### ISSUE TITLE
这句话好难理解，表示看不懂，有没有大神解答下

### ISSUE THREAD

**Issue by uEndMe** [ruanyf/es6tutorial#1000]
6.正则的扩展    /    2.字符串的正则方法 § ⇧

>>
如下：
String.prototype.match 调用 RegExp.prototype[Symbol.match]

>>
我这样理解的：
let reg = /xxx/;
reg.match('这是匹配的文字');

>>
然而并不行- -？这是为什么

**Comment by ruanyf** [comment]
https://wangdoc.com/javascript/oop/prototype.html#prototype-%E5%B1%9E%E6%80%A7%E7%9A%84%E4%BD%9C%E7%94%A8
