### ISSUE TITLE
第一章 let和const命令，关于global对象获取有一处的描述是不是有问题？

### ISSUE THREAD

**Issue by bosens-China** [ruanyf/es6tutorial#1001]
> 全局环境中，this会返回顶层对象。但是，Node 模块和 ES6 模块中，this返回的是当前模块。

你在es6的`module`一章又说`其中，尤其需要注意this的限制。ES6 模块之中，顶层的this指向undefined，即不应该在顶层代码使用this。`

这句话是不是冲突了

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
