### ISSUE TITLE
表述错误

### ISSUE THREAD

**Issue by BlackCloverM** [ruanyf/es6tutorial#1004]
![image](https://user-images.githubusercontent.com/49848204/91633925-ed565d00-ea1e-11ea-9ade-8c19615a6308.png)
应该是     response.settings.animationDuration 如果是null或undefined，就会返回默认值300。
呐，阮老师你康我说得对不对。

**Comment by ruanyf** [comment]
应该是 `response.settings` 和 `response.settings.animationDuration` 两种情况都包括了。
