### ISSUE TITLE
数组的拖拽-includes方法,提供的替代版本并不合适

### ISSUE THREAD

**Issue by ytx222** [ruanyf/es6tutorial#1005]
**箭头函数兼容性**
![image](https://user-images.githubusercontent.com/43210216/92296693-e1f8b980-ef69-11ea-92dd-7b5c095ad01f.png)
**includes兼容性**
![image](https://user-images.githubusercontent.com/43210216/92296712-0359a580-ef6a-11ea-95d5-f3aec91dcf70.png)
虽然在大多数浏览器中,箭头函数支持先于includes支持,但是有例外

**Comment by ruanyf** [comment]
教程不考虑实现的兼容性问题，而且随着时间推移，老浏览器的兼容性越来越不重要。
