### ISSUE TITLE
这本书里面好像没有讲Fetch？

### ISSUE THREAD

**Issue by cluyun** [ruanyf/es6tutorial#1013]
Fetch是用来做ajax的，可以替代之前的XMLHttpRequest。我觉得很有必要写到书里面去啊

**Comment by ruanyf** [comment]
Fetch 是 Web API，不属于 ES6，会写到其他教程。

这本书的内容范围只限于 ECMA262 标准。https://www.ecma-international.org/publications/standards/Ecma-262.htm

**Comment by cluyun** [comment]
写到哪个教程，有链接不？给个链接

**Comment by cluyun** [comment]
> Fetch 是 Web API，不属于 ES6，会写到其他教程。
> 
> 这本书的内容范围只限于 ECMA262 标准。https://www.ecma-international.org/publications/standards/Ecma-262.htm

写到哪个教程，有链接不？给个链接

**Comment by ruanyf** [comment]
会写到 Web API 教程里面，不过现在还没动笔。
