### ISSUE TITLE
变量的解构赋值 -> 1.数组的解构赋值 -> function* fibs()

### ISSUE THREAD

**Issue by Lawguancong** [ruanyf/es6tutorial#1015]
Hi, guys.
Recently, I meet some trouble when I coding, please help to fix this issue.Thx~
变量的解构赋值 -> 1.数组的解构赋值 -> function* fibs()
function* fibs() {
  let a = 0;
  let b = 1;
  while (true) {
    yield a;
    [a, b] = [b, a + b];
  }
}

let [first, second, third, fourth, fifth, sixth] = fibs();
sixth // 5
The value '5' of sixth is not correct.

But, the correct result that i coding in browser as below
function* fibs() {
            let a = 0;
            let b = 1;
            while (true) {
              yield a;
              [a, b] = [b, a + b];
            }
          }
          
        let [first, second, third, fourth, fifth, sixth] = fibs();
        console.log(first) // 0
        console.log(second) // 1
        console.log(third) // 1
        console.log(fourth) // 2
        console.log(fifth) // 3
        console.log(fifth) // 3

**Comment by ruanyf** [comment]
`sixth`确实是5。

**Comment by Lawguancong** [comment]
thx~
