### ISSUE TITLE
纸质书错别字反馈

### ISSUE THREAD

**Issue by nymstone** [ruanyf/es6tutorial#1016]
纸质书106页第四段第二行结尾处函数二字应为对象。

**Comment by ruanyf** [comment]
网站早已修正了，请以网站内容为准。

**Comment by nymstone** [comment]
emmm，买书是为了支持作者你，也是为了更好的读书体验呀，如果以网站为准，那就不买书了，你说是不？提这个建议，就是想着看能不能修正一下书中的错别字。

**Comment by ruanyf** [comment]
谢谢你的支持。纸书没法日常更新，只能积累到第四版一起更新。

**Comment by nymstone** [comment]
好的，理解。只要我的反馈，您这边接收到就行。
