### ISSUE TITLE
Promise -> 5.Promise.prototype.finally() 小节

### ISSUE THREAD

**Issue by Lawguancong** [ruanyf/es6tutorial#1017]
原文：
Promise.prototype.finally = function (callback) {
  let P = this.constructor;
  return this.then(
    value  => P.resolve(callback()).then(() => value),
    reason => P.resolve(callback()).then(() => { throw reason })
  );
};
问题：
第二个参数方法不是 reason => P.reject() ??

**Comment by ruanyf** [comment]
这个不重要，只要抛出错误，就等同于 rejected 了。

**Comment by Lawguancong** [comment]
thx~
