### ISSUE TITLE
第25节编程风格中，按照示例使用Eslint配置Airbnb报错。

### ISSUE THREAD

**Issue by iolh** [ruanyf/es6tutorial#1020]
阮老师，参照线上电子书第25节的示例Eslint配置出错，使用版本是eslint@7.13.0，原因是Eslint以及eslint-config-airbnb需要本地安装，而不是全局安装。。eslintrc配置文件是跟随项目的，所以的确更适合本地安装。当使用全局安装Eslint，执行eslint --init后也会本地安装eslint。表述如有错误之处，还望见谅！

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
