### ISSUE TITLE
null

### ISSUE THREAD

**Issue by ghost** [ruanyf/es6tutorial#1023]

**Comment by ruanyf** [comment]
这里可以不用 return，因为没有用到累积变量。而且，每一轮 async 函数不管有没有 return，总是返回一个 Promise 对象。

**Comment by rainydaycode** [comment]
那 `_` 的值是初始化的 `undefined`，我没太看懂每次都 `await undefined` 干嘛。

**Comment by rainydaycode** [comment]
原来是这个样子呀，明白了大大
