### ISSUE TITLE
类 class 的属性定义问题

### ISSUE THREAD

**Issue by zhmvictor** [ruanyf/es6tutorial#1024]
阮老师，您好，

我对**第21章-Class基本语法，类的实例**这个地方有疑惑：

> 与 ES5 一样，实例的属性除非显式定义在其本身（即定义在this对象上），否则都是定义在原型上（即定义在class上）

上面参考您写的，我写了下面的代码：
```
class Test {
  name = 'Tom';
  constructor(age) {
    this.age = age;
  }
}
const test = new Test(10);
console.log(test.hasOwnProperty('name')); // true
console.log(test.hasOwnProperty('age')); // true
```

我发现在控制台打印输出结果都为 true。

根据运行结果显示，似乎类里非显示定义在 this 对象上属性，也都是定义在 this 实例对象上的，而不是定义在类的原型上。

对此，小白的我很迷惑，希望阮老师能指点一下，谢谢。

**Comment by ruanyf** [comment]
这里指的是下面这样定义的属性。

```javascript
class foo {
  bar() {}
}
```

**Comment by zhmvictor** [comment]
懂了，谢谢

**Comment by zhmvictor** [comment]
> 这里指的是下面这样定义的属性。
> 
> ```js
> class foo {
>   bar() {}
> }
> ```

懂了，谢谢老师
