### ISSUE TITLE
Class 的基本语法 章节中: constructor() 是定义在原型上的表述不正确

### ISSUE THREAD

**Issue by GivenCui** [ruanyf/es6tutorial#1025]
![image](https://user-images.githubusercontent.com/17002107/101622806-7b94a300-3a52-11eb-9cc1-8d65396a0c73.png)

应该是

```
class Point {
  constructor() {
    // ...
  }

  toString() {
    // ...
  }

  toValue() {
    // ...
  }
}

// 等同于

Point.prototype = {
  toString() {},
  toValue() {},
};

```

`constructor()` 是 `class` 相关的语法糖,  并不是 `Point.prototype` 上的方法,  `Point.prototype`原型对象中的 `constructor`属性与 `class` 中的 `constructor()` 毫无关系

**Comment by ruanyf** [comment]
这里是想说明 prototype 上面有这个属性。
