### ISSUE TITLE
数组的扩展 copyWithin 方法例子疑问

### ISSUE THREAD

**Issue by hulingyua** [ruanyf/es6tutorial#1026]
![image](https://user-images.githubusercontent.com/32869719/102302517-2a296e00-3f94-11eb-848c-f1791147bf09.png)
`// -2相当于3号位，-1相当于4号位
[1, 2, 3, 4, 5].copyWithin(0, -2, -1)
// [4, 2, 3, 4, 5]`
这个 -2 应该是4号位，-1应该是5号位吧

**Comment by ruanyf** [comment]
0-based.
