### ISSUE TITLE
Promise.prototype.then()参数疑问

### ISSUE THREAD

**Issue by Geekhyt** [ruanyf/es6tutorial#1028]
Promise对象章节第3条原文：
> 前面说过，then方法的第一个参数是resolved状态的回调函数，第二个参数（可选）是rejected状态的回调函数。

疑问：Promise.prototype.then()的两个参数不应该都是可选参数么？

- [MDN](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/then)
- [Promises/A+](https://github.com/promises-aplus/promises-spec)

如上述资料中所述，then 的两个参数都是可选的。

《JavaScript高级程序设计》(第4版)的第十一章中也有如下描述：

> Promise.prototype.then()是为期约实例添加处理程序的主要方法。这个then()方法接收最多两个参数：onResolved处理程序和onRejected处理程序。这两个参数都是可选的，如果提供的话，则会在期约分别进入“兑现”和“拒绝”状态时执行。

- [ecma-262](https://www.ecma-international.org/ecma-262/6.0/#sec-promise.prototype.then) 好像没说参数是否都是可选参数。

阮大，求指教。

**Comment by ruanyf** [comment]
第一个参数可选指的是`.then(undefined, callback)`吧。

**Comment by Geekhyt** [comment]
是这样，阮大，我再展开说一下，下面这个例子是您原文中的例子及描述：

```javascript
promise.then(function(value) {
  // success
}, function(error) {
  // failure
});
```
> then方法可以接受两个回调函数作为参数。第一个回调函数是Promise对象的状态变为resolved时调用，第二个回调函数是Promise对象的状态变为rejected时调用。其中，第二个函数是可选的，不一定要提供。这两个函数都接受Promise对象传出的值作为参数。

下面是《JavaScript高级程序设计》(第4版)中的例子：

```javascript
let p1 = Promise.reject('foo');

// 调用then()时不传处理程序则原样向后传
let p2 = p1.then();
// Uncaught (in promise) foo
```

下面是Promises/A+ 规范中的原文：

> Both onFulfilled and onRejected are optional arguments:

> If onFulfilled is not a function, it must be ignored.
> If onRejected is not a function, it must be ignored.

我理解 then 的两个参数严谨来说的话都是可选的，不传的话就是透传。如果从严谨的角度来说，是否您文中的描述是有点小问题的。但不可否认，您举的例子是符合直觉的。

**Comment by Shenfq** [comment]
按照 Promises/A+ 的规范，原文在表述上替换成两个参数都是可选的是不是更好呢？

![image](https://user-images.githubusercontent.com/18613842/102866657-9283be00-4472-11eb-8aed-bd9141016f6f.png)

**Comment by ruanyf** [comment]
谢谢指出，我已经改过来了。
