### ISSUE TITLE
20. Module - 6. 模块的继承 - 例子中有错别字

### ISSUE THREAD

**Issue by zhanjiaxia** [ruanyf/es6tutorial#103]
第一个例子：
export \* from 'circle';
export var e = 2.71828182846;    // 这里的 e 是小写
export default function(x) {
  return Math.exp(x);
}

第三个例子：
// main.js
module math from "circleplus";
import exp from "circleplus";
console.log(exp(math.E));    // 这里的 E 是大写

**Comment by ruanyf** [comment]
已经改正，谢谢指出。
