### ISSUE TITLE
async / await is syntax sugar of promises or generator

### ISSUE THREAD

**Issue by inascf** [ruanyf/es6tutorial#1031]
i learn this from [MDN](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await) 
`More recent additions to the JavaScript language are async functions and the await keyword, part of the so-called ECMAScript 2017 JavaScript edition (see ECMAScript Next support in Mozilla). These features basically act as syntactic sugar on top of promises, making asynchronous code easier to write and to read afterwards.`
i thought it meaning syntax sugar of promise, but in your book , you said  is syntax sugar of **generator**
[ECMAScript 6 入门](https://es6.ruanyifeng.com/#docs/async), how can i understand this, thank you.

i had send you mail, but no reply

**Comment by ruanyf** [comment]
书里已经解释了。
