### ISSUE TITLE
programmersought.com 某系列文章将此书书名译为 European teacher's ECMAScript 6

### ISSUE THREAD

**Issue by gricn** [ruanyf/es6tutorial#1034]
在搜索资料的过程中，发现programmersought.com中有该书英文版翻译，虽标注了原文地址，但该系列文章将书名译为 **European teacher's ECMAScript 6**

链接如下：https://www.programmersought.com/article/17161128109/

个人觉得不太妥当，但这找不到合适的反馈方式，故在此反馈一下

**Comment by ruanyf** [comment]
这本书是“保持署名—非商用”授权，所以他们那样用是可以的。
