### ISSUE TITLE
对Promise的catch讲解中的good/bad case有一丝武断

### ISSUE THREAD

**Issue by yinsang** [ruanyf/es6tutorial#1035]
辛苦阮老师能再斟酌一下语句。
我在这篇专栏里写了详细的案例：
https://zhuanlan.zhihu.com/p/347663889

![image](https://user-images.githubusercontent.com/12373328/106102962-26842c00-617b-11eb-974c-5561f77c7073.png)

------------

因then中调用的函数错误也会触发到catch中，所以catch的功能有两个：1是捕获Promise的错误，2是捕获then里面函数的错误（例如react setState引发的render渲染错误）。

建议改为：若需要统一处理error，可以在catch中处理。若仅需要捕获当前Promise错误，而非then里面的函数造成的错误时，必须用onRejected。

**Comment by ruanyf** [comment]
你那篇文章的意思是，onRejected 专门处理 fetch 的错误，如果用了`catch()`话，会把 onFulfilled 里面的错误吃掉。

但是，`catch()`里面其实可以区分错误的类型，判断是哪一类错误，所以我觉得这不算太大的问题。

如果我也希望捕获 onFulfilled 里面的错误，就必须写成下面这样，这就有点累赘了。

```javascript
fetch(url)
.then(result => result.json())
.then(
  data => { .... }, // 渲染组件
  err => { ... } // 处理 fetch 的报错
).catch( err => { ... }) // 处理渲染过程的报错
```

**Comment by yinsang** [comment]
> 你那篇文章的意思是，onRejected 专门处理 fetch 的错误，如果用了`catch()`话，会把 onFulfilled 里面的错误吃掉。
> 
> 但是，`catch()`里面其实可以区分错误的类型，判断是哪一类错误，所以我觉得这不算太大的问题。
> 
> 如果我也希望捕获 onFulfilled 里面的错误，就必须写成下面这样，这就有点累赘了。
> 
> ```js
> fetch(url)
> .then(result => result.json())
> .then(
>   data => { .... }, // 渲染组件
>   err => { ... } // 处理 fetch 的报错
> ).catch( err => { ... }) // 处理渲染过程的报错
> ```

感谢回复，暂且这样吧
