### ISSUE TITLE
使用Array构造函数，传入单个非数值参数，可以返回由该参数组成的新数组

### ISSUE THREAD

**Issue by ChangYanwei** [ruanyf/es6tutorial#1037]
在“**数组的扩展**“章节，第三部分对 [Array.of](https://es6.ruanyifeng.com/#docs/array#Array-of) 的讲解中，有这样一段描述：

> Array方法没有参数、一个参数、三个参数时，返回结果都不一样。**只有当参数个数不少于 2 个时，Array()才会返回由参数组成的新数组。** 参数个数只有一个时，实际上是指定数组的长度。

如果对Array构造函数，传入单个非数值参数（比如字符串、布尔值、对象等），则可以返回由该参数组成的新数组。

`new Array('hello');` 输出 `["hello"]`

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
