### ISSUE TITLE
async 函数中关于await的疑问

### ISSUE THREAD

**Issue by fanhualu** [ruanyf/es6tutorial#1042]
**20. async 函数  => 1.含义**

> 一比较就会发现，async函数就是将 Generator 函数的星号（*）替换成async，**将yield替换成await**，仅此而已。
> ... ...
> 进一步说，async函数完全可以看作多个异步操作，包装成的一个 Promise 对象，而**await命令就是内部then命令的语法糖**。

疑问是：为什么说await命令是内部then的语法糖呢？看起来更像是yield的语法糖呀？上文也讲了**yield替换成await**

**Comment by ruanyf** [comment]
后一段是谈 async 与· Promise 的相似性。await 同时可以用来替代 yield 和 then，都有一点语法糖的意思。
