### ISSUE TITLE
关于String.raw()的问题

### ISSUE THREAD

**Issue by xiekaifei** [ruanyf/es6tutorial#1043]
阮老师，你好。
最近在看您的ES6书籍，发现一个问题。
在[第5章：字符串的新增方法中](https://es6.ruanyifeng.com/#docs/string-methods#String-raw)，描述`String.raw()`作为函数的代码实现方法时，列出的实现代码在执行的时候和原生的方法输出的结果有所不同。

<img width="608" alt="raw" src="https://user-images.githubusercontent.com/36142352/113512865-4976f600-9599-11eb-89f5-38091eff3e37.png">

传入参数`String.raw({ raw: 'test' }, 0, 1, 2, 3)`，原生方法输出`t0e1s2t`，文章里代码输出`t0e1s2t3undefined`。
所以实现代码是不是应该改为下面这样：

```javascript
String.raw = function (strings, ...values) {
  let output = '';
  let index;
  let length = strings.raw.length > 0 ? strings.raw.length - 1 : 0;
  for (index = 0; index < length; index++) {
    let text = values[index] !== undefined ? values[index] : '';
    output += strings.raw[index] + text;
  }

  output += strings.raw[index]
  return output;
}
```

**Comment by ruanyf** [comment]
教程里的实现只是一个原理的演示，假设字符串的长度总是比 values 数组大`1`。
