### ISSUE TITLE
Generator函数的异步使用似乎有误

### ISSUE THREAD

**Issue by RadiumAg** [ruanyf/es6tutorial#1046]
阮老师，Generator函数的异步使用似乎有误
![image](https://user-images.githubusercontent.com/48897151/115563010-a983d100-a2e9-11eb-8bb3-254a9ce59f6c.png)

**Comment by ruanyf** [comment]
Node.js 约定 callback 第一个参数是 err 对象。

**Comment by RadiumAg** [comment]
okok,后来又看了一遍，发现如果result.value是Thunk函数，确实是result.value(next)
