### ISSUE TITLE
let 存在变量提升

### ISSUE THREAD

**Issue by xmz-dream** [ruanyf/es6tutorial#1049]
参考：https://stackoverflow.com/questions/31219420/are-variables-declared-with-let-or-const-hoisted/31222689#31222689

**Comment by ruanyf** [comment]
会报错，不能叫做提升吧。

**Comment by Liuxingwei** [comment]
如果把“定义”和“赋初值”这两个动作同时完成视为提升的话，let 就不存在提升。

如果只把完成“定义”这个动作视为提升的话，let 就存在提升。

浏览器和node.js实现是把这两个动作拆开的。

`
console.log(a); // ReferenceError: b is not defined
`

`
console.log(a); // ReferenceError: Cannot access 'c' before initialization
`
`
let a;
`

MDN 文档认为这也是一种提升：

> 在 ECMAScript 6 中，let和const同样会被**提升**变量到代码块的顶部但是不会被赋予初始值。在变量声明之前引用这个变量，将抛出引用错误（ReferenceError）。这个变量将从代码块一开始的时候就处在一个“暂时性死区”，直到这个变量被声明为止。

参见：[https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Grammar_and_types#%E5%8F%98%E9%87%8F%E7%9A%84%E4%BD%9C%E7%94%A8%E5%9F%9F](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Grammar_and_types#%E5%8F%98%E9%87%8F%E7%9A%84%E4%BD%9C%E7%94%A8%E5%9F%9F)

**Comment by Liuxingwei** [comment]
如果把“定义”和“赋初值”这两个动作同时完成视为提升的话，let 就不存在提升。
如果只把完成“定义”这个动作视为提升的话，let 就存在提升。
浏览器和node.js实现是把这两个动作拆开的。
`
console.log(a); // ReferenceError: b is not defined
`
`
console.log(a); // ReferenceError: Cannot access 'c' before initialization
let a;
`
MDN 文档认为这也是一种提升：

> 在 ECMAScript 6 中，let和const同样会被提升变量到代码块的顶部但是不会被赋予初始值。在变量声明之前引用这个变量，将抛出引用错误（ReferenceError）。这个变量将从代码块一开始的时候就处在一个“暂时性死区”，直到这个变量被声明为止。

参见：[https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Grammar_and_types#%E5%8F%98%E9%87%8F%E7%9A%84%E4%BD%9C%E7%94%A8%E5%9F%9F](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Grammar_and_types#%E5%8F%98%E9%87%8F%E7%9A%84%E4%BD%9C%E7%94%A8%E5%9F%9F)
