### ISSUE TITLE
21类的基本语法，类和构造

### ISSUE THREAD

**Issue by keduhoutian** [ruanyf/es6tutorial#1060]
原文：
`class Point {
    constructor() {
      // ...
    }
    toString() {
      // ...
    }
}`
// 等同于
`Point.prototype = {
    constructor() {},
    toString() {}
}`

这里感觉不能完全这么说？一般构造函数是下面这样吗？
`Point.prototype = {
    constructor:Point,
    toString() {}
}`
即`Point.prototype.constructor === Point`

**Comment by ruanyf** [comment]
这里只是说明，类的定义等价于原型，不是给出精确的实现。
