### ISSUE TITLE
let章节的两个细节

### ISSUE THREAD

**Issue by sapjax** [ruanyf/es6tutorial#108]
- **[不存在变量提升](https://github.com/ruanyf/es6tutorial/blob/gh-pages/docs/let.md#%E4%B8%8D%E5%AD%98%E5%9C%A8%E5%8F%98%E9%87%8F%E6%8F%90%E5%8D%87)** 这一节结尾对`typeof`的解释可能引起歧义，这里`typeof x` 报错的原因并不是**不存在变量提升**和**`x`还没有声明**，而是因为下面的`let x`导致的**暂时性死区**。单独一句`typeof x`并不会报错，关于typeof的这一段移到下一节比较好。
- **[const命令](https://github.com/ruanyf/es6tutorial/blob/gh-pages/docs/let.md#const%E5%91%BD%E4%BB%A4)** 中的这一段：
  
  > ``` javascript
  > const foo;
  > // SyntaxError: missing = in const declaration
  > ```
  > 
  > 上面代码表示，对于const来说，只声明不赋值，就会报错。
  
  `const`不赋值的话，只有在严格模式下才会报错。
  
  另外下面的:
  
  > ``````
  > ```javascript
  > const foo = Object.freeze({});
  > foo.prop = 123; // 不起作用
  > ```
  > 上面代码中，常量foo指向一个冻结的对象，所以添加新属性不起作用。
  > ``````
  
  给冻结对象添加属性，在常规模式下是不起作用，在严格模式下则会报错。
  结合这两段代码示例，前者运行在严格模式，后者运行在常规模式，而不同摸下的结果都不同，我觉得全书的示例最好统一到一个模式下，或者单独标明是哪种模式。

**Comment by ruanyf** [comment]
谢谢指出，说得很正确，我已经改过来了。
