### ISSUE TITLE
数组的扩展-合并数组 拷贝类型说明疑似错误

### ISSUE THREAD

**Issue by fsyRunning** [ruanyf/es6tutorial#1091]
const a3 = a1.concat(a2);
const a4 = [...a1, ...a2];
经控制台测试，这两种写法都不是浅拷贝，修改a1和a2的值都不会影响a3和a4，下面是原文和测试
![image](https://user-images.githubusercontent.com/92191746/140679340-2ff56923-a5c8-4af4-96b9-8f11ecd6e5ea.png)
![image](https://user-images.githubusercontent.com/92191746/140679166-bb555996-cadf-4b6b-8011-1e12a00fe3fb.png)

**Comment by ruanyf** [comment]
a1[0].foo = 2;
a1[0].foo === a3[0].foo
