### ISSUE TITLE
关于 array like 的定义模糊，和扩展运算符 中的错误

### ISSUE THREAD

**Issue by SimplyY** [ruanyf/es6tutorial#111]
http://es6.ruanyifeng.com/#docs/array#Array-from 

这里Array.from方法用于将两类对象转为真正的数组：类似数组的对象（array-like object）和可遍历（iterable）的对象

``` js
let arrayLike = {
    '0': 'a',
    '1': 'b',
    '2': 'c',
    length: 3
};
```

但是 http://es6.ruanyifeng.com/#docs/function#扩展运算符的应用这里

5）类似数组的对象

任何类似数组的对象，都可以用扩展运算符转为真正的数组。

``` js
var nodeList = document.querySelectorAll('div');
var array = [...nodeList];
```

这里明显有问题，对于扩展运算符，只能对于可遍历（iterable）的对象

> MDN
> The spread operator allows an expression to be expanded in places where multiple arguments (for function calls) or multiple elements (for array literals) are expected.

 (for array literals) ,而不是任何类似数组的对象。

所以书中应该明确指出数组的对象（array-like object）和可遍历（iterable）的对象两者的区别。

**Comment by SimplyY** [comment]
![Uploading image.png…]()

**Comment by SimplyY** [comment]
网卡了，出现了异常操作，最近墙真厉害，我的 ss 总是要换节点= =

**Comment by ruanyf** [comment]
你可以在Babel试一下，是可以转的。

``` javascript
let arrayLike = {
    '0': 'a',
    '1': 'b',
    '2': 'c',
    length: 3
};

let array = [...arrayLike];
```

**Comment by ruanyf** [comment]
查了规格，Babel的实现居然是不对的，确实不能转……
