### ISSUE TITLE
8.函数的扩展 复杂度问题

### ISSUE THREAD

**Issue by Cubexp** [ruanyf/es6tutorial#1114]
![](https://s3.bmp.ovh/imgs/2022/05/01/9c41b9cd0014fb5a.png)
复杂度O(n)改为空间复杂度O(n)，或许更加准确一些。
直接说复杂度的话，感觉包括了空间复杂度与时间复杂度，文章中空间复杂度变成了O(1)，但时间复杂度是没有变化的。

**Comment by ruanyf** [comment]
原文没错。
