### ISSUE TITLE
【21.async 函数】【3.语法】【Promise 对象的状态变化】代码错误

### ISSUE THREAD

**Issue by itchaox** [ruanyf/es6tutorial#1120]
`async function getTitle(url) {
  let response = await fetch(url);
  let html = await response.text();
  return html.match(/<title>([\s\S]+)<\/title>/i)[1];
}
getTitle('https://tc39.github.io/ecma262/').then(console.log)  // 这里应该修改为 .then( v => console.log(v) )
// "ECMAScript 2017 Language Specification"`

**Comment by itchaox** [comment]
阮一峰大佬，这个问题需要处理吗？

itchao
2022年6月29日15:26:12

**Comment by itchaox** [comment]
async function getTitle(url) { 
let response = await fetch(url); 
let html = await response.text(); 
return html.match(/<title>([\s\S]+)<\/title>/i)[1]; 
} 
getTitle('https://tc39.github.io/ecma262/').then(console.log) // 这里应该修改为 .then( v => console.log(v) ) 
// "ECMAScript 2017 Language Specification"

**Comment by ruanyf** [comment]
请不要提这么低级的 issue，尊重别人的时间。

Promise.resolve(1).then(console.log)

**Comment by itchaox** [comment]
好的
