### ISSUE TITLE
Symbol章 下的“Symbol.hasInstance”节

### ISSUE THREAD

**Issue by LiuCaptain** [ruanyf/es6tutorial#1124]
![image](https://user-images.githubusercontent.com/43247357/177477747-90705b65-b083-495c-84b0-92a76e48f7ff.png)

我把这段代码放进一个react项目中测试时报错，

![image](https://user-images.githubusercontent.com/43247357/177477894-7d62e5cc-2879-494b-a37b-94ca02cb3bb0.png)

请问这是因为什么问题呢

**Comment by ruanyf** [comment]
issue 不用来答疑。

**Comment by LiuCaptain** [comment]
了解。但是我是将例子代码复制进去react项目里面测试，结果报错，有没有可能例子代码存在一定问题

**Comment by LiuCaptain** [comment]
> issue 不用来答疑。
了解。但是我是将例子代码复制进去react项目里面测试，结果报错，有没有可能例子代码存在一定问题
