### ISSUE TITLE
21async 函数 =》 5.与其他异步处理方法的比较

### ISSUE THREAD

**Issue by LiuCaptain** [ruanyf/es6tutorial#1127]
“假定某个 DOM 元素上面，部署了一系列的动画，前一个动画结束，才能开始后一个。如果当中有一个动画出错，就不再往下执行，返回上一个成功执行的动画的返回值。”

这段当中有句 “如果当中有一个动画出错，就不再往下执行”

但是下文列举三种代码写法，为什么都是 /* 忽略错误，继续执行 */，是否是与上文有所矛盾?

**Comment by ruanyf** [comment]
这个“继续执行”，不是指继续执行下一个动画，而是指继续执行动画后面的代码。
