### ISSUE TITLE
所有页面已不能正常访问

### ISSUE THREAD

**Issue by Eventidus** [ruanyf/es6tutorial#1129]
打开任一网页，都提示这样的错误信息：

![image](https://user-images.githubusercontent.com/49816387/182543730-aed67022-9424-4cbc-984c-667853622ea2.png)

**Comment by liiiiiiiiiiiir** [comment]
可以暂时使用 https://wangdoc.com/es6/ 官方镜像

**Comment by ruanyf** [comment]
可能跟广告拦截器冲突，你把域名加入白名单试试看。
