### ISSUE TITLE
对于es6 简介那一章的一些建议

### ISSUE THREAD

**Issue by SimplyY** [ruanyf/es6tutorial#113]
当然我是 想直接 PR 的，不过不知道您的意见是怎样，于是先写到这里，看看您的意见。
1. 对于使用 es6的方案很多，但操作性不强，特别是对于那些水平差一点的（比如我女朋友），说不定就会直接放弃，如果能有一个方便一点的测试方案用于学习就好了。
2. 我看 MDN 的时候发现 firefox 支持了好多 es6 语法，于是我去查了一下 在 http://kangax.github.io/compat-table/es6/ 里发现 FF45（firefox）里除了§block-level function declaration[12] 不支持其他的支持程度甚至强于 babel，所以我们为何不加一个学习测试用的方法，推荐用户用 FF45（或更新版） 对 es6 语法学习的时候进行测试运行呢？而且交互式运行环境对于学习很有帮助。
3. 我觉得应该向读者推荐一下 MDN，虽然 MDN 的可读性很差，但是作为查询的文档，没读懂的地方去查它，有了它可以让大家对 es6 语法有更深的理解。

谢谢。

**Comment by ruanyf** [comment]
MDN一搜就能搜到，就不特别推荐了。附录里面还有很多参考链接，可以查看
