### ISSUE TITLE
如果按照文档所说，协程应该是并发执行的，期望解读

### ISSUE THREAD

**Issue by yfools** [ruanyf/es6tutorial#1138]
”协程与其不同，多个线程（单线程情况下，即多个函数）可以并行执行，但是只有一个线程（或函数）处于正在运行的状态，其他线程（或函数）都处于暂停态（suspended），线程（或函数）之间可以交换执行权。“

并行是同一时刻运行多个任务；
觉得改成“多个协程可以并发执行”会更好，不知道是不是笔误，但是读来觉得不太通顺。

**Comment by ruanyf** [comment]
并发不是更好的表达。
