### ISSUE TITLE
18、Iterator 和 for...of 循环

### ISSUE THREAD

**Issue by LiuCaptain** [ruanyf/es6tutorial#1143]
书中有句，“指针对象的next方法，用来移动指针。开始时，指针指向数组的开始位置。然后，每次调用next方法，指针就会指向数组的下一个成员。第一次调用，指向a；第二次调用，指向b。”

不是扣字眼，我觉得这句“每次调用next方法，指针就会指向数组的下一个成员”，与后面的“第一次调用，指向a；第二次调用，指向b”，自相矛盾，如果每次调用指针会指向下一个成员，但是为啥第一次调用，会指向a，下一个成员不应该是 b 吗

**Comment by ruanyf** [comment]
没调用之前，指针在数组之外。
