### ISSUE TITLE
Module 的语法

### ISSUE THREAD

**Issue by freemedom** [ruanyf/es6tutorial#1151]
https://es6.ruanyifeng.com/#docs/module#import-%E5%91%BD%E4%BB%A4
> import后面的from指定模块文件的位置，可以是相对路径，也可以是绝对路径。如果不带有路径，只是一个模块名，那么必须有配置文件，告诉 JavaScript 引擎该模块的位置。

请问这个**配置文件**是什么意思，查了查似乎没有配置文件这个说法

**Comment by ruanyf** [comment]
一般是 package.json 的 main 字段。
