### ISSUE TITLE
关于Promise.resolve()是在本轮“事件循环”（event loop）的结束时执行，还是在下一轮“事件循环”的开始时的疑问

### ISSUE THREAD

**Issue by ChenKun1997** [ruanyf/es6tutorial#1158]
https://es6.ruanyifeng.com/#docs/promise#Promise-resolve 
阮老师您好，我有个疑问，下图中，划线句子下面有个例子，这个例子好像并不能证明 `立即resolve()的 Promise 对象，是在本轮“事件循环”（event loop）的结束时执行，而不是在下一轮“事件循环”的开始时。` 这句话。如果它是下一轮事件循环开始时执行，输出结果应该也是一样的不是吗，
![image](https://github.com/ruanyf/es6tutorial/assets/24249578/a52cbc1a-21c1-4408-93a6-59d6a936c62b)

**Comment by ruanyf** [comment]
如果是在下一轮循环的开头，按照代码顺序，它应该排在 setTimeout(fn, 0) 的后面。
