### ISSUE TITLE
iso和ecma

### ISSUE THREAD

**Issue by 404pnf** [ruanyf/es6tutorial#116]
// intro.md

> 决定将JavaScript提交给国际标准化组织ECMA

国际标准化组织 可以算是专有名词吧，特指 International Organization for Standardization

ECMA是另一个组织 European Computer Manufactures Association。

文中的句子可重新考虑一下，现在比较让人迷惑。

另，一个美国公司跑到欧洲请欧洲机构做标准化，太离谱了吧！？背后原因，去看Douglas Crockford在YUI讲js的视频（历史篇）就知道了。 ：）

**Comment by ruanyf** [comment]
ECMA早就改名了。

> Ecma International is an international private (membership-based) non-profit standards organization for information and communication systems.[1] It acquired its current name in 1994, when the European Computer Manufacturers Association (ECMA) changed its name to reflect the organization's global reach and activities. As a consequence, the name is no longer considered an acronym and no longer uses full capitalization.

-- Wikipedia

https://en.wikipedia.org/wiki/Ecma_International

**Comment by 404pnf** [comment]
明白了。文中的国际标准化组织是形容词，那个英文也无需全部大写。 谢谢。
