### ISSUE TITLE
array grouyBy是写错了么

### ISSUE THREAD

**Issue by cuidong626** [ruanyf/es6tutorial#1161]
array grouyBy是写错了么？标题没有这个函数名称？
![image](https://github.com/ruanyf/es6tutorial/assets/22650893/2b5423fe-bc02-4ef4-8f42-33a2059b7850)

**Comment by cuidong626** [comment]
看样子是写错了
![image](https://github.com/ruanyf/es6tutorial/assets/22650893/dc391de3-0da0-4b92-a2a8-e9a19d9506aa)

**Comment by ruanyf** [comment]
已经改过来了。
