### ISSUE TITLE
关于 WeakSet WeakMap 的使用表现与文档不一致的问题

### ISSUE THREAD

**Issue by sdshaoda** [ruanyf/es6tutorial#1162]
在查看文档时发现 WeakSet 在控制台的表现，和文档示例中不一致。
`ws.add(Symbol())` 在文档中 “上面代码试图向 WeakSet 添加一个数值和Symbol值，结果报错，因为 WeakSet 只能放置对象”，但实际上在控制台重复这个代码没问题
![image](https://github.com/ruanyf/es6tutorial/assets/21106848/64a1b100-e543-4413-8e66-d65940607e72)
![image](https://github.com/ruanyf/es6tutorial/assets/21106848/e148e0e8-6f28-474a-aac9-e69e1826a414)

**Comment by sdshaoda** [comment]
WeakMap 也有此问题，文档中 `map.set(Symbol(), 2)` 会报错，实际可以成功
![image](https://github.com/ruanyf/es6tutorial/assets/21106848/287225c5-38f5-4c72-b190-9670a6d09e2f)
![image](https://github.com/ruanyf/es6tutorial/assets/21106848/ec20b3f8-33c4-475b-bb64-787447d3e0f7)

**Comment by sdshaoda** [comment]
应该是最新版的 Chrome 已经实现了 Stage 3的提案 https://github.com/tc39/proposal-symbols-as-weakmap-keys

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
