### ISSUE TITLE
函数拓展中的length属性

### ISSUE THREAD

**Issue by honpery** [ruanyf/es6tutorial#117]
既然前面提到了参数默认值的位置的问题，那么存在着下面的情况

var fun = function (a, b = 1, c, d = 1) {
  console.log(fun.length); 
}
fun(1, 2, 3, 4);  // 3

那可能原文描述的不准确了。怎么说我也不知道 - -

**Comment by ruanyf** [comment]
length属性表示的是预期传入的参数，第二个参数是没法省略的，因此length属性还是对的。

**Comment by XGHeaven** [comment]
我测试了一下，发现并没有这种问题。
![image](https://cloud.githubusercontent.com/assets/9291212/12253271/a8646f42-b919-11e5-889f-3b07517decff.png)
我的 Node 版本是
![image](https://cloud.githubusercontent.com/assets/9291212/12253276/ba2f82ca-b919-11e5-8701-a620e9ce4dfa.png)

@ruanyf @honpery

**Comment by ruanyf** [comment]
返回3是对的。Node的实现有问题。

参见标准 http://www.ecma-international.org/ecma-262/6.0/#sec-14.1.6

注意这段话：

> "The ExpectedArgumentCount of a FormalParameterList is the number of FormalParameters to the left of either the rest parameter or the first FormalParameter with an Initializer."

**Comment by XGHeaven** [comment]
@ruanyf 阮老师，问一下 `FormalParameterList` 是什么意思？
和 `FormalsList` 有什么区别？

**Comment by ruanyf** [comment]
我觉得 `FormalParameterList` 是 `FormalsList` 的一种吧。

**Comment by XGHeaven** [comment]
@ruanyf 似乎文档中没有详细解释这是什么，只是给了一个很粗浅的概念，不太懂什么意思。
