### ISSUE TITLE
文档中的链接需要更新，原链接已经404

### ISSUE THREAD

**Issue by sclchic** [ruanyf/es6tutorial#1170]
## 文档地址
https://es6.ruanyifeng.com/#docs/intro
## 需更新的位置

> 目前，各大浏览器对 ES6 的支持可以查看[kangax.github.io/compat-table/es6/](https://kangax.github.io/compat-table/es6/)。
## 需更新为
https://compat-table.github.io/compat-table/es6/

**Comment by ruanyf** [comment]
谢谢指出，已经更正
