### ISSUE TITLE
类装饰器目前没有上下文对象传参

### ISSUE THREAD

**Issue by HuRuilin** [ruanyf/es6tutorial#1175]
阮老师好：
查看类装饰器类型声明如下：declare type ClassDecorator = <TFunction extends Function>(target: TFunction) => TFunction | void;
并没有context 参数，与decorator 装饰器章节内容不符。是我理解错了，还是教程没有更新呢？

**Comment by ruanyf** [comment]
参见 TypeScript 教程，后面会改。https://wangdoc.com/typescript/decorator
