### ISSUE TITLE
array comprehension 不在ES6标准中

### ISSUE THREAD

**Issue by GTxx** [ruanyf/es6tutorial#128]
数组推导确定[不是ES6标准](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Array_comprehensions)了， 在babel中好像也取消了对array comprehension的支持：
http://babeljs.io/docs/learn-es2015/#comprehensions

是否考虑把 [数组推导](http://es6.ruanyifeng.com/#docs/array#数组推导) 这一小节删掉？

**Comment by ruanyf** [comment]
我有点犹豫。当初的说法是，ES7会包括array comprehension。

我想再等一等确切消息，如果ES7确认放弃array comprehension，我就删掉它。
