### ISSUE TITLE
ArrayComprehension

### ISSUE THREAD

**Issue by army8735** [ruanyf/es6tutorial#13]
网站上留言估计看不到。

firefox30已更改为标准实现，赋值表达式是在末尾，for关键字作为lookahead确定进入arraycmph。

https://developer.mozilla.org/en-US/Firefox/Releases/30

ArrayComprehension[Yield] :

[ Comprehension[?Yield] ]

Comprehension[Yield] :

ComprehensionFor[?Yield] ComprehensionTail[?Yield]

ComprehensionTail[Yield] :

AssignmentExpression[In, ?Yield]

ComprehensionFor[?Yield] ComprehensionTail[?Yield]

ComprehensionIf[?Yield] ComprehensionTail[?Yield]

ComprehensionFor[Yield] :

for ( ForBinding[?Yield] of AssignmentExpression[In, ?Yield] )

ComprehensionIf[Yield] :

if ( AssignmentExpression[In, ?Yield] )

ForBinding[Yield] :

BindingIdentifier[?Yield]

BindingPattern[?Yield]

**Comment by army8735** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Array_comprehensions

**Comment by ruanyf** [comment]
谢谢指出，真没注意到这个问题，已经改过来了。

**Comment by army8735** [comment]
忘了说了，介绍里面有个留言，希望能介绍下我的jsdc转换器，简短的就行，支持下国产，thx~

**Comment by ruanyf** [comment]
加到《参考链接》部分了

http://es6.ruanyifeng.com/#docs/reference

2014年6月12日 下午2:57于 "army8735" notifications@github.com写道：
