### ISSUE TITLE
Module章节关于CommonJS的错误

### ISSUE THREAD

**Issue by sapjax** [ruanyf/es6tutorial#139]
[ES6模块加载的实质](http://es6.ruanyifeng.com/#docs/module#ES6模块加载的实质)

> ES6模块加载的机制，与CommonJS模块完全不同。CommonJS模块输出的是一个值的拷贝，而ES6模块输出的是值的引用。
> 
> CommonJS模块输出的是被输出值的拷贝，也就是说，一旦输出一个值，模块内部的变化就影响不到这个值。请看下面这个模块文件lib.js的例子。
> 
> ``` javascript
> // lib.js
> var counter = 3;
> function incCounter() {
>   counter++;
> }
> module.exports = {
>   get counter() {
>     return counter;
>   },
>   incCounter: incCounter,
> };
> ```
> 
> 上面代码输出内部变量counter和改写这个变量的内部方法incCounter。然后，在main.js里面加载这个模块。
> 
> ``` javascript
> // main.js
> var counter = require('./lib').counter;
> var incCounter = require('./lib').incCounter;
> 
> console.log(counter);  // 3
> incCounter();
> console.log(counter); // 3
> ```
> 
> 上面代码说明，counter输出以后，lib.js模块内部的变化就影响不到counter了。

---

上面这一段整体描述都有错误，CommonJS**并不是输出一个值的拷贝**，对象始终是按引用传递的，例子中的问题出现在下面一句:

``` javascript
var counter = require('./lib').counter;
```

在你给counter变量赋值的时候，因为`require('./lib').counter`是一个基本类型的数据，所以counter变量在**赋值的时候拷贝了值**，和CommonJS的输出没有关系， 把例子改一下做一下对比：

``` javascript
// main.js
var lib = require('./lib')
var incCounter = require('./lib').incCounter;

> console.log(lib.counter);  // 3
incCounter();
console.log(lib.counter); // 4
```

上面的代码中，把`require('./lib')`赋值给`lib`变量，因为`require('./lib')`返回的是一个对象，所以`lib`变量对原对象的引用，所以最后输出4。
而ES6模块之所以没有问题是因为：ES6模块的输出和上面的情况类似，本质上还是相当于在命名空间下的。

**Comment by sapjax** [comment]
看到了评论下面的解释，**我的理解有误**，CommonJS输出的对象上的**基本类型**的属性值确实会被缓存下来。
不过文章中的描述可以改成下面这样，更准确一点：

> CommonJS模块输出的对象上的**基本类型**属性，是对应值的拷贝

**Comment by ruanyf** [comment]
我改了一下，现在应该说得更清楚了。

https://github.com/ruanyf/es6tutorial/commit/3cec648ff2e9ecd830d7dcf5a8a13918ea484b7f
