### ISSUE TITLE
不错

### ISSUE THREAD

**Issue by xiongxin** [ruanyf/es6tutorial#14]
阮老师有时间可以翻译ecma-262这本书。专业术语太多了

**Comment by zqzhang** [comment]
@kennyluck 等人已然翻译，见：http://www.w3.org/html/ig/zh/wiki/ES5

本人打算[近期对该翻译进行校订](http://lists.w3.org/Archives/Public/public-html-ig-zh/2014Jul/0000.html)，有兴趣的话可一起参与。

同时，@kennyluck也着手翻译ES6，见：http://www.w3.org/html/ig/zh/wiki/ES6

因搜索ES6新特性至此，见谅。

**Comment by jerrylau91** [comment]
支持一下！
