### ISSUE TITLE
希望尽快把github上已经解决的问题同步到官网

### ISSUE THREAD

**Issue by iyongliang** [ruanyf/es6tutorial#145]
我买了第一版的，现在照着 [官网](http://es6.ruanyifeng.com/)在看两个版本的差距，发现例如REPL写成PEPL之类的错误，本来想在github提issue的，但是发现您的文档已经修改过了。
希望能把最新修改的结果同步到官网，非常感谢这本书。

**Comment by ruanyf** [comment]
谢谢你购买这本书，欢迎多提宝贵意见。

Github源码库与网站版本是同步的。只要源码改了，网页就会同步反应出来。
