### ISSUE TITLE
19.2方法的修饰

### ISSUE THREAD

**Issue by JChehe** [ruanyf/es6tutorial#146]
### 第19章 修饰器

**19.2方法的修饰**

```
@testable  
class Person {
  @readonly
  @nonenumerable
  name() { return `${this.first} ${this.last}` }
}
```

> 原文是：从上面代码中，我们一眼就能看出，**MyTestableClass类**是可测试的，而name方法是只读和不可枚举的。

我的疑问是：代码中并没有出现 `MyTestableClass` 类（在19.1 类的修饰提到了），这里是不是应该是 `Person` 类呢？

**Comment by XGHeaven** [comment]
应该是写错了

**Comment by ruanyf** [comment]
谢谢指出，已经合并PR了。
