### ISSUE TITLE
关于严格模式

### ISSUE THREAD

**Issue by willin** [ruanyf/es6tutorial#155]
在第20个章节Module里面提到**严格模式**(同时我也好奇为什么放在这个章节里)：

> ES6的模块自动采用严格模式，不管你有没有在模块头部加上`'use strict';`。

既然是这样的话，我个人的感觉是那就不加了吧，既能节省几个字节的开销，又避免了忘记写导致的不同源码文件之间存在差异性。

而在**编程风格**章节中有几个例子专门加上了`'use strict';`我不知道这是不是一种刻意的引导，以及是否有这样的必要

**Comment by ruanyf** [comment]
这里是为了提醒读者，下面的示例代码是严格模式，可以看做注释。

以后，模块功能普遍支持了，这行可以不加。
