### ISSUE TITLE
关于Promise#catch的解释

### ISSUE THREAD

**Issue by sapjax** [ruanyf/es6tutorial#156]
[Promise.prototype.catch()](http://es6.ruanyifeng.com/#docs/promise#Promise-prototype-catch)

> ``` javascript
> // bad
> promise
>   .then(function(data) {
>     // success
>   }, function(err) {
>     // error
>   });
> 
> // good
> promise
>   .then(function(data) { //cb
>     // success
>   })
>   .catch(function(err) {
>     // error
>   });
> ```
> 
> 上面代码中，第二种写法要好于第一种写法，理由是前者更接近同步的写法（try/catch）。

最后的解释不是很准确，这里推荐用`catch`是因为：如果在`then`中(不是Promise执行过程中)抛出了一个错误，`then`的第二个参(数`onRejected`处理函数)是无法捕获到错误的，而`catch`的写法是可以捕获到的。

**Comment by willin** [comment]
这个我个人感觉只要知道第二种写法好就行了，要说好的理由还能举出很多来，举个栗子：

``` javascript
// bad
promise.then(function(data1) {
    // success1
  }, function(err) {
    // error
  }).then(function(data2) {
    // success2
  }, function(err) {
    // error
    // 两者的错误捕获方法相同
  });

// good
promise
  .then(function(data1) { //cb
    // success1
  })
  .then(function(data2) { //cb
    // success2
  })
  .catch(function(err) {
    // error
    // 只catch了一次
  });
```

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
