### ISSUE TITLE
WeakSet已有

### ISSUE THREAD

**Issue by dou4cc** [ruanyf/es6tutorial#16]
是不是应该补充进去。。。
https://developer.mozilla.org/en-US/docs/Web/JavaScript/ECMAScript_6_support_in_Mozilla 的末尾的未支持项目提到了WeakSet。

**Comment by ruanyf** [comment]
抱歉，出国中，没有及时回复。

WeakSet的资料很少，也没有任何实现，用途又很有限，等有更多资料再写入教程吧。
2014年7月15日 下午8:40于 "dou4cc" notifications@github.com写道：

**Comment by dou4cc** [comment]
WeakSet在最新版的Firefox Nightly和最新版的Chrome Canary中都实现了

**Comment by joshyu** [comment]
大范围的工程应用还是需要稳定版下来再说
