### ISSUE TITLE
关于正则的扩展

### ISSUE THREAD

**Issue by cntanglijun** [ruanyf/es6tutorial#162]
![1](https://cloud.githubusercontent.com/assets/13279117/13943925/f1f6e190-f03b-11e5-9a7b-2340d5891def.jpg)
![2](https://cloud.githubusercontent.com/assets/13279117/13943971/36ba8aac-f03c-11e5-9f6f-fc25e9756500.jpg)

[https://leanpub.com/understandinges6/read/#leanpub-auto-duplicating-regular-expressions](https://leanpub.com/understandinges6/read/#leanpub-auto-duplicating-regular-expressions)

**Comment by ruanyf** [comment]
谢谢指出，已经改正了。
