### ISSUE TITLE
I'd like to know how to use dead simple to write this book

### ISSUE THREAD

**Issue by jiaoqiang1** [ruanyf/es6tutorial#166]
I have been to looking for this problem, can be ability is limited. No rubber to understand, can you tell me??

**Comment by hypogaea** [comment]
这位作者很少在这里，你要联系他可以去他官网。另外他也是中国人，没必要用英语。。。你的话我看了好几遍才懂。。。

**Comment by ruanyf** [comment]
what is 'dead simple'?
