### ISSUE TITLE
界面在某些情况出现了问题

### ISSUE THREAD

**Issue by dou4cc** [ruanyf/es6tutorial#17]
在保证不进入手机画面的前提下缩小网页宽度，会出现左右移动的滚动条，把条条向右移，正文就向左移动了，此时正文会透过目录显示出来。希望把目录的背景设成白色以避免此情况。

**Comment by ruanyf** [comment]
目前的网页自适应设置比较简单，我你提的那个方法，我觉得不是很elegent，等下次软件升级的时候再解决吧。
2014年7月16日 上午9:23于 "dou4cc" notifications@github.com写道：
