### ISSUE TITLE
let和const命令那一章中有版本区别，应该需要标注一下

### ISSUE THREAD

**Issue by erniu** [ruanyf/es6tutorial#178]
> 有些“死区”比较隐蔽，不太容易发现。
> function bar(x = y, y = 2) {
>   return [x, y];
> }
> bar(); // 报错

我验证过，这个是否报错应该与v8的版本有关。比如在V8 5.0.71.33中，就会报ReferenceError，但是在下面这个环境中(v8: '5.0.71.35')就不会报错：

```
{
    babel: '1.0.0',
    npm: '3.8.6',
    ares: '1.10.1-DEV',
    http_parser: '2.7.0',
    icu: '56.1',
    modules: '48',
    node: '6.0.0',
    openssl: '1.0.2g',
    uv: '1.9.0',
    v8: '5.0.71.35',
    zlib: '1.2.8'
}
```

它的返回值应该是`[ undefined, 2 ]`

**Comment by ruanyf** [comment]
确实有这个问题，不是每个实现都报错，我加了一句说明。
