### ISSUE TITLE
about the arrow-functions in es6

### ISSUE THREAD

**Issue by Hancoson** [ruanyf/es6tutorial#179]
```
const Template = {
    test: function(){
        console.log(this); //object
        $('#event').on('click',()=>{
            console.log(this);//object
        });
    }
};
Template.test();
```

In click event the 'this' is not event self, why?

**Comment by sapjax** [comment]
因为箭头函数里面的`this`指向`test`函数内部的`this`，就是你上面`console.log`打印的那个，你想要拿到dom的话，应该用`event.currentTarget`。

**Comment by bilibiliou** [comment]
this指向的固定化，并不是因为箭头函数内部有绑定this的机制，实际原因是箭头函数根本没有自己的this，导致内部的this就是外层代码块的this。正是因为它没有this，所以也就不能用作构造函数。

书中原话

**Comment by ruanyf** [comment]
确实，sapjax说得很对，this不是event对象。
