### ISSUE TITLE
关于 Disqus 的小问题

### ISSUE THREAD

**Issue by riophae** [ruanyf/es6tutorial#182]
收到 Disqus 的评论回复通知邮件后，从邮件链接点击过来或报 404 错误。

例如，邮件中的链接地址为：

http://es6.ruanyifeng.com/docs/generator#comment-2668237068

实际页面地址为：

http://es6.ruanyifeng.com/#docs/generator

可能需要重新配置下 Disqus?

**Comment by ruanyf** [comment]
上次设置的时候，Disqus 好像不支持通过锚点切换的单页应用。
