### ISSUE TITLE
let 一章中的块级作用域

### ISSUE THREAD

**Issue by kaneruan** [ruanyf/es6tutorial#191]
[块级作用域](https://github.com/ruanyf/es6tutorial/blob/gh-pages/docs/let.md#es6的块级作用域)

``` js
function f1(){
  var n = 5;
  if(true){
   let n =10;
  }
  console.log(n);
}
```

输出是5不是10；我猜if里面形成的暂时死区无法影响外面的变量

``` js
function f1(){
  let n = 5;
  if(true){
   var n =10;
  }
  console.log(n);
}
```

var是函数块的变量，所以会报错
**Uncaught SyntaxError: Identifier 'n' has already been declared**

**Comment by iugo** [comment]
不知道 @githubmann 的问题是什么.
1. var 是函数级别的, let 是语言区块级别的. 例子一可以你把 if 理解为一个函数, let 改为 var 应该就能理解.
2. 同理, var 是函数级别的, 语言区块对它来说没区别, 所以你实际上做了重复的声明.

**Comment by kaneruan** [comment]
@iugo 

> 上面的函数有两个代码块，都声明了变量n，运行后输出5。这表示外层代码块不受内层代码块的影响。如果使用var定义变量n，最后输出的值就是10。

**Comment by iugo** [comment]
@githubmann 

> 例子一可以你把 if 理解为一个函数, let 改为 var

let 和 var 只有作用域的区别, 比如第一段代码可以这样修改以理解 let:

```
function f1(){
  var n = 5;
  // 意为 将 if 语言区块替换为函数区块
  function b() {
    var n =10;
  }
  b()
  console.log(n);
}
```

**Comment by kaneruan** [comment]
我理解错了，谢谢
