### ISSUE TITLE
关于let的问题

### ISSUE THREAD

**Issue by dou4cc** [ruanyf/es6tutorial#20]
按IE11的实现，全局作用域定义的let变量不作为全局对象的属性，但其它JavaScript引擎像Firefox的和Chromium的都把let变量作为全局对象的属性，但因为它们仅支持eval中的let，实在让人存疑它们的实现是否正确，反而IE11的实现看来更靠谱。阮老师您书中可以讲一下这方面在标准中的说法吗？

**Comment by dou4cc** [comment]
有人可以解疑么？

**Comment by hax** [comment]
IE 11 的实现是正确的。
