### ISSUE TITLE
关于 类的prototype属性和__proto__属性 的问题

### ISSUE THREAD

**Issue by scloudyy** [ruanyf/es6tutorial#211]
老师您好，在class这一章的 “类的prototype属性和**proto**属性” 这一小节里，开头说子类的**proto**属性表示构造函数的继承，直接指向父类，而子类的prototype里的**proto**指向父类的prototype，表示方法的继承，但是小结的结尾似乎给出了完全不同的说法，说理解为“作为一个 _对象_ ，子类（B）的原型（**proto**属性）是父类（A）；作为一个 _构造函数_，子类（B）的原型（prototype属性）是父类的实例”，应该是“作为一个 _构造函数_，子类（B）的原型（**proto**属性）是父类（A）；作为一个 _对象_，子类（B）的原型（prototype属性）是父类的实例”吧。
可能是我理解错误，如果是这样的话非常抱歉耽误您的时间

**Comment by ruanyf** [comment]
对象没有`prototype`属性，只有构造函数才有。所以，原来的表达是对的。

不过，由于ES6规定，除了浏览器，其他环境不必部署`__proto__`属性，这一节应该删除。
