### ISSUE TITLE
关于 Es6 Class

### ISSUE THREAD

**Issue by bilibiliou** [ruanyf/es6tutorial#221]
在介绍继承的时候，阮老师有一句话写道

> 子类必须在constructor方法中调用super方法，否则新建实例时会报错。

但是当我结合ReactJs 使用的时候，却可以正常运行

``` javascript
class Switch extends React.Component {
        render () {
            return <div>Hello-World</div>
        }
    }


 ReactDOM.render (
        <Switch />,
        document.querySelector("#demo"),
  ()=> console.log("页面已经渲染完成！！"));
```

**Comment by bilibiliou** [comment]
我并没有在子类的constructor 中调用super ， 甚至都没有写子类的constructor  但是却没有报错
我不知道这是为啥

**Comment by bilibiliou** [comment]
老师说的是新建实例的时候，会报错，而React 中， render 并不是 static的，我的理解是，其内部应该是需要先新建实例，然后在进行渲染的。 没报错感觉挺诧异的

**Comment by ruanyf** [comment]
如果子类没有定义constructor方法，这个方法会被默认添加。原文里有这一段的讲解。
