### ISSUE TITLE
edit 链接出错

### ISSUE THREAD

**Issue by xcatliu** [ruanyf/es6tutorial#230]
如果先点了 anchor，然后再点 edit，则无法正确的跳转到对应的修改页面，比如会跳转到这儿：

https://github.com/ruanyf/es6tutorial/edit/gh-pages/docs/class#概述.md

**Comment by ruanyf** [comment]
谢谢指出，已经改正。

**Comment by xcatliu** [comment]
https://github.com/ruanyf/es6tutorial/commit/4fb1dcbf6276df135e58aad5d4e7c09182bbca5b
