### ISSUE TITLE
数组实例的values()方法 报错

### ISSUE THREAD

**Issue by xuejiangjun** [ruanyf/es6tutorial#236]
```
for (let elem of ['a', 'b'].values()) {
  console.log(elem);
}
```

![qq 20160721160019](https://cloud.githubusercontent.com/assets/16046545/17015637/cfda9558-4f5d-11e6-8b73-14f94ea659a3.png)
为什么会报错

**Comment by xuejiangjun** [comment]
![image](https://cloud.githubusercontent.com/assets/16046545/17016238/c38bbd2e-4f60-11e6-9886-1de3b7655576.png)

![9 iws ra cgh6v6f xnhxe](https://cloud.githubusercontent.com/assets/16046545/17016210/9cf70b6e-4f60-11e6-92b3-28bf3a47df43.png)
在nodejs环境下 不报错 需要转换成ES5

**Comment by erniu** [comment]
为什么会报错？看你的报错信息，浏览器没实现[].values()呗。

你看我的6.2.2这么新的版本中都没实现，就别提浏览器啦。

![image](https://cloud.githubusercontent.com/assets/2314150/17235735/072a7690-5576-11e6-84c8-0bbb3cfa6a0b.png)
