### ISSUE TITLE
docs/generator.md部分

### ISSUE THREAD

**Issue by Kyoloro** [ruanyf/es6tutorial#237]
阮一峰老师：
在Node.js 4.x + 的版本，关于generator函数执行后的对象的throw方法的实现中

```
var gen = function * () {
    try {
        yield console.log("hello");
    } catch (e) {
        // todo handle error
    }
    yield console.log("world");
}

var g = gen();

g.next();  // {value: undefined, done: false} 执行打印 "hello"
g.throw(); // {value: undefined, done: false} 执行打印 "world"
```

所以， 这里 g.throw() 在generator函数体内部产生异常catch到之后，也与g.next()方法一样执行了yield后面的表达式。

因此，下图docs/generator.md的内容，在Node.js 4.x + 的版本实现不一样了
![image](http://7xrsrs.com1.z0.glb.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202016-07-24%20%E4%B8%8A%E5%8D%881.12.40.png)
其中g.throw() 已经执行了console.log("world"), 下一个g.next() 不再执行打印了。

**Comment by ruanyf** [comment]
谢谢提醒了，已经改正了。
