### ISSUE TITLE
您的教程缺失了一些细节

### ISSUE THREAD

**Issue by dou4cc** [ruanyf/es6tutorial#24]
当新的标准振奋着Web程序员时，Worker总被人遗忘。
新的标准哪些能通过MessageChannel哪些不能望讲解，这方面的浏览器的实现很挫，不敢置信

**Comment by XGHeaven** [comment]
@dou4cc 有关MessageChannel的应该不属于es6部分吧。
// 感觉你好厉害，满满的 notification 都是你的 :unamused:
