### ISSUE TITLE
``.trim(), 模板字符串不会trim掉换行

### ISSUE THREAD

**Issue by crenkore** [ruanyf/es6tutorial#243]
我刚好项目中出错了，经测试发现如题问题。
故认为模板字符串一章这个一个点应该要纠正。
您可以测试一下。
`fsdfds     \n     fdsfs`.trim();
## 

刚刚又找了个参考资料：
https://muffinresearch.co.uk/removing-leading-whitespace-in-es6-template-strings/

**Comment by crenkore** [comment]
刚刚又找了个参考资料：
https://muffinresearch.co.uk/removing-leading-whitespace-in-es6-template-strings/

**Comment by hax** [comment]
`trim`的作用是删除头尾的空白字符，不包括中间的。
