### ISSUE TITLE
Generator 函数 10.应用 里关于 异步操作的同步化表达 loadUI的例子存在问题

### ISSUE THREAD

**Issue by Sign312** [ruanyf/es6tutorial#245]
function\* loadUI() {
  showLoadingScreen();
  yield loadUIDataAsynchronously();
  hideLoadingScreen();
}
var loader = loadUI();
// 加载UI
loader.next()

// 卸载UI
loader.next()

当耗时较大时这段代码并不会按顺序地执行先加载数据再卸载loadUI的操作，第二个loader.next()会先于第一个loader.next()执行完成。

**Comment by ruanyf** [comment]
这里只是举一个例子，表示Generator可以执行异步操作，并不是真正可靠的代码。

如何保证异步操作的顺序，请看完《异步操作》那一章。
