### ISSUE TITLE
第八章 函数的拓展 3.扩展运算符的含义有错误

### ISSUE THREAD

**Issue by wynn719** [ruanyf/es6tutorial#251]
![image](https://cloud.githubusercontent.com/assets/9843147/17807521/bf99b042-663d-11e6-945a-51b6db7c06a5.png)

这里应该是 “用空格分割的参数序列” 吧？

**Comment by doggy8088** [comment]
@zhengbowei 你误会这句话的意思了。

这句话的意思是，以下这句程式：
`console.log(...[1, 2, 3])`
会等同于以下程式：
`console.log(1, 2, 3)`
所以才会说**将一个数组转为用逗号分隔的参数序列**。

**Comment by wynn719** [comment]
@doggy8088 原来是这样子！谢谢解惑！
