### ISSUE TITLE
es6里面的模块怎么实现异步加载

### ISSUE THREAD

**Issue by vaseala** [ruanyf/es6tutorial#253]
阮老师，你好：

```
require.async('moduleId', function (exp) {
    /* todo */
});
```

像上述这种需求在ES6中怎么去实现

**Comment by ruanyf** [comment]
Promise里面使用`require`即可。如果不想用`require`，自己读取文件，然后用`eval`执行。

**Comment by vaseala** [comment]
那moduleId对应的模块文件，还是用创建script标签的方式加载？

**Comment by hax** [comment]
@atmjs ES6本身没有定义异步加载的方法，需要等待 loader 规范（ https://github.com/whatwg/loader ）制定完成和浏览器实现。

**Comment by vaseala** [comment]
这样啊 我说怎么一直想不明白ES6异步加载模块的工作原理呢 谢谢两位
