### ISSUE TITLE
Proxy的实例方法中has最后一个示例

### ISSUE THREAD

**Issue by guxinyan** [ruanyf/es6tutorial#265]
has方法拦截的是HasProperty操作，而不是HasOwnProperty操作：这个示例中，
for (let a in oproxy1) {
  console.log(oproxy1[a]);
}
结果是Owen 59，与博客上不一。求解答
for...in循环中has拦截没有生效

**Comment by ruanyf** [comment]
查了规格，`for...in`循环不使用这个拦截，我改一下原文。
