### ISSUE TITLE
Function.prototype.toMethod

### ISSUE THREAD

**Issue by hax** [ruanyf/es6tutorial#27]
最近新增的特性：https://people.mozilla.org/~jorendorff/es6-draft.html#sec-function.prototype.tomethod

**Comment by ruanyf** [comment]
在下面网址看到一个例子，但还是没完全明白toMethod方法的作用，等更多的解释出来。

https://esdiscuss.org/topic/any-tomethod-use-case

**Comment by hax** [comment]
简单讲，toMethod是动态绑定super。

**Comment by ruanyf** [comment]
目前，我的理解是，toMethod()是把一个方法动态绑定到一个对象上，暂时没有想到设计这样一个函数的目的。希望后面会有教程出来。

**Comment by hax** [comment]
后来好像被取消了。。。

**Comment by hax** [comment]
后来好像被取消了。。。
