### ISSUE TITLE
关于文中引用图片的问题

### ISSUE THREAD

**Issue by mumingv** [ruanyf/es6tutorial#271]
阮老师你好，使用这个框架的时候发现个问题，想请教一下。

在docs目录下的.md文件中插入图片的话
`[![cover](images/cover_thumbnail.jpg)](images/cover-2nd.jpg)`
图像没法正常显示。

在README.md文件中插入图片的话就没有问题。

**Comment by mumingv** [comment]
刚通过在docs目录下增加软链接解决了。
[docs]$ ln -s ../images

[![cover](images/cover_thumbnail.jpg)](../images/cover-2nd.jpg)
不过markdown好像不支持使用 ../images/xxx 这种访问父目录的方式？

**Comment by mumingv** [comment]
刚通过在docs目录下增加软链接解决了。
[docs]$ ln -s ../images

[![cover](images/cover_thumbnail.jpg)](../images/cover-2nd.jpg)
不过markdown好像不支持使用 ../images/xxx 这种访问父目录的方式？

**Comment by mumingv** [comment]
刚通过在docs目录下增加软链接解决了。
[docs]$ ln -s ../images

[![cover](images/cover_thumbnail.jpg)](../images/cover-2nd.jpg)
不过markdown好像不支持使用 ../images/xxx 这种访问父目录的方式？

**Comment by mumingv** [comment]
刚通过在docs目录下增加软链接解决了。
`[docs]$ ln -s ../images`

`[![cover](images/cover_thumbnail.jpg)](../images/cover-2nd.jpg)`
不过markdown好像不支持使用 ../images/xxx 这种访问父目录的方式？

**Comment by superwoods** [comment]
@mumingv 

你好，

并非是markdown 不支持使用相对地址现实图片，推测应该是阮老师或您的github pages的docs目录的markdown图片地址路径不正确造成的问题。

markdown是支持相对地址引用图片的。完全没问题，参考我的profile项目，呃 仅仅是举例子。。。绝对不是广告😓

https://github.com/cjmm/profile/blob/gh-pages/README.md

这张图片在img文件夹中，实际地址为：
https://github.com/cjmm/profile/blob/gh-pages/img/superwoods_avatar.png

我们可以这样在md中引用：

``` md
![superwoods_avatar](img/superwoods_avatar.png)
```

如果发布github pages 也是可以正常显示：
https://cjmm.github.io/profile/

所以情况是这样的，和web页面的资源一模一样，看图说话：
![e58b877d-442b-4d09-be5c-45c1a526d660](https://cloud.githubusercontent.com/assets/7624198/19225131/8e0a4fb6-8ec7-11e6-8eab-229b4529f5de.png)

另外，如果实在想外链一个github图片，您也可以把自己的项目Issue 做为图床，但是我不推荐你这样做，因为github确实不是干这个用的。。。像上面的图片直接放入Issue 是这样的代码：

``` md
![e58b877d-442b-4d09-be5c-45c1a526d660](https://cloud.githubusercontent.com/assets/7624198/19225131/8e0a4fb6-8ec7-11e6-8eab-229b4529f5de.png)
```

现在，你可以把图片放到任意位置了。

## 小小的TIPS

个人觉得，阮老师的 ES6 翻译有非常多的人STAR和WATCH，嗯，希望大家尽量用Issues 问关于项目本身的问题比较好些，如果不太相关的提问，很多时候自己google、baidu一下下，想想，实在不明白了email致电什么的都比较好，嗯，也说明咱们比较有礼貌嘛，我说的多啦些，绝不是针对任何人，我自己也会尽力遵守哒！

**Comment by ruanyf** [comment]
这是 marked 的问题， 它自动将`images/cover_thumbnail.jpg`改成了`docs/images/cover_thumbnail.jpg`。
