### ISSUE TITLE
es6入门教程->数组的扩展-6.数组实例的entries()，keys()和values() 例子错误

### ISSUE THREAD

**Issue by 806745845** [ruanyf/es6tutorial#273]
为什么我测试这个例子总报错：
for (let elem of ['a', 'b'].values()) {
  console.log(elem);
}

报错：["a","b"].values is not a function 或者 ["a","b"].values(...)[Symbol.iterator] is not a function

**Comment by facetothefate** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/values
目前浏览器端只有Firefox 和Safari 支持。

用node 测试吧。

关于node 支持的情况请看这里：

http://node.green/

**Comment by ruanyf** [comment]
values() 方法，Chrome 还没支持。
