### ISSUE TITLE
关于Thunk函数章节

### ISSUE THREAD

**Issue by zenjava** [ruanyf/es6tutorial#279]
因为没有说明,Thunk函数的约定，让我有些糊涂。
不明白，Thunk如果不是fs.readFile的场景下如何使用。
后通过网络找到 http://web.jobbole.com/85901/ 这篇文章才明白：
**thunk函数具备以下两个要素：

有且只有一个参数是callback的函数；
callback的第一个参数是error。**

**Comment by ruanyf** [comment]
谢谢提醒。修改的时候，我会改得更清晰一点。
