### ISSUE TITLE
module好像从ECMAScript 6标准中移除了

### ISSUE THREAD

**Issue by dou4cc** [ruanyf/es6tutorial#28]
http://kangax.github.io/compat-table/es6/ 上删去了module这一项。

**Comment by ruanyf** [comment]
奇怪，好像是不在里面。但是ES6 module肯定在标准里啊，http://people.mozilla.org/~jorendorff/es6-draft.html#sec-modules

**Comment by hax** [comment]
只是暂时的。见 https://github.com/kangax/compat-table/issues/316

**Comment by dou4cc** [comment]
是么？module现在也不在里面
