### ISSUE TITLE
解构赋值允许指定默认值 问题

### ISSUE THREAD

**Issue by wangengzheng** [ruanyf/es6tutorial#281]
默认值
解构赋值允许指定默认值。

var [foo = true] = [];
foo // true

[x, y = 'b'] = ['a']; // x='a', y='b'
[x, y = 'b'] = ['a', undefined]; // x='a', y='b'
注意，ES6内部使用严格相等运算符（===），判断一个位置是否有值。所以，如果一个数组成员不严格等于undefined，默认值是不会生效的。

var [x = 1] = [undefined];
x // 1

var [x = 1] = [null];
x // null
上面代码中，如果一个数组成员是null，默认值就不会生效，因为null不严格等于undefined。

## 如果一个数组成员不严格等于undefined，默认值是不会生效的。

可以这样理解 undefined 不严格等于 undefined 所以默认值不会生效？

虽然结果你是对的  但是这个结论有点 拗口

**Comment by ruanyf** [comment]
确实有点拗口，改成“默认值只对 undefined 生效”，确实会好一点。
