### ISSUE TITLE
character set map

### ISSUE THREAD

**Issue by a1mersnow** [ruanyf/es6tutorial#287]
myElement.addEventListener('click', function() {
  let logoData = myWeakmap.get(myElement);
  logoData.timesClicked++;
  myWeakmap.set(myElement, logoData);
}, false);

这里回调的最后一句set是多余的吧

ps: 手机好像没办法在你的文章下留言，只好到这里来留言了…

**Comment by ruanyf** [comment]
谢谢指出，已经改正了。
