### ISSUE TITLE
charactor iterator & for...of循环

### ISSUE THREAD

**Issue by a1mersnow** [ruanyf/es6tutorial#288]
![image](https://cloud.githubusercontent.com/assets/13799160/20645363/2527773a-b497-11e6-98b2-b9f39fcba544.png)

这个地方我觉得有误导之嫌。
for...of 作用的对象或者对象的原型链上必须有Symbol.iterator接口才行。
而上图中第二处代码中，for...of作用的对象却是Symbol.iterator接口执行后的结果，也就是遍历器对象。
于是我就以为for...of不仅可以作用于部署了Symbol.iterator接口的对象，还可以直接作用于遍历器对象。
于是我自己写了一个生成遍历器的函数，将它的执行结果（也就是一个遍历器对象）传给for...of，结果浏览器报错了，显示未部署Symbol.iterator接口。
于是我打印了一下数组的遍历器对象 即 [][Symbol.iterator]()：
![image](https://cloud.githubusercontent.com/assets/13799160/20645368/55419356-b497-11e6-9db2-f12ff0e44b53.png)

原来不是我想的那样。。。

原来第二段代码之所以能工作是因为[][Symbol.iterator]()的原型链上还有一个Symbol.iterator接口

希望阮老师能为我解释清楚，谢谢~

**Comment by ruanyf** [comment]
谢谢指出，已经改过来了。
