### ISSUE TITLE
9.3对象扩展 第3点 "方法的 name 属性"

### ISSUE THREAD

**Issue by tornadocn** [ruanyf/es6tutorial#308]
var person = {
  sayName() {
    console.log(this.name);
  },
  get firstName() {
    return "Nicholas";
  }
};

person.sayName.name   // "sayName"
person.firstName.name // "get firstName"  实际输出undefined

**Comment by ruanyf** [comment]
谢谢指出。已经改正，`name`属性是在属性的描述对象的`get`和`set`属性上面。

```javascript
var o = { get foo(){}, set foo(x){} };
var descriptor = Object.getOwnPropertyDescriptor(o, "foo");
descriptor.get.name // "get foo" 
descriptor.set.name // "set foo"
```

**Comment by tornadocn** [comment]
descriptor.get.name == descriptor.set.name == "foo"
