### ISSUE TITLE
19.Decorator 表述不对

### ISSUE THREAD

**Issue by yangkean** [ruanyf/es6tutorial#311]
http://es6.ruanyifeng.com/#docs/decorator#为什么修饰器不能用于函数？ 这一节

> 上面的代码，意图是执行后counter等于1，但是实际上结果是counter等于0。

```javascript
@add
function foo() {
}

var counter;
var add;

counter = 0;

add = function () {
  counter++;
};
```
对于上面的代码，按照下面这种解析的方法应该直接报错
```javascript
@decorator
class A {}

// 等同于

class A {}
A = decorator(A) || A;
```
实际执行时add是undefined，对undefined进行调用操作会报TypeError，不会执行到 `counter=0` 一行，所以也不会有 `counter等于0` 的结果。

**Comment by ruanyf** [comment]
现在 Decorator 还没有原生支持，我觉得有可能报错，也有可能是`count = 0`，这跟实现有关。

**Comment by yangkean** [comment]
嗯，从原理上说应该要报错，不过确实看实现。
