### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by ghost** [ruanyf/es6tutorial#318]
网上看了你的ECMAScript 6 入门
http://www.nodeclass.com/api/ECMAScript6.html#object
在第41. Object.observe()，Object.unobserve()部分，
- 有一处observe写成了observer。有时间可以改过来。
- 在控制台测试了一下例子程序，并不能运行，到mdn上查了才知道，这个方法已经被废除了。所以有个建议：那些已经废除的方法属性，能不能在书中标明？

**Comment by ipcjs** [comment]
请认准官方链接：http://es6.ruanyifeng.com/
你说的Object.observe()相关的内容，老早就删掉了。

**Comment by ruanyf** [comment]
这里是官方仓库，最新版本以这里为准。https://github.com/ruanyf/es6tutorial
