### ISSUE TITLE
关于Module的问题

### ISSUE THREAD

**Issue by suprekaka** [ruanyf/es6tutorial#321]
阮老师您好, @ruanyf 

在Module章节中, 有如下两段描述:

- 图1
![image1](https://cloud.githubusercontent.com/assets/7970776/21955463/8d7cabae-daa6-11e6-9d18-eb7329503815.png)
- 图2
![image2](https://cloud.githubusercontent.com/assets/7970776/21955469/a2ecbf24-daa6-11e6-94d1-007c475c5c6e.png)

不太能理解 `import`语句时会不会执行被导入的模块. 图一中原文说"遇到模块加载命令`import`时, 不会去执行模块", 图二中的示例代码, 又表明在`a.js`中`import`了`b.js`, 导致`b.js`先执行.

请指教, 谢谢

**Comment by ruanyf** [comment]
我没有表达清楚。脚本执行有两个阶段，脚本加载（静态分析）和实际执行。`import`在脚本加载阶段就生效，但是不执行。

我改一下原文。
