### ISSUE TITLE
ES6标准入门有一个案例错误

### ISSUE THREAD

**Issue by chinaliyun** [ruanyf/es6tutorial#329]
第2章 let与const变量  

章节中的案例
```js
function f(){console.log('outside')}
	(function(){
		if(false){
			function f(){
				console.log('inside')
			}
		}
		f();
	}())
```
ES5下我在chrome  firefox IE等浏览器下，都执行的时报错或者undefined  而不是 inside， 这里是不是写错了

**Comment by hax** [comment]
现在浏览器已经都按照ES6（的webcompat行为）来执行了，你要测ES5的行为得用老浏览器。

不过原文里后面的ES6的例子应该写明是否是strict模式，以及是否是webcompat行为。否则读者可能误解。

**Comment by ruanyf** [comment]
最好在 IE6 ～ IE8 或者 Node 0.10 下试一下，现在 ES5 环境都不容易找了。

另外，这一章更新过了，文字更容易懂了，你可以再看看。

**Comment by chinaliyun** [comment]
@ruanyf  好的 谢谢
