### ISSUE TITLE
这个例子 foo() 输出的是2

### ISSUE THREAD

**Issue by ianhwu** [ruanyf/es6tutorial#332]
var x = 1;
function foo(x, y = function() { x = 2; }) {
  var x = 3;
  y();
  console.log(x);
}

foo() // 3
x // 1

只要 var x = 3; 在 y()上面执行, console.log(x); 就永远是2.

上面的foo函数相当于
foo(x) {
    var x = 3;
    {
      x = 2;
    }
    console.log(x);
  }
可以清晰看出 无论 输入 x 是什么, 最后 x 都会等于2.

**Comment by ruanyf** [comment]
运行结果是3。

**Comment by ianhwu** [comment]
为什么我这里一直输出是2, 能解释一下为什么是3吗?

**Comment by ruanyf** [comment]
Chrome 56 控制台输入下面的代码。

```javascript
var x = 1;
function foo(x, y = function() { x = 2; }) {
  var x = 3;
  y();
  console.log(x);
}

foo() // 3 
```

**Comment by ianhwu** [comment]
我试了一下 Chrome 里面输出的确实是3,  我是在 react native 中调试, 通过 Chrome 控制台输出的一直是2, 谢谢了, 我再看看
