### ISSUE TITLE
Promise.prototype.done 返回链式化调用？

### ISSUE THREAD

**Issue by AminHuang** [ruanyf/es6tutorial#333]
Promise.prototype.done = function (onFulfilled, onRejected) {
  this.then(onFulfilled, onRejected)
    .catch(function (reason) {
      // 抛出一个全局错误
      setTimeout(() => { throw reason }, 0);
    });
};

调用链式化：

Promise.prototype.done = function (onFulfilled, onRejected) {
  return this.then(onFulfilled, onRejected)
    .catch(function (reason) {
      // 抛出一个全局错误
      setTimeout(() => { throw reason }, 0);
    });
};

我的场景是在做ajax操作的时候可能需要手动中断请求，我多增加了一个 abort 函数

Promise.prototype.abort = function() {...}

a = getJSON(...).done()

a.abort()

按原来那种返回，我就没办法进行abort操作了

**Comment by ruanyf** [comment]
`done`方法明确是用在最后一个位置，后面不适合再接其他方法了。比如，你的`abort`方法后面接不接`then`或`catch`呢？

如果确实需要取消 Promise，建议不要使用`done`了。
