### ISSUE TITLE
关于普通对象使用for..of的问题。

### ISSUE THREAD

**Issue by tensozangeci** [ruanyf/es6tutorial#334]
在峰哥的for...of循环的内容中讲到普通对象使用for..of结构的方法提到可以将数组的Symbol.iterator属性赋值给对象的Symbol.iterator属性；我尝试了一下在谷歌和火狐上，然而并不行,后来尝试在对象上加上length属性就可以了。也就是让对象的属性结构跟数组一致方可使用for...of遍历。

**Comment by ruanyf** [comment]
谢谢指出。

我试了一下，果然要设了`length`属性才能遍历，但是遍历的时候取不到值。

考虑到这些内容用处不大，我一会会把它们删了。
