### ISSUE TITLE
yield 的两个疑问。

### ISSUE THREAD

**Issue by tensozangeci** [ruanyf/es6tutorial#335]
chrome版本57 console.log('hello'+(yield 123))直接运行不了；试了火狐版本51以及edge均无法运行；须放在 Generator函数内；我觉得yield 既然不能在普通函数用使用那么在console中理应也是无法使用的；
另一个疑问是关于yield作为函数参数的用法不是很懂峰哥的意思。试了几种方式均不行；能否请峰哥给个demo

**Comment by ruanyf** [comment]
```javascript
const f = function* () {
    console.log('hello'+(yield 123));
}

const gen = f();
gen.next();
gen.next(); 
```

**Comment by tensozangeci** [comment]
？？？这是回答console不能直接运行yield的疑问吗？
那关于yield作为函数参数的疑问是怎样一个形式呢？峰哥在文章中举了这么个例子
/*
foo(yield 'a', yield 'b'); // OK
*/
我尝试了foo为普通函数和Generator函数均报错

**Comment by ruanyf** [comment]
yield 必须放在 Generator 函数里面。

**Comment by hax** [comment]
@ruanyf 看了原文，建议把“yield语句“改为”yield表达式“，这样就比较容易理解了。

**Comment by ruanyf** [comment]
OK.
