### ISSUE TITLE
extends Array webpack编译不了

### ISSUE THREAD

**Issue by 0810731113** [ruanyf/es6tutorial#336]
webpack和browserify 编译报错提示 commit() 不是一个函数

**Comment by ruanyf** [comment]
到 Babel 测试，可以运行的。https://babeljs.io/repl/

**Comment by 0810731113** [comment]
# Uncaught TypeError: x.commit is not a function(…)  在浏览器里运行报错

**Comment by 0810731113** [comment]
在服务端cmd命令行里运行可以，在服务器端运行报错，蛋刀编译后浏览器支持并不完全，而且我是在google浏览器里运行的

**Comment by 0810731113** [comment]
在服务端cmd命令行里运行可以，在客户端浏览器端运行报错，编译后浏览器支持并不完全，而且我是在google浏览器里运行的

**Comment by hax** [comment]
（不支持extends内建类型）这是babel的bug。
