### ISSUE TITLE
[16]Generator 函数的语法 之 yield语句部分 控制台报错

### ISSUE THREAD

**Issue by zxhycxq** [ruanyf/es6tutorial#340]
地址： http://es6.ruanyifeng.com/#docs/generator 

你好，我在最新版的chrome浏览器中输入之后，会显示错误。其他浏览器也是如此。

> ![image](https://cloud.githubusercontent.com/assets/11674203/23339652/1d4626a2-fc62-11e6-894c-94dac617a0c2.png)

![image](https://cloud.githubusercontent.com/assets/11674203/23339698/b17b3fec-fc62-11e6-8d99-c1e1c0b71146.png)

是不能这样输入还是？我看了其他的书籍，不过他们没有讲这么细。

**Comment by ruanyf** [comment]
我这里没写清楚，`yield`只能用在 Generator 函数里面。
