### ISSUE TITLE
关于es6块级作用域函数声明问题求教前辈

### ISSUE THREAD

**Issue by HongChutang** [ruanyf/es6tutorial#343]
阮前辈您好！最近在学习您的es6入门一书，在“块级作用域函数声明”这一小节里有个问题很不解，望您指教！
问题：
您说到：
 为了解决兼容老版问题，浏览器的对于块级作用域中的函数声明有自己的行为方式：
 1、允许在块级作用域内声明函数
 2、函数声明类似于var 机会提升到全局作用域或函数的头部
 3、函数声明还会提升到所在块级作用域的头部
然后我按照我的理解改了下书中给的例子：

f();
function f() { console.log('I am global scope!'); }
(function () {
  if (true) {
    f();
    function f() { console.log('I am brock scope!'); }
  } 
    f(); 
    function f() { console.log('I am function scope!'); }  
}());	

我理解是这样的：全局的声明、块级作用域中的声明和函数作用域中的声明都会提前，所以预想输出应该是：global brock function
但是却输出 global brock brock
我又改了下代码：

f();
function f() { console.log('I am global scope!'); }
(function () {
  f(); 
  function f() { console.log('I am function scope!'); }  
  if (true) {
    f();
    function f() { console.log('I am brock scope!'); }
  } 
}());	
这下就如我预想的那样 输出 global function brock 了

我的理解应该出了问题，但是想了很久想不通，希望您有空能给我指点下，谢谢！
我的运行环境是浏览器控制台和nodejs 6+ 都是90%支持es6的
您的书写的真的很好，崇拜点赞！

**Comment by ruanyf** [comment]
实际执行的是下面的代码。

```javascript
f();
function f() { console.log('I am global scope!'); }

(function () {
  var f;
  f = function () { console.log('I am function scope!');} ;
  if (true) {
    f = function f() { console.log('I am brock scope!'); };
    f();
  }
  f();
}());
```
