### ISSUE TITLE
变量的解构勘误

### ISSUE THREAD

**Issue by CaptainYYH** [ruanyf/es6tutorial#344]
let obj = {
  p: [
    'Hello',
    { y: 'World' }
  ]
};

let { p: [x, { y }] } = obj;
x // "Hello"
y // "World"

报错了！
Type 'string | { y: string; }' has no property 'y' and no string index signature.

**Comment by CaptainYYH** [comment]
麻烦阮老师看一下

**Comment by unlangchan** [comment]
没有说过对象可以解构吧(lll￢ω￢)  必须含有遍历器才行

**Comment by flyyang** [comment]
@CaptainYYH  我这边没问题。你环境对么。

**Comment by ruanyf** [comment]
Chrome 56 可以执行，你是什么环境？
