### ISSUE TITLE
new (Date.bind.apply(Date, [null, 2015, 1, 1]))

### ISSUE THREAD

**Issue by zss007** [ruanyf/es6tutorial#346]
讲函数的扩展时候，看到一个es5的语法，不太理解。apply、bind语法我都了解，会用，但是可以连起来用吗？查了下资料也都没怎么看懂，请帮忙解答下，谢谢！
new (Date.bind.apply(Date, [null, 2015, 1, 1]))

**Comment by ruanyf** [comment]
`bind`用于绑定参数，`apply`是`bind`内部的`this`绑定`Date`。
