### ISSUE TITLE
推荐将fetch编入章节，毕竟是最新的ES标准，实用同时也是未来的发展方向

### ISSUE THREAD

**Issue by cers000** [ruanyf/es6tutorial#347]
有标准
https://fetch.spec.whatwg.org/
有polyfill
https://github.com/github/fetch
还有铺天盖地的的各种宣传，难道不值得一提吗？

**Comment by flyyang** [comment]
fetch属于WebAPI。

这里讲的是ES,没毛病。

**Comment by cers000** [comment]
哦，也是哦
