### ISSUE TITLE
勘误：Promise第二小节关于Promise状态变动时间

### ISSUE THREAD

**Issue by sunkuo** [ruanyf/es6tutorial#349]
阮老师好，Promise章节第二小节最后一段，如图所示
<img width="606" alt="screen shot 2017-03-15 at 10 00 51 pm" src="https://cloud.githubusercontent.com/assets/5069192/23952021/0327b1e8-09cb-11e7-83bf-2c5a842e62c1.png">
根据 [promise-spec](https://github.com/promises-aplus/promises-spec#the-promise-resolution-procedure) 指示，如果一个Promise resolve了另一个Promise， 并且第二个Promise处于pending状态，那么**第一个Promise的状态维持Pending直到第二个Promise resolve或者reject**。
所以原文中p2的状态应该也是第三秒才改变，原文中是第一秒改变。

> 上面代码中，p1是一个Promise，3秒之后变为rejected。p2的状态在1秒之后改变。

**Comment by ruanyf** [comment]
这里确实表达得不清楚。我改一下，P2其实 发生了两次状态变化。第一次在1秒后，第二次是又过了两秒。第一次变化以后，发现返回的是一个 Promise，于是本次变化无效。
