### ISSUE TITLE
关于super关键字以及静态方法的问题

### ISSUE THREAD

**Issue by silhouettesia** [ruanyf/es6tutorial#354]
在super关键字中说到：
>super这个关键字，既可以当作函数使用，也可以当作对象使用。在这两种情况下，它的用法完全不同。
>- 第一种情况，super作为函数调用时，代表父类的构造函数。作为函数时，super()只能用在子类的构造函数之中，用在其他地方就会报错。
>- 第二种情况，super作为对象时，指向父类的原型对象。

关于静态方法有如下描述：
> 如果在一个方法前，加上static关键字，就表示该方法不会被实例继承，而是直接通过类来调用。如果在实例上调用静态方法，会抛出一个错误，表示不存在该方法。
>父类的静态方法，可以被子类继承。静态方法也是可以从super对象上调用的。

```
class Foo {
  static classMethod() {
    return 'hello';
  }
}

class Bar extends Foo {
  static classMethod() {
    return super.classMethod() + ', too';
  }
}

Bar.classMethod();
```
根据以上描述，在Bar的classMethod中使用`super`是作为对象使用，那么此时`super`指向Foo的原型对象。但是Foo的静态方法只能通过Foo直接调用，Foo的原型对象上并没有该静态方法，请问此处是否有矛盾？

**Comment by XGHeaven** [comment]
根据babel的转码来看，super应该指的是父类本身这个对象，并不是父类的原型对象

**Comment by ruanyf** [comment]
我没写清楚，在普通方法之中 super 指向父类的原型对象，在静态方法之中指向父类本身，参见 http://stackoverflow.com/questions/29439656/inherit-static-methods-in-es6 。

原文也已经改正。
