### ISSUE TITLE
建议在加上当前浏览器的实现情况

### ISSUE THREAD

**Issue by yiye** [ruanyf/es6tutorial#36]
可以用 [caniuse.com](http://caniuse.com/#search=promise)。有些好的标准，在一些业务中已经可以使用了

**Comment by hirokith** [comment]
同建议，可以在对应子项上挂一个对应的 es6 compat-table 的对应链接，例如讲到 `let`，放一个链接：https://kangax.github.io/compat-table/es6/#let 直接看该语法当前的支持程度。
