### ISSUE TITLE
FileReader没有close readLine方法吧？

### ISSUE THREAD

**Issue by baggiomygod** [ruanyf/es6tutorial#363]
Generator那章,第10节
function* numbers() {
  let file = new FileReader("numbers.txt");
  try {
    while(!file.eof) {
      yield parseInt(file.readLine(), 10);
    }
  } finally {
    file.close();// 运行报 close is not a function  查看API好像FileReader没有close readLine方法吧？
  }
}

**Comment by ruanyf** [comment]
这其实是一段伪代码，表示一个虚拟的 FileReader 库。

**Comment by ruanyf** [comment]
有空的时候，我看看能不能找一个现成的实现。
