### ISSUE TITLE
第17章 Generator函数的异步调用 中的字词错误

### ISSUE THREAD

**Issue by noe132** [ruanyf/es6tutorial#365]
在17章 的 「Generator 函数的异步应用」 小节中的第二段
http://es6.ruanyifeng.com/#docs/generator-async

 > 使用Promise.race()函数，可以判断这三个事件之中哪一个最先发生，只有当`data`时间最先发生时，

中

只有当data时间 应为 只有当data事件

**Comment by ruanyf** [comment]
谢谢指出，我已经改正了。
