### ISSUE TITLE
let和const这张在暂时性死区这里有错误

### ISSUE THREAD

**Issue by sunling123** [ruanyf/es6tutorial#366]
var tmp = 123;

if (true) {
  tmp = 'abc'; // 这里不会报错
  let tmp;
}

if里面的tmp赋值不会报错

**Comment by zxhycxq** [comment]
@sunling123  你确定你试验过了。

**Comment by sunling123** [comment]
@zxhycxq 我确定我试验过了，但是我忘了使用了babel了。sorry~
