### ISSUE TITLE
Promise中resolve方法的解释有误

### ISSUE THREAD

**Issue by sage417** [ruanyf/es6tutorial#369]
resolve不能简单的解释为“完成”
其实后面也说明了, resolve方法可以接受primise类型的参数，而这个primise既可以是fulfill的也可以是rejected状态的，所以还是解释为“决议”，表示这个primise状态已经被决议，不能再次变更。

**Comment by ruanyf** [comment]
是的，`resolve`确实表示决议或解决了。

“完成”其实是 fulfill 的翻译，而且我觉得说“Promise 完成了”比“Promise 解决了”，在中文里面更顺口一些。
