### ISSUE TITLE
1、let和const命令 -> 块级作用域与函数声明问题

### ISSUE THREAD

**Issue by shangTou** [ruanyf/es6tutorial#371]
在 1、let和const命令 -> 块级作用域与函数声明 内容中

原文内容：

代码：
function f() { console.log('I am outside!'); }

(function () {
  if (false) {
    // 重复声明一次函数f
    function f() { console.log('I am inside!'); }
  }

  f();
}());

上面代码在 ES5 中运行，会得到“I am inside!”，因为在if内声明的函数f会被提升到函数头部，实际运行的代码如下。

----------------------------------------------------------------------

原文中的  在 ES5 中运行，会得到“I am inside!”  是怎么搞来的呢？ : -)，谢谢

亲测：
（1）把上面代码贴到es6的文件然后运行，结果是报错
（2）把上面代码贴到es6文件中转换成es5后，运行es5文件，结果是输出"I am outside!"
（3）把上面代码直接贴到es5文件中运行，结果是报错，f is not a function

**Comment by xhlwill** [comment]
应该在`ES5运行环境`中测，而不是转成ES5文件……比如 IE

**Comment by ruanyf** [comment]
你通过 nvm 安装 node v0.12.7，然后切换到那个版本，执行这段代码。
