### ISSUE TITLE
yield应该是expression而不是statement

### ISSUE THREAD

**Issue by acrazing** [ruanyf/es6tutorial#374]
在[generator.md](https://github.com/ruanyf/es6tutorial/blob/gh-pages/docs/generator.md#yield语句)一文中, `yield`被指为`yield语句`. 但是在ecma规范中, `yield`是一个表达式(expression).

这会造成一定的误解, 望修正.

参考: <http://www.ecma-international.org/ecma-262/7.0/#prod-YieldExpression>

**Comment by ruanyf** [comment]
谢谢提醒，下次编辑的时候会改掉。

以我个人的看法，`yield`叫做表达式其实是很勉强的，因为它没有返回值。

**Comment by acrazing** [comment]
这种说法不一定正确, 首先`YieldExpression`是有返回值的, 参考: <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/yield>, 其次表达式与语句的区别挺大, 参考 <http://2ality.com/2012/09/expressions-vs-statements.html>.
