### ISSUE TITLE
纠错

### ISSUE THREAD

**Issue by HarryPoint** [ruanyf/es6tutorial#378]
let o1 = { a: 1 };
let o2 = { b: 2 };
o2.__proto__ = o1;
let o3 = { ...o2 };
o3 // { b: 2 }
上面代码中，对象o3是o2的拷贝，但是只复制了o2自身的属性，没有复制它的原型对象o1的属性。

是否应该改为
let {...o3} = o2};

**Comment by ruanyf** [comment]
谢谢指出，这个例子在解构赋值部分，确实应该写成你说的那样。

我已经改过来了。

**Comment by HarryPoint** [comment]
回复真快！表示还在看这块儿，谢谢大神分享！
当前部分
var o = Object.create({ x: 1, y: 2 });
o.z = 3;

let { x, ...{ y, z } } = o;
x // 1
y // undefined
z // 3
上面代码中，变量x是单纯的解构赋值，所以可以读取继承的属性；解构赋值产生的变量y和z，只能读取对象自身的属性，所以只有变量z可以赋值成功。
---------------------------------------
此处的描述是否应该指出是(...n)这种形式的解构赋值才只能读取对象自身的属性，感觉都描述为解构赋值有点凌乱。例如：
let o1 = { a: 1 };
      let o = { x: 1, y: 2 };
      o.__proto__ = o1;
      o.z = 3;

      let { x, y,z,a } = o;
      console.log(x) // 1
      console.log(y) // 2
      console.log(z) // 3
      console.log(a) // 1
