### ISSUE TITLE
/generator#next方法的参数 (表述问题)

### ISSUE THREAD

**Issue by Akiq2016** [ruanyf/es6tutorial#386]
阮老师好

> 上面代码先定义了一个可以无限运行的 Generator 函数f，如果next方法没有参数，每次运行到yield语句，变量reset的值总是undefined。当next方法带一个参数true时，变量reset就被重置为这个参数（即true），因此i会等于-1，下一轮循环就会从-1开始递增。

个人感觉这里表述不准确：
`如果next方法没有参数，【每次运行到yield语句】，变量reset的值总是undefined`。
或许改为这样比较正确？
`如果next方法没有参数，【从暂停状态到恢复运行时】，变量reset的值总是undefined`

**Comment by ruanyf** [comment]
原来的表述比较直接吧。

这里讨论的是 yield 表达式的返回值，我觉得把 yield 将出来会比较好理解。

**Comment by Akiq2016** [comment]
well, 

如果本次next没有带参数，那么当把yield 其后面的运算结果抛出来后，抛回给变量的值 是undefined。
而下一次next带上参数时，则会改变上一yield语句返回给变量的值，这个时候变量的值 才被改写。

所以我个人认为 并不是【每次运行到yield语句】这个节点 变量reset的值才改变。而是再一次next(带参数)的时候，参数值 才被塞进上一行yield的返回值里。不知道我的理解是否有误。

**Comment by ruanyf** [comment]
你的理解没问题，但是怎么表达清楚，`next`的参数就是上一次暂停处的 yield 表达式的值。

我还是觉得，原来的表达比修改后的表达清楚一点。因为可以把 yield 看作是同步语法，这样比说清楚上一次和下一次要简单一点。
