### ISSUE TITLE
表述有误

### ISSUE THREAD

**Issue by HarryPoint** [ruanyf/es6tutorial#387]
而且，数组的map和filter方法也可以用于 Set 了。

let set = new Set([1, 2, 3]);
set = new Set([...set].map(x => x * 2));
// 返回Set结构：{2, 4, 6}

let set = new Set([1, 2, 3, 4, 5]);
set = new Set([...set].filter(x => (x % 2) == 0));
// 返回Set结构：{2, 4}

---------------------------------------------------------
此处数组的map和filter方法并没有用于Set

**Comment by ruanyf** [comment]
是的，Set 结构本身没办法使用`map`和`filter`。

这里为了表达方便，偷懒了。
