### ISSUE TITLE
“generator函数应用——异步操作的同步化表达” 的第一个demo有问题

### ISSUE THREAD

**Issue by LuckyDottie** [ruanyf/es6tutorial#393]
异步操作的同步化表达的这个demo并不能保证等到异步加载数据完成后才执行下一个loader.next()。
![demo](https://cloud.githubusercontent.com/assets/11747305/25517184/c9a66a4a-2c20-11e7-923f-04e5f4bfada6.png)

**Comment by ruanyf** [comment]
这里是伪代码。一般来说，`loadUiDataAsync`通过回调函数或 Promise 对象，保证操作结束后调用`loader.next`方法。
