### ISSUE TITLE
为什么我在Chrome中使用import报 识别不了该标识

### ISSUE THREAD

**Issue by shaoqiming** [ruanyf/es6tutorial#395]
```javascript
///profile.js
var firstName = 'Michael';
var lastName = 'Jackson';
var year = 1958;

export {firstName, lastName, year};
```

```javascript
///main.js
import {firstName, lastName, year} from './profile.js';

function setName() {
  console.log(firstName + ' ' + lastName);
}

setName();
```
index.html
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>shaoqitest</title>
    </head>
    <body>
        <div id='example'></div>
        <script src="./profile.js"></script>
        <script src="./main.js"></script>
    </body>
</html>
```
文件目录
![image](https://cloud.githubusercontent.com/assets/12133970/25650002/727cd174-300c-11e7-8828-8a54c2c82529.png)

错误信息
![image](https://cloud.githubusercontent.com/assets/12133970/25650010/8470c82c-300c-11e7-8608-e7220ec317ff.png)

main.js引用profile.js 在chrome中便报识别不了关键字，网上查了一下，估计是太基础了，也没上面靠谱的答案。其它的多是大型应用，用的可能是node.js和require.js。我就是个刚开始学的菜鸟,希望阮老师能指导一下，是不是一定要使用上面两种进行加载才能使用import和export。如果直接写个最简单的列子的话，应该是怎么写的呢？ 还有个小小的建议 最好是有些关于es6的小demo，效果看es6的效果可能会好点。

**Comment by shaoqiming** [comment]
$ babel-node 难道是要通过这个转码 将ES6的代码转换成ES5？ 直接写import 和export Chrome不支持吗？

**Comment by eeve** [comment]
@shaoqiming 

chrome还不支持import语法

http://kangax.github.io/compat-table/es6/

建议上babel

**Comment by ruanyf** [comment]
Chrome 还不支持 export 和 import 。
