### ISSUE TITLE
p12'有的死区比较隐蔽, 不易发现...'这段当中举的例子与let似乎并无关系

### ISSUE THREAD

**Issue by tinycold** [ruanyf/es6tutorial#396]
源代码

```
function foo(x = y, y = 2) {
    return [x, y]
}

foo();
```

这样一个代码, 在es5中也是报错not defined. 说明y原本就没有被提升.  所以我认为这个例子说来至少算是不够突出, 要是还有第三版希望阮老师能换一个更好的例子.

**Comment by ruanyf** [comment]
ES5 报错不是这个原因，而是因为不支持函数参数的默认值。
