### ISSUE TITLE
表述好像有问题

### ISSUE THREAD

**Issue by onlycxue** [ruanyf/es6tutorial#397]
阮老师好，在介绍Promise.reject() 方法时。

注意，Promise.reject()方法的参数，会原封不动地作为reject的理由，变成后续方法的参数。这一点与Promise.resolve方法不一致。

其中 “会原封不动地作为reject的理由”  是不是表述有问题

**Comment by ruanyf** [comment]
哪里有问题？

**Comment by onlycxue** [comment]
“原封不动地作为reject的理由” 中的reject 是不是可以理解为
```
new Promise(function(resolve,reject){
})
```
代码中的参数reject ？
不太明白 Promise.reject()的方法参数怎么会作为reject 。

刚接触ES6，希望阮老师指点一下。。

**Comment by ruanyf** [comment]
书里的例子很明白了。

```javascript
const thenable = {
  then(resolve, reject) {
    reject('出错了');
  }
};

Promise.reject(thenable)
.catch(e => {
  console.log(e === thenable)
})
// true
```

`thenable`会原封不动地成为`catch`方法的参数。
