### ISSUE TITLE
set-map里边的map实例的属性与方法小节

### ISSUE THREAD

**Issue by chenshiforever** [ruanyf/es6tutorial#403]
set-map里边的map实例的属性与方法小节的里边的（5）里边的最后一行代码，根据上下文来看，看起来应该是m.delete(undefined)  ，而不是m.has(undefined)

**Comment by kakanjau** [comment]
m.delete(undefined)
m.has(undefined) 
是这两句吗
我猜这里`m.has(undefined)`的目的是告诉你，上面`m.delete(undefined)`的执行结果的。
从上下文看，没有问题

**Comment by chenshiforever** [comment]
@kakanjau 那么他这里就缺少一句啊，这里得目的是为了验证m.delete(undefined) ，这个会返回false，然而代码上并不能看出来它会返回false

**Comment by ruanyf** [comment]
我的原意是，原来的键是`undefined`，删除以后，这个键就没了。

```javascript
// 新建一个 Map 实例
const m = new Map();

// 设置一个键值对
m.set(undefined, 'nah');

// 是否存在 undefined 键
m.has(undefined)     // true

// 删除 undefined 键
m.delete(undefined)

// 是否存在 undefined 键
m.has(undefined)       // false
```
