### ISSUE TITLE
阮老师好 书中有一个疑问

### ISSUE THREAD

**Issue by 450611** [ruanyf/es6tutorial#405]
http://es6.ruanyifeng.com/#docs/promise
`var p1 = new Promise(function (resolve, reject) {
  setTimeout(() => reject(new Error('fail')), 3000)
})

var p2 = new Promise(function (resolve, reject) {
  setTimeout(() => resolve(p1), 1000)
})

p2
  .then(result => console.log(result))
  .catch(error => console.log(error))`

这段代码中的 p2函数中的Promise  resolve(p1); 这样p1只是一个函数吧， 并没有执行 ，
难道不应该是 resolve(p1()) 么？

**Comment by chenshiforever** [comment]
我也曾在这里疑惑过很久~
我的理解是 p1是一个promise的对象，不是函数，当你在new Promise的时候，p1这个对象处于pending的状态，他正在等待变为resolved状态或者rejected状态;剩下的老师都写的很明白了

**Comment by 450611** [comment]
这个没啥问题， 是我之前自己手打的例子跟老师的不一样， 是我疏忽了

**Comment by ruanyf** [comment]
`p1`是 Promise 对象。`resolve(p1)`没有问题。
