### ISSUE TITLE
第十四章Promise中，node 7.7.3 对于无catch的错误，可以正确给出错误提示

### ISSUE THREAD

**Issue by wind-direction** [ruanyf/es6tutorial#411]
![image](https://cloud.githubusercontent.com/assets/10607815/26384371/60f5301c-406b-11e7-9870-9d52ee5db794.png)
我在进行学习的过程中，发现阮老师有一个不太一样的地方，这是我的代码：
![image](https://cloud.githubusercontent.com/assets/10607815/26384471/0f8477dc-406c-11e7-8ad3-595d1949f369.png)
这是执行过后的提示：
![image](https://cloud.githubusercontent.com/assets/10607815/26384415/a5c4c900-406b-11e7-868a-7377a6c0da34.png)

**Comment by ruanyf** [comment]
我为了你的测试用例加上`done()`，试了一下确实能通过。

看来这里只是打印错误，没有真的抛出错误。我要修改一下原文，谢谢指出。

**Comment by wind-direction** [comment]
谢谢阮老师。我没注意过`done`在异步操作的影响。。学了一招。。。
