### ISSUE TITLE
手机打开http://es6.ruanyifeng.com/非常慢

### ISSUE THREAD

**Issue by Eastegg** [ruanyf/es6tutorial#417]
阮老师你好，手机访问http://es6.ruanyifeng.com/巨慢，好几分钟打不开。
似乎http://es6.ruanyifeng.com/网页里面有资源需要翻墙才能用，开了vpn以后打开就快了。
请查看是否是因为http://es6.disqus.com/embed.js这类资源被墙了

**Comment by ruanyf** [comment]
Disqus 是动态插入的，按理说不会影响到主页面的渲染啊。

我手机打开速度还可以。如果你的网路一直如此，建议直接看 Github 上面的源码。https://github.com/ruanyf/es6tutorial/blob/gh-pages/docs/let.md

**Comment by limchen233** [comment]
阮老师，我用了shadowsocksR代理，用的PAC模式，阮老师的博客打不开，是怎么回事？
