### ISSUE TITLE
stream 模式是指什么？

### ISSUE THREAD

**Issue by lexdene** [ruanyf/es6tutorial#419]
在《Promise 对象》这一节，有一句话。

> 如果某些事件不断地反复发生，一般来说，使用 stream 模式是比部署Promise更好的选择。

这个`stream 模式`不太理解。搜了好多资料感觉都和`某些事件不断地反复发生`没什么关系。

因此求问:

1. stream 模式是什么？
2. 如何把一个不断地反复发生的事件改写成 stream 模式的代码？

**Comment by laplaceliu** [comment]
同问，不知道是不是java8里的Stream API。查到了一个stream.js，但是官网已经打不开了，这个库是仿的java8 stream api

**Comment by ruanyf** [comment]
这里指的是 Node 的 stream API。https://nodejs.org/api/stream.html
