### ISSUE TITLE
Object.getOwnPropertyDescriptors并不能实现c mixin a,b

### ISSUE THREAD

**Issue by front2psy** [ruanyf/es6tutorial#420]
Object.getOwnPropertyDescriptors也可以用来实现 Mixin（混入）模式。

let mix = (object) => ({
  with: (...mixins) => mixins.reduce(
    (c, mixin) => Object.create(
      c, Object.getOwnPropertyDescriptors(mixin)
    ), object)
});

// multiple mixins example
let a = {a: 'a'};
let b = {b: 'b'};
let c = {c: 'c'};
let d = mix(c).with(a, b);
上面代码中，对象a和b被混入了对象c。

对象扩展中，第11部分-Object.getOwnPropertyDescriptors() 
我将代码复制下来后，并不能实现描述的那种混入。不知道是我操作错误还是什么原因，望大家指点！

**Comment by ruanyf** [comment]
可以实现的。原文的用词不准确，实际是在`d`上面实现。

```javascript
d.c // "c"
d.b // "b"
d.a // "a"
```
