### ISSUE TITLE
7 块级作用域 代码有误

### ISSUE THREAD

**Issue by JingLi-kooboo** [ruanyf/es6tutorial#423]
![image](https://user-images.githubusercontent.com/20513064/26923450-b65a3326-4c74-11e7-9fc3-47ebb5132d68.png)
此处应为true吧

**Comment by ruanyf** [comment]
这里故意写成 false 的，表示这一块代码不会执行，但是在 ES5 还是会生效。

**Comment by JingLi-kooboo** [comment]
立即执行函数(function(){})会先于function f()执行,此时执行f()出错

**Comment by ruanyf** [comment]
> "ES6 就完全不一样了，理论上会得到“I am outside!”。因为块级作用域内声明的函数类似于let，对作用域之外没有影响。但是，如果你真的在 ES6 浏览器中运行一下上面的代码，是会报错的，这是为什么呢？"

> "原来，如果改变了块级作用域内声明的函数的处理规则，显然会对老代码产生很大影响。为了减轻因此产生的不兼容问题，ES6在附录B里面规定，浏览器的实现可以不遵守上面的规定，有自己的行为方式。" 

……

**Comment by JingLi-kooboo** [comment]
大概理解了,又试firefix和chrome,现在对在if中声明的函数的处理是 提前声明变量f,但不会提前赋值
![image](https://user-images.githubusercontent.com/20513064/26962483-019b19c8-4d19-11e7-80ca-5a11fdd957af.png)
