### ISSUE TITLE
“Class 的静态属性和实例属性” 引用的提案变更

### ISSUE THREAD

**Issue by PaperStrike** [ruanyf/es6tutorial#424]
[Class 的静态属性和实例属性](http://es6.ruanyifeng.com/#docs/class#Class-的静态属性和实例属性)引用了一个位于 GitHub 上的[提案](https://github.com/jeffmo/es-class-properties)。
2017年6月9日，这个提案与其他提案合并了。

> NOTE: This proposal has been merged with the [Private Fields proposal](https://github.com/tc39/proposal-private-fields) to form a single unified proposal [here](https://github.com/tc39/proposal-class-fields).

更新？

**Comment by ruanyf** [comment]
看了一下，提案的内容没有改变，就是合并了。

我已经把链接修改掉了。
