### ISSUE TITLE
Class 和 Module 一章 有关 prototype 和 __proto__ 的问题

### ISSUE THREAD

**Issue by mescoda** [ruanyf/es6tutorial#43]
我觉得 `Class 和 Module` 一章 `Class 的 继承` 一节 `（2）prototype 属性` 部分，有点问题。

``` javascript

class A {
}

class B extends A {
}

```

在 ES6 中这样使得 B 继承 A 之后，会形成两条原型链
1. `B.__proto__ === A`
2. `B.prototype.__proto__ === A.prototype`

via: http://www.2ality.com/2015/02/es6-classes-final.html

`prototype` 和 `__proto__` 是有区别的，这点阮老师应该了解。

所以这部分的一些说法应该是 `子类的 __proto__ 属性都指向父类`

以及

``` javascript

class A {
}

A.__proto__ === Function.prototype
// true

class B extends A {
}

B.__proto__ === A
// true

class C extends Object {
}

C.__proto__ === Object
// true

```

但考虑到如果全部改成这样就跟这部分的标题 `（2）prototype 属性` 不符了，所以就不直接 PR 了。

**Comment by ruanyf** [comment]
谢谢指出，已经改了。
