### ISSUE TITLE
http://www.ruanyifeng.com/   验证权限？

### ISSUE THREAD

**Issue by xue1234jun** [ruanyf/es6tutorial#430]
This server could not verify that you are authorized to access the document requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.

**Comment by ruanyf** [comment]
今天，主机公司因为怀疑有安全漏洞，将我的网站停机了两个小时。现在已经恢复访问。

**Comment by xue1234jun** [comment]
http://www.ruanyifeng.com/blog/javascript/  这个网址好像还是有问题的 ，Forbidden了。阮老师看看
