### ISSUE TITLE
Number.isInteger() 在输入非安全范围内的整数也应当返回 true

### ISSUE THREAD

**Issue by huanguolin** [ruanyf/es6tutorial#433]
首先非常感谢你分享的书籍《ES6入门》。

我在看到 [Number-isInteger](http://es6.ruanyifeng.com/#docs/number#Number-isInteger) 时对比了 chrome 执行结果。发现你写的这个 `Number.isInteger()`  垫片函数会对非安全的整数返回 false:
```
// ES5可以通过下面的代码，部署Number.isInteger()。

(function (global) {
  var floor = Math.floor,
    isFinite = global.isFinite;

  Object.defineProperty(Number, 'isInteger', {
    value: function isInteger(value) {
      return typeof value === 'number' && isFinite(value) &&
        value > -9007199254740992 && value < 9007199254740992 &&  // 这里做了安全整数的判断
        floor(value) === value;
    },
    configurable: true,
    enumerable: false,
    writable: true
  });
})(this);
```
在 [规范](https://tc39.github.io/ecma262/#sec-number.isinteger) 中也确实没有要求必须是安全的整数。

**Comment by ruanyf** [comment]
谢谢你的`Number.isInteger()`版本。

书里面的版本，主要是为了帮助读者理解，而不是考虑到各种 edge case。所以，我觉得还是保留原来的版本比较好，否则要花篇幅，解释这个实现。

**Comment by huanguolin** [comment]
额， 是我没有说清楚，上面贴的代码是你书中的代码。 [Number.isInteger](http://www.ecma-international.org/ecma-262/6.0/#sec-number.isinteger) 并不需要判断这个整数是否安全。所以，你的实现其实更复杂，更关键的是不符合规范的行为。我个人认为最好是遵守规范，当然我只是建议。

**Comment by ruanyf** [comment]
不好意思，我都忘了。

已经修改过了，删掉了检查安全整数那一行。
