### ISSUE TITLE
第22章第6节小疑问

### ISSUE THREAD

**Issue by wangbayang** [ruanyf/es6tutorial#446]
在第22章第6节最后部分，阮老师这样写的：

如果想在一条import语句中，同时输入默认方法和其他变量，可以写成下面这样。

import _, { each } from 'lodash';
对应上面代码的export语句如下。

export default function (obj) {
  // ···
}

export function each(obj, iterator, context) {
  // ···
}

export { each as forEach };
上面代码的最后一行的意思是，暴露出forEach接口，默认指向each接口，即forEach和each指向同一个方法。
**疑问：export { each as forEach } 暴漏出的是forEach接口,在import时 不是应该这样写吗
import _, { forEach } from 'lodash' ? ,还是说export中指明了 each as forEach之后，import还可以用 each?**

**Comment by ruanyf** [comment]
这是我写的不清楚。

上面一行改成了下面这样。

```javascript
import _, { each, each as forEach } from 'lodash';
```

**Comment by wangbayang** [comment]
a a
