### ISSUE TITLE
promise中的then()方法

### ISSUE THREAD

**Issue by ghost** [ruanyf/es6tutorial#448]
章节：3.Promise.prototype.then() 
书中的前面是这样写的：
then方法返回的是一个新的Promise实例（注意，不是原来那个Promise实例）。因此可以采用链式写法，即then方法后面再调用另一个then方法。

再往下看两段，书中是这样写的：
采用链式的then，可以指定一组按照次序调用的回调函数。这时，前一个回调函数，有可能返回的还是一个Promise对象（即有异步操作），这时后一个回调函数，就会等待该Promise对象的状态发生变化，才会被调用。

这里说有可能返回一个Promise对象，也就是说有可能不会返回一个Promise对象。而前面说then方法返回的是一个新的Promise实例

问一下老师，返回实例和返回对象是一回事吗？？

**Comment by ruanyf** [comment]
你看教程里面的例子。

```javascript
getJSON("/post/1.json").then(function(post) {
  return getJSON(post.commentURL);
}).then(function funcA(comments) {
  console.log("Resolved: ", comments);
}, function funcB(err){
  console.log("Rejected: ", err);
});
```

`then`返回的肯定是一个 Promise 对象。但是如果它里面的操作，本身就会返回 Promise 对象，比如上面的 getJSON()，那么这个 Promise 对象就会替代 then 自己产生的 Promise 对象作为返回值。
