### ISSUE TITLE
变量的解构赋值之圆括号

### ISSUE THREAD

**Issue by albyho** [ruanyf/es6tutorial#450]
声明一下，我是Javascript新手，没系统学过Javascript。
1、
关于圆括号的详细解释建议放在"数组的解构赋值"，而不是后面的"对象的解构赋值"中，毕竟前者在文前。

2、
var a = [];
for (let i = 0; i < 10; i++) {
  a[i] = function () {
    console.log(i);
  };
}
a[6](); // 6

能否解释下在闭包中，对 let 变量的捕获原理？

3、
如果解构失败，变量的值等于undefined。

let {foo} = {bar: 'baz'};
foo // undefined

我觉得放在稍前一点解释会好点。可结合：
let foo;
foo // undefined
作为对比学习。

4、
关于下面这个，我琢磨了一下：
var node = {
  loc: {
    start: {
      line: 1,
      column: 5
    }
  }
};

var { loc: { start: { line } } } = node;
line // 1
loc  // error: loc is undefined
start // error: start is undefined

如果真要获取 node 的 loc 的 start 的值，语法是：
let { loc: { start } } = node;
或
let { loc: { start: start } } = node;
或
let { loc: { start: start1 } } = node;

同理，如果真要获取 node 的 loc 的值，语法是：
let { loc } = node;
或
let { loc: loc } = node;
或
let { loc: loc1 } = node;

如果要取 start 的整体，同时又要取 start 的 column，语法是:
let { loc: { start }, loc: { start: { column } } } = node;

5、
数组的解构赋值，这样也可以：
let [x, y = x + 2] = [1];

**Comment by ruanyf** [comment]
1. 解构赋值的圆括号比较不重要，也难解释，所以放到后面的部分。

2 和 3 都是 ES5 的内容，所以这本教程不多解释了。

4 和 5 你的理解非常好，这个例子我决定加到书里了。
