### ISSUE TITLE
二进制和八进制表示法

### ISSUE THREAD

**Issue by albyho** [ruanyf/es6tutorial#452]
如果要将0b和0o前缀的字符串数值转为十进制，要使用Number方法。

Number('0b111')  // 7
Number('0o10')  // 8

非字符串也是可以的：

Number(0b111)  // 7
Number(0o10)  // 8

**Comment by ruanyf** [comment]
系统会自动转数字。

```javascript
console.log(0b111) // 7
```

感觉那一段不是很必要，考虑删掉它。
