### ISSUE TITLE
关于Class的继承那一章中版本功能的数组的问题

### ISSUE THREAD

**Issue by 313183373** [ruanyf/es6tutorial#460]
```
class VersionedArray extends Array {
  constructor() {
    super();
    this.history = [[]];
  }
  commit() {
    this.history.push(this.slice());
  }
  revert() {
    this.splice(0, this.length, ...this.history[this.history.length - 1]);
  }
}

var x = new VersionedArray();

x.push(1);
x.push(2);
x // [1, 2]
x.history // [[]]

x.commit();
x.history // [[], [1, 2]]

x.push(3);
x // [1, 2, 3]
x.history // [[], [1, 2]]

x.revert();
x // [1, 2]
```

在revert()方法中```   revert() {
    this.splice(0, this.length, ...this.history[this.history.length - 1]);
  } ```如果有多次提交，由于每次恢复时都是取history.length，每次都会恢复成上一次提交，所以连续revert时就永远都是上一个提交状态，而不能达到上上个，所以我觉得如果不考虑revert回来还能revert回去的这种情况下，可以直接在revert()时候就让history数组POP出来一个，就修复了上述的问题，不知道阮一峰老师怎么看

**Comment by ruanyf** [comment]
你的写法是对的，但是这样会改变 history。作为版本，一旦写入，应该是不能删掉。

这个例子确实不能多次 revert，只能撤销最新一次 commit。我想了想，如果改掉的话，代码会变得复杂一些。作为示例，好像还是保持简单比较好，目的是让大家看懂。所以我就不改了，希望得到你的理解。
