### ISSUE TITLE
5.10 笔误

### ISSUE THREAD

**Issue by merrye** [ruanyf/es6tutorial#463]
##  5.10 具名组匹配下的解构赋值和替换一小节中有一处小笔误
`'2015-01-02'.replace(re, (
   matched, // 整个匹配结果 2015-01-02
   capture1, // 第一个组匹配 2015
   capture2, // 第二个组匹配 01
   capture3, // 第三个组匹配 02
   position, // 匹配开始的位置 0
   

> S, // 原字符串 2015-01-05

   groups // 具名组构成的一个对象 {year, month, day}
 ) => {
 let {day, month, year} = args[args.length - 1];
 return `${day}/${month}/${year}`;
});`
## replace第二个参数的参数序列中的的S应该是2015-01-02

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
