### ISSUE TITLE
promise执行顺序相关

### ISSUE THREAD

**Issue by tan520500** [ruanyf/es6tutorial#467]
图1
![1](https://user-images.githubusercontent.com/17905854/29032694-f4651ea4-7bc4-11e7-908c-bdce602f12c4.png)

图2
![2](https://user-images.githubusercontent.com/17905854/29032741-34080490-7bc5-11e7-933c-3851ba440da3.png)

阮老师，按照图1的理解，图2里的 throw new Error('test');语句不是应该先执行吗，麻烦问一下这里应该怎么理解，谢谢~

**Comment by ruanyf** [comment]
我的理解是，Promise 内部实现是有`try...catch`的。一旦状态变成`resolved`，后面再抛出错误，都会被`catch`掉，不再冒泡。
