### ISSUE TITLE
Promise 状态描述与标准有出入

### ISSUE THREAD

**Issue by MondoGao** [ruanyf/es6tutorial#469]
在 Ecma-262 标准 25.4 一节 [Promise Objects](https://www.ecma-international.org/ecma-262/8.0/index.html#sec-promise-objects) 中，Resolved 状态被描述为“ resolve 或 reject 方法无法变更 Promise 状态”的一种状态，而 Fulfilled 则是“ then(f) 中的 f 会立即被插入到执行队列中”的状态。在本书 [Promise-的含义](http://es6.ruanyifeng.com/#docs/promise#Promise-的含义) 一节中将其作为同一种状态略有不妥，不知是否有其他考量。

BTW：差点一个激动发 PR，后来发现全篇大量使用 resolved 这个状态，赶紧压压火发个 Issue 问一下

**Comment by XGHeaven** [comment]
具体的规范我没有读过，但是我感觉用 `Fulfilled` 是更加正规的方式。
在描述状态的时候用 `Fulfilled`，但是在描述过程或者一个动作的时候用 `Resolved`。
比如

> 如果 Promise 的状态为 Fulfilled 的时候，不能进行变更
> 如果 Promise 被 Resolved 的时候，不能再次通过 reject 或者 reject 修改其中的状态和值。

我觉得不是很需要全部改，只需要在头部介绍的时候说明一下就好了，让读者清楚这两个有区别，但是后面的教程统一用 `Resolved` 的代替 `Fulfilled` 没什么太大的问题。毕竟很多教科书都是这样的节奏。

> 后文我们统一用 `Resolved` 代替 `Fulfilled` 这个状态进行描述，方便读者理解。

感觉这样理解起来会更好理解。

**Comment by ruanyf** [comment]
Promise 三种状态的正式用语是 Fulfilled、Rejected 和 Pending。但是，Promise 作为构造函数，接受的两个参数是 resolve 和 reject。

所以，正确的介绍应该是“调用 resolve 函数以后，Promise 状态变为 Fulfilled”。但是，我觉得在中文教程中，这样不如“调用 resolve 函数以后，Promise 状态变为 resolved”更好懂。

我希望，在教程中出现的英文单词越少越好，降低中文读者的理解负担。所以，这里是刻意的，故意不提 fulfilled，只说 resolved（因为 resolve 和 reject 这两个词是无法避免的）。从规格的角度，可能不完全正确，但是有利于行文。而且，我觉得使用 resolved 替代 fulfilled，对正确使用 Promise 不会有影响。

**Comment by ruanyf** [comment]
又想了想，用 resolve 替代 fulfilled 确实不妥。

我修改一下原文吧。

**Comment by MondoGao** [comment]
无论是 Promise.resolve 还是传入到 handler 中的 resolve，都会让一个 promise 变为 resolved 状态，但 resolved 的状态是可能向两种方向发展的：

```javascript
const p = new Promise((resolve, reject) => {
  // p 转变为 resolved 状态
  resolve(new Promise((resolve, reject) => {
    // 到时间后，p 将由 resolved 状态转变为 rejected 状态
    setTimeout(reject, 100, '想不到吧！（手动滑稽）');
  }));
});

p.then(
  onFulfilled, // 不会执行
  function onRejected(msg) {
    console.log(msg); // => '想不到吧！（手动滑稽）'
  }
)
```

这个例子可以清楚的表示 `resolved` 和 `fulfilled` 状态的区别

**Comment by XGHeaven** [comment]
@MondoGao 如果当前 promise(A) resolve 了一个 promise(B)，那么可以认为当前 promise(A) 装填为 fulfilled，然后将这个 promise(A) 上面的所有挂载 then 和 catch 全部转移到 promise(B) 中，相当于之后 reject 是由 promise(B) 引起的，而不是 promise(A) 先 resolve 后 reject 引起的。
我去文档找找相关的介绍。

**Comment by XGHeaven** [comment]
我有看了一下文档当中的介绍，确实在文档当中 `Resolved` 代表的意思是这个 promise 已经被完成了，他同时包含两个状态 `Fulfilled` 和 `Rejected`。也就是说只要 promise 的状态不是 `Pending` 那么他的状态就是 `Resolved`。
问题就在这里， Promise 规范是用 `Resolved` 来代表两种完成状态。但是 `Resolve` 单词的过去式正是 `Resolved`，所以会给人一种 `Resolved` 是 `Resolve` 动作带来的状态。所以还是添加一下说明会比较好。
哎呀，好吧，好像作者已经改掉了。那就当我啥都没说，哈哈哈。

**Comment by MondoGao** [comment]
@XGHeaven Resolved 的确是 resolve 动作带来的状态，具体看上面那个栗子。
promise 如果不是 pending 态，那么它有可能是 resolved or settled 状态，settled 同时包含 fulfilled 和 rejected 状态。
另外，实际上不是将 A 的 then 队列转移至 B 中，而是相当于
```javascript
resolve(B);
// 实际上
B.then(resolve/* 属于 A */, reject)
```

**Comment by XGHeaven** [comment]
好吧。。。

**Comment by hellobeifeng** [comment]
一直觉得，文章的精彩回复能让我了解到更多的视角！

**Comment by wanhmr** [comment]
@MondoGao 
```
A Promise is an object that is used as a placeholder for the eventual results of a deferred (and possibly asynchronous) computation.

Any Promise object is in one of three mutually exclusive states: fulfilled, rejected, and pending:

A promise p is fulfilled if p.then(f, r) will immediately enqueue a Job to call the function f.
A promise p is rejected if p.then(f, r) will immediately enqueue a Job to call the function r.
A promise is pending if it is neither fulfilled nor rejected.
A promise is said to be settled if it is not pending, i.e. if it is either fulfilled or rejected.

A promise is resolved if it is settled or if it has been “locked in” to match the state of another promise. Attempting to resolve or reject a resolved promise has no effect. A promise is unresolved if it is not resolved. An unresolved promise is always in the pending state. A resolved promise may be pending, fulfilled or rejected.
```
> A promise is said to be settled if it is not pending, i.e. if it is either fulfilled or rejected.

从文档来看，`Promise` 共有三种状态，分别是 `Pending`、`Fulfilled`、`Rejected`。而`settled ` 说的是 `fulfilled` 或者 `rejected `。

但是这句话
> An unresolved promise is always in the pending state. A resolved promise may be pending, fulfilled or rejected.

又把我绕晕了。
既然已经 `resolved`，为什么还可能是 `pending` 状态。
我是刚刚接触 js 的新手，其实没有实际用过 `Promise`。

**Comment by MondoGao** [comment]
@wanhmr
因为可以 resolve 一个新的 promise，新的 promise 状态其实是不确定的，但老 promise 已经被 resolved 不可再变了。

**Comment by wanhmr** [comment]
@MondoGao O(∩_∩)O谢谢

**Comment by adispring** [comment]
根据这篇文章：https://github.com/domenic/promises-unwrapping/blob/master/docs/states-and-fates.md

promise 有三种 states（状态）：pending、fulfilled 和 rejected，
两种 fates （命运）：resolved 和 unresolved；

将 resolved 称作 “resolved 状态” 感觉可能会造成理解上的歧义？但 fates 翻译为 “命运” 感觉又太生硬 😏

@MondoGao
