### ISSUE TITLE
「勘误」： 12. Promise对象一节出现错误

### ISSUE THREAD

**Issue by sursir** [ruanyf/es6tutorial#47]
##### 详细信息：

`client.onreadystatechange`进行回调处理时，`handle`方法中
没有判断**`readyState`**的状态， 这样带来的结果是 **`readyState == 2`**时提前触发了`resolve`回调函数，导致运行错误。

**Comment by xqin** [comment]
请参考这个: https://github.com/ruanyf/es6tutorial/issues/97
你所发现的问题已经反馈给作者了.
