### ISSUE TITLE
2.1 let命令用babel-node后运行结果与教程不符

### ISSUE THREAD

**Issue by hellobeifeng** [ruanyf/es6tutorial#470]
for (let i = 0; i < 3; i++) {
  let i = 'abc';
  console.log(i);
}
环境：node v5.6.0 
1、直接在 nodejs 的 严格模式下运行node code.js,输出与教程一致；
abc
abc
abc
2、使用babel编译后只输出一次  babel-node code.js
abc

**Comment by ruanyf** [comment]
尽可能不要用 Babel。

**Comment by hellobeifeng** [comment]
嗯，我尽量在高版本的node环境中直接运行代码
