### ISSUE TITLE
Class 的基本语法 此章

### ISSUE THREAD

**Issue by zhiyongsun** [ruanyf/es6tutorial#473]
```
class MyClass {
  constructor() {
    // ...
  }
  get prop() {
    return 'getter';
  }
  set prop(value) {
    console.log('setter: '+value);
  }
}

let inst = new MyClass();

inst.prop = 123;
// setter: 123

inst.prop
// 'getter'
```
最好还是将"return 'getter';"改为"console.log('getter');" 单独运行此段代码时候,return不会打印出来'getter'

**Comment by ruanyf** [comment]
这不是打印，而是返回值，比如下面的用法。

```javascript
console.log('It is ' + inst.prop);
```

**Comment by zhiyongsun** [comment]
是这样的,在阅读此段代码的时候,会尝试着运行一下此段代码.在执行到'inst.prop = 123;',会输出就像注释这里'setter: 123';在执行到'inst.prop',发现没有任何反应,当时有点疑惑,后来查看仔细查看代码才发现,这里并没有log,个人认为替换为log更好一些.

**Comment by ruanyf** [comment]
`get`是取值器，应该返回一个值。

**Comment by stenders** [comment]
@ysbpysbp 然鹅你说的并不是“更好些”，而是错误的用法
希望看到log，你就需要在下面读取属性时自己带log而不是需要程序本身给你log
