### ISSUE TITLE
async部分代码好像有错误

### ISSUE THREAD

**Issue by ishowman** [ruanyf/es6tutorial#475]
![image](https://user-images.githubusercontent.com/16897283/29301657-57dce34a-81b0-11e7-8db7-15d05d6b7c15.png)
await只能在async函数内部执行，图中的使用方式代码会报错吧？我是ES6初学者，如是理解错误，望指点迷津。

**Comment by ruanyf** [comment]
这里是为了简洁，省略了`async`函数。也就是说，`await`默认放在`async`里面，所以就省略了。
