### ISSUE TITLE
修饰器一节的笔误

### ISSUE THREAD

**Issue by Thomaszzc** [ruanyf/es6tutorial#476]
位置： http://es6.ruanyifeng.com/#docs/decorator  decorator 那一节的 core-decorator.js 里面的第五条@supressWarnings
"suppressWarnings修饰器抑制decorated修饰器导致的console.warn()调用。但是，异步代码发出的调用除外"。
这一句里面 “supressWarnings 修饰器抑制decorated 修饰器”，应该是 “抑制deprecated 修饰器”

**Comment by qqdayan** [comment]
位置：正则表达式那一节，后行断言，匹配不在美元后面的数字，这个例子给的结果是90，其实匹配不到的
/(?<!\$)\d+/.exec('it’s is worth about €90')

**Comment by ruanyf** [comment]
@qqdayan 为什么匹配不到？

@Thomaszzc 谢谢指出，已经改正了。

**Comment by qqdayan** [comment]
对不起看错了，”后行否定断言“，x只有不在y后面才匹配，必须写成/(?<!y)x/。我把那个符号看成美元符号了，哈哈 @ruanyf
