### ISSUE TITLE
关于 `javascript` 传值调用

### ISSUE THREAD

**Issue by wanhmr** [ruanyf/es6tutorial#482]
在 `Generator 函数的异步应用` 这一章节中的 `JavaScript 语言的 Thunk 函数` 这一小节：
> JavaScript 语言是传值调用，它的 Thunk 函数含义有所不同。在 JavaScript 语言中，Thunk 函数替换的不是表达式，而是多参数函数，将其替换成一个只接受回调函数作为参数的单参数函数。

但是在 `Thunk 函数的含义` 这一小节中：
> 这就是 Thunk 函数的定义，它是“传名调用”的一种实现策略，用来替换某个表达式。

按照上下文，`JavaScript` 语言不应该是传名调用吗？

非常感谢阮老师的 tutorial。

**Comment by ruanyf** [comment]
Thunk是传名调用的一种实现手段，让传值调用的语言也有办法实现传名调用。

JavaScript 里面的 Thunk，基本上与这个含义无关，就是指原函数的一种改写形式，变成一个只接受回调函数作为参数的函数。
