### ISSUE TITLE
generator函数next()方法的参数问题

### ISSUE THREAD

**Issue by iamzephyr** [ruanyf/es6tutorial#497]
阮老师您好：
http://es6.ruanyifeng.com/#docs/generator#next-方法的参数 。   这一小节里面我

```
            function* foo(x) {
                 var y = 2 * (yield (x + 1));
                 var z = yield (y / 3);
                   return (x + y + z);
            }
          var b = foo(5);
          b.next() // { value:6, done:false }
          b.next(12) // { value:8, done:false }
          b.next(13) // { value:42, done:true }
```
我的问题：1.第一次next()的返回值是 6，y=12  ,这个我明白了
                  2. 第二next(12) 传参 表达式的值为什么=8，不是12/3=4吗

**Comment by iamzephyr** [comment]
不好意思,前面我理解错了。第二次next(12)  这里 意思是 yield(x+1)这个表达式=12，所以y等于24了。
第三次next(13)传参，z=yield(y/3)=13  返回值 5+24+13=42 
就是说：每次next(n)传参了，都会把上一次的yield重新计算一遍。是这样吗

**Comment by ruanyf** [comment]
next 的参数就是 yield 表达式的返回值。

**Comment by iamzephyr** [comment]
好的，谢谢老师。
