### ISSUE TITLE
class 继承章节

### ISSUE THREAD

**Issue by xiaoxiaoaobama** [ruanyf/es6tutorial#499]
class A {
  constructor() {
    this.x = 1;
  }
}

class B extends A {
  constructor() {
    super();
    this.x = 2;
    super.x = 3;
    console.log(super.x); // undefined
    console.log(this.x); // 3     在浏览器中实际打印2。
  }
}

let b = new B();

**Comment by ruanyf** [comment]
我手边的 Chrome 56 和 Firefox 51 都打印 3。

Node 8.5 也打印 3。

**Comment by shenke119** [comment]
直接运行打印的是3  经过编译后打印的是2
