### ISSUE TITLE
[promise章节]有一个疑问: promise的异常如果没有捕获,将不会被抛到外层代码

### ISSUE THREAD

**Issue by 18boys** [ruanyf/es6tutorial#500]
原文是:

> someAsyncThing函数产生的 Promise 对象会报错，但是由于没有指定catch方法，这个错误不会被捕获，也不会传递到外层代码。正常情况下，运行后不会有任何输出，但是浏览器此时会打印出错误“ReferenceError: x is not defined”，不过不会终止脚本执行，如果这个脚本放在服务器执行，退出码就是0（即表示执行成功）。

但是我在最新版 chrome 上尝试的时候,控制台明确打印出
> VM57439:4 Uncaught (in promise) ReferenceError: x is not defined
    at <anonymous>:4:13
    at Promise (<anonymous>)
    at someAsyncThing (<anonymous>:2:10)
    at <anonymous>:8:1

浏览器明确指出是未捕获的异常.你的文章中指出运行后不会有任何输出,但是浏览器会打印出错误,这二者是不是明显不同,你的文章中这句话是不是有点让人摸不着头脑?是不是应该把 '正常情况下，运行后不会有任何输出' 删掉?

还有我用 node执行你文中的这段代码的时候:
```
var someAsyncThing = function() {
  return new Promise(function(resolve, reject) {
    // 下面一行会报错，因为x没有声明
    resolve(x + 2);
  });
};

someAsyncThing().then(function() {
  console.log('everything is great');
});
```
控制台报这个错误
> (node:18748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): ReferenceError: x is not defined
(node:18748) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

明确指出未来 promise 在没有异常捕获的时候将会导致非0退出,文中应该指名这点,预防读者在这儿犯错

第一次提 issue,有不当之处请指出并原谅~

**Comment by ruanyf** [comment]
这里的意思是，Promise 里面的报错不会导致进程终止。原文写的不太清楚，输出是专指`console.log`的输出。

请看下面的代码。

```javascript
var someAsyncThing = function() {
  return new Promise(function(resolve, reject) {
    // 下面一行会报错，因为x没有声明
    resolve(x + 2);
  });
};

// 新增一行
setTimeout(() => {console.log('abc')}, 2000);

someAsyncThing().then(function() {
  console.log('everything is great');
});
```

上面代码运行后，还是会输出`abc`，证明 Promise 里面的报错不会终止进程。
