### ISSUE TITLE
函数默认值x=x问题

### ISSUE THREAD

**Issue by snayan** [ruanyf/es6tutorial#502]
我看第3版时，书中写着

```
function foo(x=x){
    //...
}
foo() // ReferenceError: x is not defined 
```

但是，如果我这样调用`foo(1)`。就不会报错了。
![image](https://user-images.githubusercontent.com/18651872/30725378-eba64966-9f76-11e7-985f-82ab7a0fc165.png)

我在chrome里调试了。
如果按照书中写的，实际执行的是`let x=x;`。这样感觉解释不通。
还请阮老师解答。

**Comment by ruanyf** [comment]
这是因为参数的默认值是在运行时求值，如果`foo(1)`不会触发默认值。
