### ISSUE TITLE
第24章《编程风格》中 ESLint 相关内容是否需要更新？

### ISSUE THREAD

**Issue by liuzhuan** [ruanyf/es6tutorial#506]
> 多家公司和组织已经公开了它们的风格规范，具体可参阅 jscs.info，下面的内容主要参考了Airbnb的JavaScript风格规范。

jscs.info 已经与 ESLint 合并，而且从 v3.0.6 开始至今，jscs.info 已经一年多未更新，而 ESLint 更新很频繁。是否可以把 jscs.info 替换为 ESLint 地址？

> 10. ESLint的使用

目前 ESLint v4.7.2 的使用方法有了调整，照书中命令运行会报错。是否可以更新为新版命令？比如下面是一个可运行的简单样例。

首先，安装ESLint。

```
$ npm install eslint --save-dev
```

然后，初始化配置文件：

```
$ ./node_modules/.bin/eslint --init
```

现在就可以检查，当前项目的代码是否符合预设的规则。

```
$ ./node_modules/.bin/eslint yourfile.js
```

感谢阮老师！

**Comment by ruanyf** [comment]
谢谢指出，已经更正了内容。
