### ISSUE TITLE
关于Number.EPSILON

### ISSUE THREAD

**Issue by Mr-shao** [ruanyf/es6tutorial#508]
阮老师您好：
文中提到
```
function withinErrorMargin (left, right) {
  return Math.abs(left - right) < Number.EPSILON;
}
```
的方法检测是否在误差范围内
Number.EPSILON大于1的最小可表示数 与 1的差，根据IEEE754标准，就是(Number.parseInt("1"+"0".repeat(51)+"1",2) * 2 ** -52) - 1  === 2 ** -52；
并不能用来检测是否在误差范围内，比如withinErrorMargin(1.1 + 1.3, 2.4) === false；

老师，我这还有个疑问就是浮点数计算的误差最大值要怎么计算，通过parseFloat(value.toFixed(12))舍去误差方法中的toFixed括号中的值取多少更合适，谢谢

**Comment by waitingsong** [comment]
withinErrorMargin(1.1 + 1.3, 2.4) === false;
表示 1.1+ 1.3 和 2.4是逻辑相等的

**Comment by ruanyf** [comment]
谢谢指出，我原先没注意到 Number.EPSILON 是 JavaScript 的最小精度。

已经改正了，误差范围只要设为 Number.EPSILON 的倍数就可以了。

> `Number.EPSILON`可以用来设置“能够接受的误差范围”。比如，误差范围设为2的-50次方（即`Number.EPSILON * Math.pow(2, 2)`），即如果两个浮点数的差小于这个值，我们就认为这两个浮点数是相等的。

```javascript
function withinErrorMargin (left, right) {
  return Math.abs(left - right) < Number.EPSILON * Math.pow(2, 2);
}

1.1 + 1.3 === 2.4 // false
withinErrorMargin(1.1 + 1.3, 2.4) // true
```

**Comment by mlyknown** [comment]
get

**Comment by mlyknown** [comment]
为什么要乘 Math.pow(2, 2) 呢

**Comment by youge** [comment]
回楼上，原文是 :

> Number.EPSILON可以用来设置“能够接受的误差范围”。比如，误差范围设为2的-50次方（即Number.EPSILON * Math.pow(2, 2)），即如果两个浮点数的差小于这个值，我们就认为这两个浮点数是相等的。

作者说误差范围要设成 2 的 -50 次方(也就是 2^(-50))，而 Number.EPSILON * Math.pow(2, 2) 正好等于 2^(-52) * 2^2 = 2^(-50) 啊。
这个误差范围是主观决定的，如果你想把误差范围设大一点也没问题，这里只是为了达到作者说的误差范围，所以乘以了 Math.pow(2, 2) 而已。

**Comment by mlyknown** [comment]
原来如此 thx
