### ISSUE TITLE
String.raw demo是不是有问题？和我打印出来的不一样？

### ISSUE THREAD

**Issue by hu949277923** [ruanyf/es6tutorial#511]
我的浏览器是chrome 61.0.3163.100
String.raw`Hi\n${2+3}!`;
// "Hi\\n5!"

String.raw`Hi\u000A!`;
// 'Hi\\u000A!'
上面是您demo
我打印的结果如下：
console.log(String.raw`Hi\n${2+3}!`); // Hi\n5!
console.log(String.raw`Hi\u000A!`); // Hi\u000A!
请教下为啥不一样？和浏览器有关吗？还是？

**Comment by ruanyf** [comment]
浏览器显示的转义后的结果。

```javascript
String.raw`Hi\n${2+3}!`=== "Hi\\n5!"
// true
```
