### ISSUE TITLE
字符串扩展，demo错误

### ISSUE THREAD

**Issue by hu949277923** [ruanyf/es6tutorial#512]
浏览器 chrome 61.0.3163.100
String.raw()
String.raw = function (strings, ...values) {
  let output = "";
  for (let index = 0; index < values.length; index++) {
    output += strings.raw[index] + values[index];
  }

  output += strings.raw[index]   // 问题：index在此作用域下是无法找到的，这里报错了：  index is not defined
  return output;
}
  console.log(String.raw({ raw: 'test' }, 0, 1, 2));

**Comment by ruanyf** [comment]
#510 已经修正了。
