### ISSUE TITLE
systemjs运行的时候不需要调用traceur

### ISSUE THREAD

**Issue by lovetingyuan** [ruanyf/es6tutorial#513]
module-loader中提到systemjs后台调用traceur，这个不太对吧，systemjs只是对各种模块格式进行封装以及依赖加载，没有对代码进行转译哦

**Comment by ruanyf** [comment]
https://github.com/systemjs/systemjs/blob/f732daa29bece8051ad9e58b4b54c1142371b3bd/package.json#L29

**Comment by lovetingyuan** [comment]
你不能看到packagejson里引入了就说代码中使用了吧，引入traceur只是为了测试使用，因为systemjs需要在配置里支持traceur所以需要test下，但是不配置tranceur就不会进行转译，因为systemjs不需要转义代码，这不是这个库本身的工作范围，另外package.json中还有Babel，这个也可以用来转义

**Comment by ruanyf** [comment]
看了一下，新版改掉了，老版默认用 traceur 转码。https://stackoverflow.com/questions/35963219/using-systemjs-in-production-without-traceur

**Comment by lovetingyuan** [comment]
好的 感谢！
