### ISSUE TITLE
有个地方和co的官网说的不一样

### ISSUE THREAD

**Issue by wocaatm** [ruanyf/es6tutorial#522]
老师好，我在Generator异步函数的应用那节，co模块的原理下面看到了您说的co v4.0版以后，yield命令后面只能是 Promise 对象，不再支持 Thunk 函数。但是co官网上说还是可以的，我也试了可以，只是co的返回改变了，之前可以是thunk函数，自己添加回调，现在返回的只能是Promise对象了

![igf4t1_f 4bq 5zd2ru 59](https://user-images.githubusercontent.com/11764069/31642633-864a7e46-b31e-11e7-9202-46e2e7abb1cb.png)
![9q qciwpusk0 r j81wm](https://user-images.githubusercontent.com/11764069/31642638-887a1d5c-b31e-11e7-9b87-8e6e54368cf3.png)
![xp j2 f bi _ 85dbpvra1x](https://user-images.githubusercontent.com/11764069/31642680-b7dae0ea-b31e-11e7-910f-9b1a641ccc65.png)

不知道我说的对不对。麻烦您看一下

**Comment by ruanyf** [comment]
谢谢指出，我看得不仔细，一直以为 Co 不支持 Thunk 了。

我马上修改文档。
