### ISSUE TITLE
关于Set 数据结构 forEach() 方法的疑问

### ISSUE THREAD

**Issue by ronggang** [ruanyf/es6tutorial#523]
阮老师你好，
近日在学习 http://es6.ruanyifeng.com/#docs/set-map 这个章节时，下面这一段读起来有点绕
![image](https://user-images.githubusercontent.com/8065899/31696356-2adf8838-b3e3-11e7-85e4-7dbbc6ea9565.png)

关于 forEach() 方法的参数，应该怎么理解？3个还是2个？

谢谢！

**Comment by ruanyf** [comment]
forEach 方法有两个参数：forEach(fn, this)，其中`fn`是一个函数，有三个参数。

**Comment by ronggang** [comment]
谢谢阮老师的解答！
