### ISSUE TITLE
关于setTimeout和event loop

### ISSUE THREAD

**Issue by Yanchenyu** [ruanyf/es6tutorial#526]
阮老师您好，先赞美一下，es6第三版真的很赞，受益匪浅，内容讲解很细很全面，老师辛苦了！
回到问题，在书上第290页，谈到Promise.resove()方法时，对比了setTimeout()，原文是"setTimeout(fn, 0)是在下一轮'事件循环'开始时执行的“，但是之前您在网络日志中“JavaScript 运行机制详解：再谈Event Loop”里面第五大点“定时器”里面讲道：“总之，setTimeout(fn,0)的含义是，指定某个任务在主线程最早可得的空闲时间执行，也就是说，尽可能早得执行。它在"任务队列"的尾部添加一个事件，因此要等到同步任务和"任务队列"现有的事件都处理完，才会得到执行。”意思是在当前队列尾部添加一个事件，而书上是在下一轮头部开始时执行，请问这是否矛盾？

**Comment by ruanyf** [comment]
书里是对的。

我以前那篇文章没有区分微任务和异步任务，所以只是模糊地说要”尽可能早得执行“。也就是说，写那篇文章时，我没意识到任务可能会添加在本轮事件循环的结尾。
