### ISSUE TITLE
10.3 消除魔术字符串

### ISSUE THREAD

**Issue by muzishuiji** [ruanyf/es6tutorial#527]
你说symbol类型的变量可以消除魔术字符串
所以书上的例子中将函数中多次使用到的'Triangle'字符串换成了Symbol(),但是这个代码是有switch的,他是要做比较的,这样会导致这个switch传进去的shape参数永远都不等于第一种情况下的 shape.triangle  
所以这样不是看似解决了问题,但是事实上已经达不到想要的目的了呢?还是我理解错了,请求指导.

**Comment by ruanyf** [comment]
原代码是正确的，你可以执行一下，能得到结果的。

因为传入`getArea`的是`shapeType.triangle`。

**Comment by muzishuiji** [comment]
好的,我知道了,我没认真看的原因.
