### ISSUE TITLE
求添加webpack2 摇树优化简单实现

### ISSUE THREAD

**Issue by xiaofan9** [ruanyf/es6tutorial#528]
能否在es6 module这些相关章节加个webpack 摇树优化的简单实现？
看了很多文章多是再讲他的实现原理，但是看完之后特懵逼到底怎么做的，也有想过去看webpack 源码，但是看不懂😭，还找了好久才找到的。希望能加下，感觉对理解module很多帮助。

**Comment by ruanyf** [comment]
摇树的实现，我也没看过。

以后有空研究一下 Rollup 的实现，再看能不能写到书里。
