### ISSUE TITLE
函数的扩展--绑定this绑定语法表述存疑

### ISSUE THREAD

**Issue by kfayay** [ruanyf/es6tutorial#529]
由于双冒号运算符返回的还是原对象，因此可以采用链式写法。

- 上面表述中，“双冒号运算符返回”，运算符有返回值这样的表述是否有误？
- 双冒号运算符作为bind，apply，call的语法糖，返回结果是绑定函数执行的结果，不应该是原对象吧？
因此例子中的链式写法也和双冒号运算符没有因果关系了。

**Comment by ruanyf** [comment]
谢谢指出，我改一下。
