### ISSUE TITLE
函数的扩展一章中，有一点不理解

### ISSUE THREAD

**Issue by baskinwind** [ruanyf/es6tutorial#531]
下面是一个更复杂的例子。
```
var x = 1;
function foo(x, y = function() { x = 2; }) {
  var x = 3;
  y();
  console.log(x);
}

foo() // 3
x // 1
```
上面代码中，函数foo的参数形成一个单独作用域。这个作用域里面，首先声明了变量x，然后声明了变量y，y的默认值是一个匿名函数。这个匿名函数内部的变量x，指向同一个作用域的第一个参数x。函数foo内部又声明了一个内部变量x，该变量与第一个参数x由于不是同一个作用域，所以不是同一个变量，因此执行y后，内部变量x和外部全局变量x的值都没变。

=================

上面是原文，但是在这节的开头又说过这样一句

> 等到初始化结束，这个作用域就会消失。

所以这个作用域不是应该已经消失了吗？在浏览器上运行确实是这样输出的，但是既然是一个单独的作用域，那么是可以用 `let` 的，所以我把 `var` 改成了 `let` 之后，就报错了，错误是：
```
let x = 1;
function foo(x, y = function() { x = 2; }) {
  let x = 3;
  y();
  console.log(x);
}

foo()
x
Uncaught SyntaxError: Identifier 'x' has already been declared
```
从报错来看是因为函数的作用域中的 `let` 重复声明照成的，所以那个参数的作用域和函数的作用域应该不是完全独立的关系吧？
不是很理解为什么？想请教下

**Comment by ruanyf** [comment]
参数作用域会与函数体作用域合并，所以不能再次声明`x`。`var`命令可以再次声明的。

**Comment by baskinwind** [comment]
但是这句话：
> 函数foo内部又声明了一个内部变量x，该变量与第一个参数x由于不是同一个作用域，所以不是同一个变量

而且从结果看确实有两个作用域里的 x 因为函数 y 的执行没有改变 x 的值，如果合并了的话应该结果是 2 吧
而且函数的参数的声明是使用 let 的，在正常情况下不应该是声明了let变量后在声明var也是会报错的么。

**Comment by ruanyf** [comment]
你看下面的代码。

```javascript
// 不报错
function f(x) {
  var x;
}
f();

// 报错
function f(x) {
  let x;
}
f()
```

**Comment by baskinwind** [comment]
嗯  了解，感谢
还有就是尾递归优化实现那章中的一个例子：
```
function sum(x, y) {
  if (y > 0) {
    return sum(x + 1, y - 1);
  } else {
    return x;
  }
}
```
和这个例子感觉是差不多的
```
function Fibonacci2 (n , ac1 = 1 , ac2 = 1) {
  if( n <= 1 ) {return ac2};
  return Fibonacci2 (n - 1, ac2, ac1 + ac2);
}
```
我把sum函数可以改成和 Fibonacci2 函数写法一致
```
function sum(x, y) {
  if(y <= 0) return x;
  return sum(x+1,y-1);
}
```
但为什么 Fibonacci2 是符合尾递归的，而 sum 函数是不符合尾递归的？
我在node环境下测试这两个函数，sum(1,10000) 和 Fibonacci2(10000) 都是不会报错的，而两个函数在100000下都报了 `Maximum call stack size exceeded`。
 O(1) 的复杂度应该是不会报这个错误的吧。。。。。
还是说当前的环境没有实现尾调用优化
我的node环境是 6.2.0

**Comment by ruanyf** [comment]
奇怪，尾递归确实没生效…… 

我还在找原因。

**Comment by flyyang** [comment]
尾调用优化只在严格模式下生效。
目前只有 safari 实现了尾调用优化。[https://kangax.github.io/compat-table/es6/](https://kangax.github.io/compat-table/es6/)
可以看之前写的一篇文章，[尾调用优化](https://flyyang.github.io/2017/07/24/JavaScript-%E4%B8%AD%E7%9A%84%E5%B0%BE%E8%B0%83%E7%94%A8%E4%BC%98%E5%8C%96%EF%BC%88tail-call-optimization%EF%BC%89/)

**Comment by baskinwind** [comment]
@flyyang 所以这个为调用优化仅仅在 safari 下实现了，node 的环境也没有实现，对吧
