### ISSUE TITLE
WeakMap数据结构的引用计数问题

### ISSUE THREAD

**Issue by cutPicturesMan** [ruanyf/es6tutorial#536]
阮老师，你好

在《Set和Map数据结构》一章的WeakMap章节中，在WeakMap数据结构的键名是对象的情况下，文章说是不计算该对象的引用计数的。但是在文末的WeakMap数据结构的node gc垃圾回收示例的注解中，却将数组形式的键名的引用计数加1了。

请问WeakMap的键名在引用对象的情况下，是否会增加该对象的引用计数？

注意下图绿色箭头：

<img src="http://7xt1tq.com1.z0.glb.clouddn.com/TimLine%E6%88%AA%E5%9B%BE20171102211109.png" />

**Comment by ruanyf** [comment]
谢谢指出，我表达不准确，已经改正了。
