### ISSUE TITLE
chrome还不支持arr.values()吗？

### ISSUE THREAD

**Issue by qiphon** [ruanyf/es6tutorial#539]
for ( var i of [1,2,3,4].values()){console.log(i)}
VM1569:1 Uncaught TypeError: [1,2,3,4].values(...)[Symbol.iterator] is not a function
    at <anonymous>:1:26
这是浏览器的打印结果
版本 60.0.3112.113（正式版本） （64 位）
更新了chrome还是不行，火狐也不行，这是不支持呢吗老师？

**Comment by ruanyf** [comment]
还不支持。
