### ISSUE TITLE
module-loader部分的几个问题

### ISSUE THREAD

**Issue by lhlPersonal** [ruanyf/es6tutorial#542]
阮老师，最近研读module-loader部分时，遇到几个问题。
地址：https://github.com/ruanyf/es6tutorial/blob/gh-pages/docs/module-loader.md

1.基于62版本的chrome，测试“ES6 模块的循环加载”，实际情况会报错，跟babel-node执行的结果不一样。
//b.js
import {foo} from  './a.js';
console.log('b.js');
console.log(foo);  //这句话会直接报错，阻止后面的语句执行。Uncaught ReferenceError: foo is not defined

2. 章节23.5“ES6模块的转码”感觉可以去掉了。这一章节和章节23.1.2“加载规则”有所冲突。而且chrome61、62版本已经支持了ES6模块语法了，在真实环境中去体验应该会更好。

3.章节23.1.1“浏览器加载”部分async和defer的叙述容易造成误解。这两个关键字应该与DOMContentLoaded事件或者兼容事件一起描述。书中说的“渲染完再执行”和“整个页面正常渲染结束”等语句感觉不太准确，因为渲染完成已经是在页面呈现了。严格的说defer应该是DOM下载和解析完成，DOMContentLoaded事件之前执行，async是在DOMContentLoaded之后执行，尽管这一规范在实际中不一定严格遵循。建议阮老师对这一章节重新梳理下，描述的更加准确些，避免造成理解上的混淆。

以上问题和描述，如有不对的地方，请指正和谅解。谢谢。

**Comment by ruanyf** [comment]
谢谢指出。

1、已经修改了示例。
2、这个部分再等一段时间删除，一方面 ES6 模块加载目前还是实验性的，另一方面我觉得读者需要知道有 SystemJS 这个项目，但是怎么介绍我还没想好。
3、已经修改了表述方式。
