### ISSUE TITLE
网页正文靠左，宽屏的要侧着脑袋看

### ISSUE THREAD

**Issue by zkeen** [ruanyf/es6tutorial#547]
日子好了，显示器大了，如今看 http://es6.ruanyifeng.com/#docs/async 的内容要侧着脑袋。好累~

**Comment by ruanyf** [comment]
这个只能等全站改版的时候，再考虑了。

**Comment by xgqfrms** [comment]
![image](https://user-images.githubusercontent.com/7291672/99873931-8bbd1d80-2c1e-11eb-8ac0-c8930c9c29a1.png)

<del>@ruanyf 现在没有改进计划吗？</del>

https://github.com/ruanyf/es6tutorial/issues/865
