### ISSUE TITLE
class.md章节, "__proto__ 并不是语言本身的特性....."

### ISSUE THREAD

**Issue by zhangenming** [ruanyf/es6tutorial#550]
https://www.ecma-international.org/ecma-262/6.0/#sec-__proto__-property-names-in-object-initializers
从ES6.0规范已经提到__proto__了
所以 "__proto__ 并不是语言本身的特性....."
是不是不准确
谢谢

**Comment by ruanyf** [comment]
这一节是在附录里面，不是正文啊。
