### ISSUE TITLE
双冒号运算符是否为过时信息？

### ISSUE THREAD

**Issue by baixiaoyu2997** [ruanyf/es6tutorial#553]
教程中提到的双冒号运算符，并未在[tc39建议](https://github.com/tc39/proposals)中找到，不知道是不是我找的方式不对，如果为过时信息是否应该删除

**Comment by XGHeaven** [comment]
https://github.com/zenparsing/es-function-bind here

**Comment by baixiaoyu2997** [comment]
@XGHeaven  这个是教程中给出的，我看到了，我的理解是16年之后就没提交过，要么是被添加了，要么是被放弃了，在node环境中试验没有被支持，所以我就在想是不是被放弃了？
在Stage 0 Proposals，Finished Proposals，Inactive Proposals中都没有。
还是说我对这个机制理解有误，感谢回复

**Comment by ruanyf** [comment]
还是在 stage 0 里面，“Function bind syntax” 确实两年毫无进展
 https://github.com/tc39/proposals/blob/master/stage-0-proposals.md

**Comment by baixiaoyu2997** [comment]
@ruanyf  非常感谢阮大的回复，原来是我没找到........
