### ISSUE TITLE
WeakMap的例子看能否通过下面的方式演示？

### ISSUE THREAD

**Issue by tomjerry1024** [ruanyf/es6tutorial#554]
const wm = new WeakMap();
let key = {};
let obj = {foo: 1};
wm.set(key, obj);
key = null;
setTimeout(function () {
            console.log(wm);
 }, 10000);

阮老师，您好！
读您的ES6那本书的时候，看到了“WeakMap 的例子很难演示，因为无法观察它里面的引用会自动消失”，我尝试了这种方式，貌似可以演示，不知道书里那句话的意思我理解对了没有。

当setTimeout时间设置为10000毫秒（10秒）时，console.log出来的是“WeakMap {}”，为空。
当setTimeout时间设置为10毫秒时，console.log出来的是“WeakMap {{…} => {…}}”，非空。

**Comment by ruanyf** [comment]
我试了一下，好像打印的还是`WeakMap {{…} => {…}}`。

另外，这个方法像是 Hack，感觉不是那么靠得住。

**Comment by tomjerry1024** [comment]
刚刚又试了下，把时间调成20000（20秒），试了30次左右，只有1次是WeakMap {{…} => {…}}，其它都是WeakMap {}，pc上用的chrome浏览器。调整成2秒后，10次两种输出大约各占一半。可能是不太靠得住，时间要足够长。

**Comment by ruanyf** [comment]
不是时间足够长，而是它取决于垃圾回收（gc）什么时间执行。

如果 gc 30秒不执行，那么就算过了30秒，输出的还是 WeakMap {{…} => {…}}

**Comment by tomjerry1024** [comment]
谢谢阮大的回复~
我的意思是看能不能通过这种方式演示WeakMap的效果，“观察它里面的引用会自动消失”，同时能看到垃圾回收（gc）的执行效果，有时消失、有时不消失正好可以对比。
也可能您书中的意思我理解有误。

**Comment by ruanyf** [comment]
我同意，这样可以演示 WeakMap 的效果。

但是，我有两个顾虑。一是怎么展示 WeakMap，每个浏览器不一样，我甚至觉得不应该通过输出的结果，来判断 WeakMap 包含多少个元素；二是这个例子的结果取决于 gc 的执行时机，但是没有办法手动触发浏览器的 gc，这样就缺乏说服力了，读者完全可以质疑，例子没有生效是由于其他原因。

**Comment by tomjerry1024** [comment]
阮老师考虑周到，感谢细心回复！
