### ISSUE TITLE
【新手】初学中，我干了一件白痴的事， 事后才明白。

### ISSUE THREAD

**Issue by tfciw** [ruanyf/es6tutorial#557]
const按着阮老师的例子去敲，我用的webpack编译的，在console返回的结果与书本不一致，定义之前我也可以引用，不会报错。我就自己咋咋乎乎的去修改了一番，后面才想到我用webpack编译后就不再是es6的语法了。所以把自己的例子po出来给新手看下。

**Comment by ruanyf** [comment]
没看到例子

**Comment by tfciw** [comment]
var tmp = 123;

if (true) {
  tmp = 'tmp' //并没有报错
  console.log(tmp) //'tmp'
  let tmp = 1
  console.log(tmp)//'1'
}
上面这个就是例子了，但是因为编译了，所以才不会报哪些属于es6的错。
【for其他遇到同样问题又想不通的新手】
