### ISSUE TITLE
function.md一章中 展开数组 [...5] 经过测试有误

### ISSUE THREAD

**Issue by mydearxym** [ruanyf/es6tutorial#56]
精彩的教程，非常感谢。
[function.md章节](https://github.com/mydearxym/es6tutorial/blob/gh-pages/docs/function.md)中提到：

扩展运算符还可以将字符串转为真正的数组。

``` javascript
[..."hello"]
// [ "h", "e", "l", "l", "o" ]
```

这里是对的。但是`除了展开数组，扩展运算符还可以将一个数值扩展成数组。`

``` javascript
[...5]
// [0, 1, 2, 3, 4, 5] 
```

实际上得到的却是 [] 

测试使用的 [babel.js](https://babeljs.io/) 将es6 转换成 es5, 并在node下运行。

**Comment by ruanyf** [comment]
已删除该内容。
