### ISSUE TITLE
import（）

### ISSUE THREAD

**Issue by transient-ad** [ruanyf/es6tutorial#562]
前辈你好:
    在module语法章节中，import（）函数 我在.babelrc中添加了
{
    "presets": [
        "env",
        "stage-3"
    ],
    "plugins": ["syntax-dynamic-import"]
}

因为此import（）是在stage3中才有的，以及转换import（）所必须的插件syntax-dynamic-import
但是我现在用babel转换的时候   还是无法转换成功   我想知道原因。。？
是不是一定要配合webpack  才能使用此 import（）函数？

**Comment by ruanyf** [comment]
`syntax-dynamic-import`的问题，我不是很清楚。你可以不用这个插件，因为 Webpack 默认支持`import()`。https://github.com/webpack/webpack/issues/3098
