### ISSUE TITLE
关于generator的异步控制问题

### ISSUE THREAD

**Issue by miracle9312** [ruanyf/es6tutorial#563]
阮老师您好，关于异步控制我有个小问题，一下是您书上的一个示例
`function* loadUI() {
  showLoadingScreen();
  yield loadUIDataAsynchronously();
  hideLoadingScreen();
}
var loader = loadUI();
// 加载UI
loader.next()

// 卸载UI
loader.next()`
我对这段实例的理解是，loadUIDataAsynchronously()是个异步执行函数，经过yield操作后执行顺序变为showLoadingScreen()->loadUIDataAsynchronously()->hideLoadingScreen().
模仿您的示例我自己写了一个
`function* geneAsync() {
    console.log(1);
    yield setTimeout(function(){
        console.log(2)
    }, 1000);
    console.log(3)
}

var geneAsyncObj = geneAsync();
geneAsyncObj.next();
geneAsyncObj.next();`
结果输出是1，3，2。
好像并没有把异步操作变成同步的效果啊~~

**Comment by ruanyf** [comment]
书里的例子是说，要等到 UI 使用完成后，再卸载 UI，不是连在一起执行。
