### ISSUE TITLE
关于global 对象的，一个地方没看明白

### ISSUE THREAD

**Issue by zzlw** [ruanyf/es6tutorial#564]
<img width="762" alt="wx20171216-211416 2x" src="https://user-images.githubusercontent.com/29618863/34070729-5b585a52-e2a6-11e7-82ca-bffe5c0d7007.png">

**Comment by ruanyf** [comment]
Node 没有 `self` 对象。

另外，我不姓软。

**Comment by zzlw** [comment]
So sorry！
第二行 window != 'undefined' 有什么意义，node中没有 window 的

**Comment by ruanyf** [comment]
第二行针对浏览器，如果存在`window`，就返回`window`。

**Comment by zzlw** [comment]
问题在于浏览器中也存在 self ，第二行会执行到吗？

**Comment by jinyang1994** [comment]
这个函数的意义在于获取顶层对象，`self === window`，当有self的时候，其实window那句执不执行已经不重要了。

**Comment by zzlw** [comment]
我说的就是 window 那句根本执行不到啊

**Comment by ruanyf** [comment]
确实浏览器不会执行到第二句，写在这里只是为了完备。
