### ISSUE TITLE
Symbol.species 例子陈述问题

### ISSUE THREAD

**Issue by WeipingChen** [ruanyf/es6tutorial#566]
面代码中，a是MyArray的实例，所以a instanceof MyArray返回true。
**由于构造函数被替换成了Array，所以a实际上也是Array的实例，于是a instanceof Array也返回true。**
而mapped是Array.prototype.map运算的结果，已经是真正的数组，它是Array的实例，而不是MyArray的实例，于是mapped instanceof Array返回true，而mapped instanceof MyArray返回false

a instanceof Array 返回true  应该是因为  MyArray extends Array 的结果 而不是因为 重载
 static get [Symbol.species]() { return Array; } 这个get函数的结果  
我在控制台中测试下面的代码
class MyArray {
  static get [Symbol.species]() { return Array; }
}
let a = new MyArray(1,2,3);

console.log(a instanceof MyArray) // false
console.log(a instanceof Array) // true

class MyArray1 extends Array{
}
let b = new MyArray1(1,2,3);

console.log(b instanceof MyArray1) // true
console.log(b instanceof Array) // true

**Comment by ruanyf** [comment]
谢谢指出，原来的解释是错的。

我已经重写这一节了。请看 commit https://github.com/ruanyf/es6tutorial/commit/649b29779a33f291b70de3bd765a5ce9330b28df
