### ISSUE TITLE
正则扩展——使用了y修饰符的正则的split方法的例子有问题

### ISSUE THREAD

**Issue by picc-lu** [ruanyf/es6tutorial#570]
**'#x#'.split(/#/y)**
### 预计结果：
// [ '', 'x#' ]
### 实际运行结果：
// [ '', 'x', '' ]

在Chrome 63的环境下运行。

**Comment by ruanyf** [comment]
谢谢指出，看来`split`方法不支持`y`修饰符，以前是支持的。我把这一段删了。
