### ISSUE TITLE
有错误，object#对象的扩展运算符

### ISSUE THREAD

**Issue by iDerekLi** [ruanyf/es6tutorial#576]
下面是另一个例子。
const o = Object.create({ x: 1, y: 2 });
o.z = 3;

let { x, ...{ y, z } } = o;
x // 1
y // undefined
z // 3
上面代码中，变量x是单纯的解构赋值，所以可以读取对象o继承的属性；变量y和z是扩展运算符的解构赋值，只能读取对象o自身的属性，所以变量z可以赋值成功，变量y取不到值。

**Comment by HowardTangOvO** [comment]
在这一章节开头已经说明`ES2017 将这个运算符引入了对象。`
需要经过babel编译以后才能使用.要使用es2017的preset
https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYewdgzgLgBCMF4YHkBGArApsKA6YATpgIZSYAUA3jAB4BcMAjADQwCeDATDAL4CUAbgBQIXAC9EMAMzChAG0yxqNVrjXU2rCT16SQwmjAD0RpkLbHTAVzAATTADMAlmEy2hEk9KA&debug=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=es2015%2Ces2017%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0

**Comment by ruanyf** [comment]
这个例子只是说明扩展运算符的语法，不涉及如何才能让它生效。
