### ISSUE TITLE
字符串码点

### ISSUE THREAD

**Issue by dajunJS** [ruanyf/es6tutorial#579]
阮老师好
在字符串扩展章节
let s = '吉a';
我在mac机chrome62.0.3202.89浏览器运行s.codePointAt(1)等于97,
运行s.charCodeAt(1) 也等于97.
发现跟老师运行不一样

**Comment by picc-lu** [comment]
let s = '\u{20BB7}a';
运行这句语句才可以，因为那个Unicode字符和“吉”长得很像。

**Comment by ruanyf** [comment]
我的例子不好，那个字太像吉祥的吉。实际上，上半部分不是士，而是土。
