### ISSUE TITLE
双冒号（::）运算的结果一定是对象吗？如果不是，此处表述有误，容易误解

### ISSUE THREAD

**Issue by HarryPoint** [ruanyf/es6tutorial#580]
双冒号运算符的运算结果，还是一个对象，因此可以采用链式写法。

是否应该改为“如果双冒号运算符的运算结果，还是一个对象，可以采用链式写法。”

**Comment by ruanyf** [comment]
根据草案，返回的应该还是一个函数，与`bind`方法类似。

**Comment by HarryPoint** [comment]
那书中描述就应该有问题了 “双冒号运算符的运算结果，还是一个对象，因此可以采用链式写法”
应该是一个函数， 但这个函数执行的结果如果是对象， 则可以采用链式写法

**Comment by ruanyf** [comment]
谢谢指出，这里是笔误，我把它改过来。
