### ISSUE TITLE
Module import 易引起误导

### ISSUE THREAD

**Issue by 8rV1n** [ruanyf/es6tutorial#584]
在20.4一节中（module 的语法/import 命令），  
对示例代码：  
```javascript
// main.js
import {firstName, lastName, year} from './profile';

function setName(element) {
  element.textContent = firstName + ' ' + lastName;
}
```
导入模块的JS文件为`./profile`，而对其下文所述文字：  
> 上面代码的import命令，用于加载profile.js文件，并从中输入变量。import命令接受一对大括号，里面指定要从其他模块导入的变量名。大括号里面的变量名，必须与被导入模块（profile.js）对外接口的名称相同。  

解释到：导入模块的文件为`profile.js`。  
在实际使用中应该导入的文件和`from`关键字后的描述一致，即：  
若要导入`profile.js`文件，应到这样写：  
```javascript
import {firstName, lastName, year} from './profile.js';
```
在`from`关键字后，应到编写的导入文件为`./profile.js`而不是原示例代码中所述的`./profile`

**Comment by ruanyf** [comment]
运行时（Runtime）都会自动添加脚本文件后缀名。

所以，`from './profile'` 和 `from './profile.js'` 都是有效的。

**Comment by 8rV1n** [comment]
实践时，没有添加任何其他依赖，直接采用ES6在Chrome 63, Edge 41.16299.15.0,Safari IOS 11上，均不会自动添加脚本文件后缀名。

**Comment by ruanyf** [comment]
确实浏览器不会自动加后缀名，我已经加上后缀名了。
