### ISSUE TITLE
Generator 小节中 Generator与状态机 （http://es6.ruanyifeng.com/#docs/generator）

### ISSUE THREAD

**Issue by ghost** [ruanyf/es6tutorial#586]
Generator 小节中 Generator与状态机 （http://es6.ruanyifeng.com/#docs/generator）
var clock = function* () {
  while (true) {
    console.log('Tick!');
    yield;
    console.log('Tock!');
    yield;
  }
};  
个人感觉下面应该注释一下这个函数的用法 ,可能会给读者困惑（  我最初的用法是这样的 clock.next()  ）但正确但用法是这个样子的；
clock().next()  // Tick
clock().next()  // Tock
clock().next()  // Tick
----------------------------------------------------------
es6 标准入门书中  （第二版）
var clock = function* (_) {
  while(true) {
  yield _;
  console.log("Tick!")
  yield _;
  console.log("Tock!")
  }
} 
个人感觉这个写法是不对的

**Comment by picc-lu** [comment]
下划线是合法的关键字，调用的时候可以写成clock( new Date() ).next()之类的。

**Comment by ghost** [comment]
关闭问题
