### ISSUE TITLE
Symbol小节，Symbol.species的描述

### ISSUE THREAD

**Issue by dxhbiz** [ruanyf/es6tutorial#587]
https://github.com/ruanyf/es6tutorial/blob/gh-pages/docs/symbol.md#symbolspecies
Symbol小节
对象的Symbol.species属性，指向一个构造函数。**创建造衍生对象时**，会使用该属性。

这个描述是否有笔误？

**Comment by ruanyf** [comment]
谢谢指出，应该是“创建”，已经改正了。
