### ISSUE TITLE
便利性功能

### ISSUE THREAD

**Issue by 605666069** [ruanyf/es6tutorial#589]
希望可以增加一个缓存功能，可以每次进入页面进入到最后退出的页面，不然每次都需要找上次学习的地方

**Comment by ruanyf** [comment]
现在就支持的。

https://github.com/ruanyf/es6tutorial/blob/gh-pages/js/ditto.js#L14

**Comment by ruanyf** [comment]
不过，你得自己进入上一次的页面。
