### ISSUE TITLE
Import is read-only 

### ISSUE THREAD

**Issue by magicds** [ruanyf/es6tutorial#595]
```js
export let a = {};
```

```js
import {a} form 'xxx.js'

a = {}; // Syntax Error : 'a' is read-only
```

我在[http://exploringjs.com/es6/...](http://exploringjs.com/es6/... 中找到了 **Imports are read-only views on exports** 的说明，而在此文中没有涉及到， 是否会在 `/docs/module.md` 中进行补充？

**Comment by ruanyf** [comment]
谢谢指出，已经加上。
