### ISSUE TITLE
类的实例属性部分代码在chrome浏览器报错

### ISSUE THREAD

**Issue by dashi3869** [ruanyf/es6tutorial#596]
class MyClass {
  myProp = 42;

  constructor() {
    console.log(this.myProp); // 42
  }
}

class MyClass {
  static myStaticProp = 42;

  constructor() {
    console.log(MyClass.myStaticProp); // 42
  }
}

提示这个错误 Uncaught SyntaxError: Unexpected token = ？？？ 为什么？？

**Comment by picc-lu** [comment]
https://github.com/tc39/proposal-class-public-fields
此提案还停留在Stage-2，未被广泛支持！

**Comment by ruanyf** [comment]
这个语法只是提案， 要用 Babel 转码。

https://babeljs.io/docs/plugins/transform-class-properties/
