### ISSUE TITLE
Symbol部分中，6.实例：模块的Singleton模式    全局变量global._foo是可写的，作为例子是不是应改为global._foo.foo是可写的更清楚明了呢？

### ISSUE THREAD

**Issue by chenjia001** [ruanyf/es6tutorial#597]
全局变量global._foo是可写的，作为例子是不是应改为global._foo.foo是可写的更清楚明了呢？
因为按照例子运行，并没有改变。

const a = require('./mod.js');
global._foo = 123;
console.log(a.foo);  //hello
因为并没有改变global._foo.foo 的值。改成：

const a = require('./mod.js');
global._foo.foo = 123;
console.log(a.foo);  //123

这样容易理解吧！还是我理解错了呢？

**Comment by ruanyf** [comment]
谢谢指出，我改了一下例子，现在没有问题了。
