### ISSUE TITLE
例子貌似有问题

### ISSUE THREAD

**Issue by khflx** [ruanyf/es6tutorial#600]
阮兄, 你在描述
<Generator函数>章节中的
“Generator函数的 this” 时例子貌似有误
`function* g() {
this.a = 11;
}
let obj = g();
obj.a // undefined`
你想用这个例子来表明Generator函数的this, 但是你这里只是返回一个遍历器而没有执行

**Comment by ruanyf** [comment]
谢谢指出，已经加上了`obj.next()`。
