### ISSUE TITLE
阮老师，很高兴认识您，请多多指教！

### ISSUE THREAD

**Issue by JasonHuang3D** [ruanyf/es6tutorial#601]
我们在用c++来实现一套自己的flash player runtime，保留其强大的API功能，并能以wasm的方式运行在浏览器中，现已完成了基础部分。目的是让强大的flash API能继续运行在浏览器上使用wasm而不依赖flash player，同时支持JS/ TS以及原有AS3这些脚本语言在上层无缝运行，当然这套API也同时能在c++层使用当作一个跨平台底层（所有原生端，和wasm），大幅度提高c++前端开发的敏捷性。我们通过半年重构了embind以及编写了大量脚本层编译器和工具，渲染用的OpenGL（OpenGL3.0/4.0，提及gles2/es3），根据编译平台对应的各filesystem，IO等等（当编译wasm时，emsdk里实现了很多c++层的API映射，然后通过libXXX.js实现在c++层extern的回调，为了还原flash api，我们自己也做了很多libs）目前已经能将AS3和JS跑在我们这个wasm的runtime了，其功能和开发便利性和之前的flash player一样。这个是我们的github的 demo。readme里面有几个demo，原生c++ exe，c++ wasm, as3 js wam. 
我们目前打算完善其API，并在18年4月开始制作一款3D全目标引擎基于这套API以及其工具层。我们现在在大量募集志同道合的国人兄弟们，咱们一起做一个国人自己的前沿平台，让这块领域不再是鬼佬的专利。我们现在资金充裕，是在一家国内大公司下的实验室，各方面都很稳定。我的Q:616267056，希望能得到你的注意！希望您能帮我们引荐一下国内牛人，感谢万分！
https://github.com/JasonHuang3D/AJC-Flash-WebAssembly-Examples/

**Comment by ruanyf** [comment]
项目很棒啊，已经回信了。

**Comment by xoxong** [comment]
很厉害的样子

**Comment by LongTengDao** [comment]
@JasonHuang3D 

>   咱们一起做一个国人自己的前沿平台，让这块领域不再是鬼佬的专利。

>   https://github.com/JasonHuang3D/AJC-Flash-WebAssembly-Examples/

点到链接中发现项目是英文的……？
