### ISSUE TITLE
阮老师，希望您能帮我解惑，谢谢

### ISSUE THREAD

**Issue by steady-join** [ruanyf/es6tutorial#603]
当我使用Proxy.defineProperty 与 Reflect.defineProperty 搭配时添加属性及描述，并不能按照理想的结果实现，当我在Proxy.defineProperty => return true并不能添加，以下是我的代码：
let obj = {
		name : 'author',
		age : 1
	}
	
	let handler = {
		defineProperty(target,key,desc){

			console.log(target,key,desc)
			console.log('-----------')

			return true
		}
	}
	let proxy = new Proxy(obj,handler)

	proxy.sex = '男'

	Object.defineProperty(proxy,'sex',{
		value : '男'
	})

	Reflect.defineProperty(proxy,'now',{
		value : () => Date.now()
	});

	console.log(proxy,obj)

**Comment by ruanyf** [comment]
返回 true 只是表示不抛出错误。真正的赋值要写在 defineProperty 方法里面。

```
let handler = {
	defineProperty(target,key,desc){

		console.log(target,key,desc)
		console.log('-----------')

		return Reflect.defineProperty(target, key, desc);
	}
}
```
