### ISSUE TITLE
Set内部0和-0是相等的，判断方法应该是same-value-zero equality

### ISSUE THREAD

**Issue by wangller** [ruanyf/es6tutorial#604]
**Same-value-zero equality**: Similar to same-value equality, but considered +0 and -0 equal.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness

测试：Set内部0和-0是相等的，并不是same-value equality
```js
new Set([NaN, NaN, 0, -0])
// Set {NaN, 0}
```

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
