### ISSUE TITLE
Null 传导运算符翻译是否准确

### ISSUE THREAD

**Issue by yuu2lee4** [ruanyf/es6tutorial#613]
Optional Chaining我看网上有翻译为 `自判断链接`  或 `可选链`

**Comment by ruanyf** [comment]
说得有道理。但是，你的那两个翻译，我觉得都不够直观。

我再想想怎么翻译比较好，也看看其他人怎么称呼这个运算符，先不急着改。毕竟，早期的讨论（[1](https://esdiscuss.org/topic/existential-operator-null-propagation-operator), [2](https://docs.google.com/presentation/d/11O_wIBBbZgE1bMVRJI8kGnmC6dWCBOwutbN9SWOK0fU/edit#slide=id.p)）都将其称为“null 传导运算符”。

**Comment by ruanyf** [comment]
链判断运算符 或者 链式判断运算符？
