### ISSUE TITLE
如果所有 Map 的键都是字符串，它可以转为对象，这个解释有问题。

### ISSUE THREAD

**Issue by fzysdsj** [ruanyf/es6tutorial#614]
我觉得，这句话说得有问题，并不是当所有Map的键都是字符串时，它才可以转为对象（因为不是字符串时，也可以转换，只是键名变成了字符串），所以，应该这样说，当Map转化为对象时，不论它的键名是什么，都会变为字符串。

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
