### ISSUE TITLE
page 17: let实际上为JavaScript新增了块级作用域。

### ISSUE THREAD

**Issue by ghost** [ruanyf/es6tutorial#62]
是不是表述有误?
比如：
for(var i  = 0;i< 10;i++){
    let c  = i;
}
将let声明换成var声明，此时，不是每一次for循环都还是会创建一个块级作用域吗？
所以说，let实际上为javascript新增了块级作用域 这种说法是不是不太正确。

**Comment by ruanyf** [comment]
块级作用域指变量在作用域外不存在，var明显不是。
