### ISSUE TITLE
阮老师， 经过检验， 这里好像是错误的

### ISSUE THREAD

**Issue by Evoque** [ruanyf/es6tutorial#622]
18章 async 函数 的  "异步Generator函数"小节 中 有个例子:
``` javascript
async function* asyncGenerator() {
  console.log('Start');
  const result = await doSomethingAsync(); // (A)
  yield 'Result: '+ result; // (B)
  console.log('Done');
}

const ag = asyncGenerator();
ag.next().then({value, done} => {
  // ...
})
```

下面对代码的执行顺序的第2条应该是错误的，原文：

> `await`命令返回一个Promise对象，但是程序不会停在这里，继续往下执行.

经过测试， 应该是`await`会等到它后面的Promise对象`resolve`之后，得到`value`之后再继续往下执行。也就是说程序暂时不会执行 `await`之后的语句。

**Comment by windyKite** [comment]
阮老师，您好。第14章中，对于Promise对象的特点描述中，
> 只有异步操作的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。

是不是笔误了？我在Chrome的控制台中，测试过以下代码。发现在构造Promise对象的过程中，即使异步函数没有执行，依然可以直接改变 Promise 对象的状态。
```javascript
console.log('构造Promise对象前')
let promise = new Promise(function(resolve,reject){
  resolve()   // 此时改变 promise 对象的状态，而setTimeout操作还没有结果
  setTimeout(()=>{
    console.log('5秒后打出这句话')
  },5000)
})
console.log('Promise对象')
console.log(promise)
console.log('构造Promise对象后')
```
也就是说，Promise对象的状态可以在生成实例的时候就指定，不知道这样说，对不对。如果阮老师您有空的话，麻烦指点一下。谢谢您

**Comment by Evoque** [comment]
@windyKite 你Promise的基本用法没理解， 在构造函数内， 任何地方调用`resolve()`都会改变promise的状态， 不论正常调用，还是异步调用。 
另： 自己开个Issue不行？

**Comment by ghost** [comment]
错的改过来就还是对的

**Comment by ruanyf** [comment]
@Evoque 谢谢指出，原来的解释是错的，已经改过来了。
