### ISSUE TITLE
关于promise和generate结合的那个例子的解释

### ISSUE THREAD

**Issue by jialigit** [ruanyf/es6tutorial#627]
在promise.doc 中关于promise和generator结合的例子：
function getFoo () {
  return new Promise(function (resolve, reject){
    resolve('foo');
  });
}

const g = function* () {
  try {
    const foo = yield getFoo();
    console.log(foo);
  } catch (e) {
    console.log(e);
  }
};

function run (generator) {
  const it = generator();

  function go(result) {
    console.log("result: " + result);
    if (result.done) {
      console.log("done" + result);
      return result.value;
    }

    return result.value.then(function (value) {
      console.log("value: " + value);
      return go(it.next(value));
    }, function (error) {
      return go(it.throw(error));
    });
  }

  go(it.next());
}

run(g);

-----------------------------------这是分割线------------------------------
中，run函数的go方法体中：
 function go(result) {
    console.log("result: " + result);
    if (result.done) {
      console.log("done" + result);
      return result.value;
    }

    return result.value.then(function (value) {
      console.log("value: " + value);
      return go(it.next(value));
    }, function (error) {
      return go(it.throw(error));
    });
  }

的参数result.done, result.value是什么？有点不明白，可否加上一些解释的内容？

**Comment by ruanyf** [comment]
next 方法返回的是一个 Iterator 对象，value 和 done 都是 Iterator 的属性，你可以参考 Iterator 那一章。
