### ISSUE TITLE
[建议]关于 Math.trunc 和 Number.parseInt

### ISSUE THREAD

**Issue by undeadway** [ruanyf/es6tutorial#631]
阮老师是不是能在书中添加一些关于 `Math.trunc` 和 `Number.parseInt` 之间的异同的内容呢？
比如
```
Math.trunc("6x"); // NaN
Number.parseInt("6x"); // 6
```
又比如
```
Number.parseInt(6.022e23); // 6
Math.trunc(6.022e23); // 6.022e+23
```

**Comment by ruanyf** [comment]
`Number.parseInt`用于将字符串转为数值，参数会自动转为字符串。

理解了这一点，就很容易理解上面的现象了。

**Comment by undeadway** [comment]
嗯，阮老师是不是理解错我的意思了？
我并不是说 `Number.parseInt`会将字符串转成数字什么的。我的第一个例子中，两个地方用的参数都是字符串，先决条件可以说是一致的。
想要表达的是，`Number.parseInt`是截取到第一个**非数字符号**，但不判断输入参数是否是**纯数字**，而`Math.trunc`是**数学角度的取整**，并且会实现判断输入参数是否是**纯数字**，如果不是纯数字，则返回`NaN`。

**Comment by ruanyf** [comment]
不是这样的。

`Number.parseInt`的参数默认转成字符串，`Math.trunc`的参数默认转成数值。

```javascript
Math.trunc(Number("6x")); // NaN
Number.parseInt(String("6x")); // 6
```

实际上，内部是上面这样的算法。

**Comment by undeadway** [comment]
哦，那是我理解错了，谢谢。
