### ISSUE TITLE
数组的扩展第5小节例子有问题

### ISSUE THREAD

**Issue by zhangxuexia** [ruanyf/es6tutorial#641]
let arrayLike = {
  '0': 'a',
  '1': 'b',
  '2': 'c',
  length: 3
};

// TypeError: Cannot spread non-iterable object.
let arr = [...arrayLike];
这个例子是可以执行的，结合第15章内容（存在数值键名和length属性的对象都可以用扩展运算符）

**Comment by xianshenglu** [comment]
![image](https://user-images.githubusercontent.com/23273077/38479327-f1e52fe2-3bf0-11e8-8553-195235c18e8d.png)

**Comment by xianshenglu** [comment]
`对于那些没有部署 Iterator 接口的类似数组的对象，扩展运算符就无法将其转为真正的数组。`

**Comment by ruanyf** [comment]
Chrome 浏览器会报错，扩展运算符转成对象可以，不能转成数组。

**Comment by zhangxuexia** [comment]
感谢及时处理，刚试了一下，在纯静态页面运行，确实会报错误，上午是在react环境和vue环境中运行是可以正确转成数组的。可能这些前端框架内部进行处理了？

**Comment by zhangxuexia** [comment]
![image](https://user-images.githubusercontent.com/36907948/38481323-acfa7e76-3bfc-11e8-8d04-9c5008e996b9.png)

**Comment by Dcatfly** [comment]
@zhangxuexia 是babel做的处理。。如果不是array会调用Array.from
