### ISSUE TITLE
在书中,第三章节变量的解构赋值,这段应该是不等于undefined吧.不知道理解的对不对

### ISSUE THREAD

**Issue by WanDa1993** [ruanyf/es6tutorial#644]
![image](https://user-images.githubusercontent.com/16666953/38532725-b40151ac-3ca8-11e8-8fa1-56d2720ea586.png)

**Comment by ruanyf** [comment]
就是`x属性的值 === undefined`。

**Comment by WanDa1993** [comment]
明白了,理解反了.
