### ISSUE TITLE
阮老师，想请教一下，async结合promise如何等待所有请求都结束，才执行回调，无论中间谁的请求失败或者成功

### ISSUE THREAD

**Issue by Yan2603** [ruanyf/es6tutorial#645]
如书中代码
```
async function dbFuc(db) {
  let docs = [{}, {}, {}];
  let promises = docs.map((doc) => db.post(doc));

  let results = await Promise.all(promises);
  console.log(results);
}
```
Promise.all是所有的promise都resolve才执行回调，或者其中有一个reject就执行回调，我想等所有的promise都执行完才执行回调，哪怕中间有reject的promise
![promise](https://user-images.githubusercontent.com/8750185/38775467-e2cf86b4-40b5-11e8-89ab-1f9a2351c71c.png)

**Comment by xianshenglu** [comment]
你给可能会出错的加上 `.catch` 或者都放入 `try catch ` 中，这样就可以了

**Comment by xianshenglu** [comment]
例子：
```
async function dbFuc(db) {
  let p1 = new Promise(function(resolve, reject) {
    setTimeout(() => {
      reject('rejected')
      console.log('rejected done')
    }, 1000)
  }).catch(e => 'error catched')//可能reject的代码

  let p2 = new Promise(function(resolve, reject) {
    setTimeout(() => {
      resolve('resolved')
      console.log('resolved done')
    }, 2000)
  })
  let promises = [p1, p2]
  return await Promise.all(promises)
  // console.log(results)
}

dbFuc()
  .then(data => console.log('success', data))
  .catch(e => console.log('error:', e))

```

**Comment by xianshenglu** [comment]
另，你提的这个是 `ES6` 的问题，不是这本书的问题，阮老师没有义务回答你吧，这种问题应该去 Stackoverflow 或 [segmentfault](https://segmentfault.com/t/javascript/questions) ，从提问角度来看，你最好补充上你尝试了什么以及尝试中遇到了什么问题，否则，你是在提需求，不是在提问题，你可以自己读读看，是不是这样子 

>Promise.all是所有的promise都resolve才执行回调，或者其中有一个reject就执行回调，我想等所有的promise都执行完才执行回调，哪怕中间有reject的promise

**Comment by Yan2603** [comment]
@xianshenglu 
我是看这里引发的问题[http://es6.ruanyifeng.com/#docs/async](http://es6.ruanyifeng.com/#docs/async)

**Comment by Yan2603** [comment]
@xianshenglu 你给可能会出错的加上 .catch 或者都放入 try catch 中，这样就可以了
这样子确实可以，感谢，又去看了下[http://es6.ruanyifeng.com/#docs/promise#Promise-all](http://es6.ruanyifeng.com/#docs/promise#Promise-all)

**Comment by STLighter** [comment]
我理解你的需求可能是要这样请求:
```
docs.map((doc) => db.post(doc).then(null, reason => reason));
```
这样相当于把错误返回错误也当成成功的结果返回。
之所以一个reject就返回是因为只要reject的时候都不会再去执行返回，而是抛出异常(或者说是promise.all返回的那个promise都会走reject方法，而不是resolve

**Comment by STLighter** [comment]
```docs.map((doc) => db.post(doc).then(null,err=>err));```

**Comment by ruanyf** [comment]
我觉得，上面@xianshenglu @STLighter 的解法应该就是你要的。

一句话，就是把返回值包装一下， 让 reject 的结果转成 resolve 再返回。

**Comment by Yan2603** [comment]
是的， @ruanyf 感谢几位大牛

**Comment by YanmaY** [comment]
### 
## ****
