### ISSUE TITLE
http://es6.ruanyifeng.com/#docs/symbol

### ISSUE THREAD

**Issue by zhangenming** [ruanyf/es6tutorial#647]
function getComplement(color) {
  switch (color) {
    case COLOR_RED:
      return COLOR_GREEN;
    case COLOR_GREEN:
      return COLOR_RED;
    default:
      throw new Error('Undefined color');
    }
}

此处switch的break应该是忘记加了吧

**Comment by leoyli** [comment]
不是忘了是不用...因為都用 `return` 收尾了

**Comment by ruanyf** [comment]
return 就直接返回了，不需要写 break 了。
