### ISSUE TITLE
关于数组空位表示的一些建议

### ISSUE THREAD

**Issue by STLighter** [ruanyf/es6tutorial#650]
在[Array](https://github.com/davi0723/es6tutorial/blob/gh-pages/docs/array.md)章节中数组的空位采用`[, , ,]`这样的表达方式, 看起来可能会产生误解.
在较新版本的chrome中空位采用`[empty x 3]`, `[empty, 1, "2", empty]`这样的表示方式, 个人觉得放在书中表达更加清晰, 建议在数组空位的表示上做一些调整.

**Comment by ruanyf** [comment]
`[empty x 3]` 只是输出，不能输入。直接输入这种写法，会报错。

`[, , ,]`是通用写法，浏览器和 Node 都能解析，所以输入部分不用改，输出部分可以改得更清楚一点。
