### ISSUE TITLE
Promise catch reject 后，Promise的状态会被更新为 resolved？

### ISSUE THREAD

**Issue by Shurlormes** [ruanyf/es6tutorial#651]
```
const rejected = new Promise(
	(resolve, reject) => {
		reject(new Error('Error...'))
	}
).catch(error => console.log(error));

const rejected2 = new Promise(
	(resolve, reject) => {
		reject(new Error('Error...'))
	}
).then(result => console.log(result));

setTimeout(() => {
	console.log(rejected);
	console.log(rejected2);
}, 1000);
```

如上述代码
第一个Promise catch了 Reject，1秒后输出对象，发现状态被更新为了resolved。
第二个Promise 没有catch，状态被更新为 rejected。

主要的疑惑点是：Promise catch 了 Reject被更新为resolved，这样不方便后续的判断吧？这是正常的吗？

另外还有个问题，就是resolved 输出的对象中，PromiseValue是 undefined。
![z7 r4 v5y 5twype2 rnm](https://user-images.githubusercontent.com/22904862/39352985-fdcbd788-4a38-11e8-9325-6d3038550ef5.png)

**Comment by Shurlormes** [comment]
重新看了一遍书，then方法返回的是一个新的Promise实例。

**Comment by xianshenglu** [comment]
> Promise catch 了 Reject被更新为resolved，这样不方便后续的判断吧？这是正常的吗？

没问题，方便后面继续调用处理函数啊，后续判断很容易的；

> 另外还有个问题，就是resolved 输出的对象中，PromiseValue是 undefined。

因为你没有 `return value`，改成下面这样就 OK 了

```
const rejected = new Promise((resolve, reject) => {
  reject(new Error('Error...'))
}).catch(error => {
  console.log('err', error)
  return error // new added
})

const rejected2 = new Promise((resolve, reject) => {
  reject(new Error('Error...'))
}).then(result => console.log('res', result))

setTimeout(() => {
  console.log(rejected)
  rejected2
}, 1000)

```

**Comment by xianshenglu** [comment]
![image](https://user-images.githubusercontent.com/23273077/39354482-3bb26b12-4a3d-11e8-8ada-e386992038dd.png)
