### ISSUE TITLE
20.1 简介 表述错误

### ISSUE THREAD

**Issue by Albert-Tao** [ruanyf/es6tutorial#657]
原文：

子类必须在constructor方法中调用super方法，否则新建实例时会报错。这是因为子类没有自己的this对象，而是继承父类的this对象，然后对其进行加工。如果不调用super方法，子类就得不到this对象。

问题：

子类是有自己的this，调用父类的原因不是继承this，而是**借用父类的构造函数按照父类的规格，初始化自己的this，得到和父类同样的实例属性**，**this不存在继承关系**。父类的实例属性是实例自身的，不会被继承，自己父类原型上的属性能被子类实例继承（实际只是发生属性查找，并不会拥有）。之后才开始增加自己独有的实例属性，或者覆写（override）父类的实例属性。

**Comment by ruanyf** [comment]
谢谢指出，你的解释是正确的，我已经改过来了。

**Comment by Albert-Tao** [comment]
其实我看到后面发现，加上自己试验发现直接new调用子类的构造器会报ReferenceError，按照《你不知道的JavaScript》对ReferenceError错误的说法，说明所有的作用域此时都不能找到子类构造器中的this，也就说，不调用父类构造器（super()）就不会创建子类的this。这有点类似于C++或Java中继承构造对象的过程，先构造父类对象，然后构造子类对象，依次调用构造器链进行初始化。我不知道规范是不是这么规定JavaScript实现的，这个只是个人理解。感觉class语法更像这些语言靠近了。

**Comment by STLighter** [comment]
@Albert-Tao  规范中`super关键字`一节对`super()`的行为有规定: https://tc39.github.io/ecma262/#sec-super-keyword
简单的说就是先调用父构造函数, 然后将返回的对象绑定为当前环境的this.

**Comment by STLighter** [comment]
大致翻阅了一下规范相关的内容, 目前知道的内容:

1. `extends`关键字会使得构造函数的`[[ConstructorKind]]`从默认的`"base"`变成`"derived"`
2. 执行构造函数前会检查`[[ConstructorKind]]`, 如果是`"base"`才会依据`newTarget`创建新对象, 并绑定到构造函数执行上下文的`this`
3. `super()`会获取当前`newTarget`(`new`直接调用的构造函数`newTarget`为构造函数对象自身), 并将此`newTarget`传入, 去执行父类的构造函数(这样保证父类构造函数得到的`newTarget`是`new`直接调用的那个构造函数, 这样创建对象的`__proto__`才正确). 父类构造函数返回的对象绑定到`this`

由于`1`和`2`导致子类的构造函数在调用`super()`前没有绑定`this`, 直到`super()`依次找到最终的那个基类构造函数, 此函数的`[[ConstructorKind]]`为`"base"`, 这才创建了新对象, 并绑定到当前上下文`this`

**Comment by Albert-Tao** [comment]
@STLighter 感谢指导！感觉过程有些复杂，不过大致功能上差不多，不理解实际的实现过程，应该也不会误用。

**Comment by STLighter** [comment]
@Albert-Tao 我也是看到你的问题才去了解相关细节的。
不过总得看来，实例是基类构造函数基于派生类原型创建的，然后再绑定到派生类的this。
也就是说，原文的说法并没有错，只是有歧义的。原文的“继承“可能并不是指面向对象中的“继承“，而是“继承我的蚂蚁花呗”的那种“继承”

**Comment by Albert-Tao** [comment]
@STLighter 同意你的观点，我也是看到后文才知道，再说，JavaScript本来就没有实现经典继承。ES6只是慢慢靠近这些经典的语言，而且就结果而已，class语法不能单纯看作语法糖，因为它实现了ES5中做不到的事情。我也是只刚学ES6，而且刚刚入门前端，现在还在纠结DOM。STLighter是前端专业人士？
