### ISSUE TITLE
BigInt 存在隐式转换

### ISSUE THREAD

**Issue by islishude** [ruanyf/es6tutorial#658]
>相等运算符（==）会改变数据类型，也是不允许混合使用。
0n == 0
// 报错 TypeError
0n == false
// 报错 TypeError

上述描述有问题，原文链接：http://es6.ruanyifeng.com/#docs/proposals#%E8%BF%90%E7%AE%97

在 chrome canary 68 中上述并不报错。

<img width="333" alt="2018-05-01 10 22 05" src="https://user-images.githubusercontent.com/24730006/39458763-86d65c4a-4d29-11e8-9ed2-4dfe6b7b1459.png">

**Comment by STLighter** [comment]
根据提案内容`==`是允许类型混用的，可以看 https://github.com/tc39/proposal-bigint#no-implicit-conversions-or-mixed-operands 最后一段。

**Comment by ruanyf** [comment]
谢谢指出，已经更正。我补充一些内容，一会就发布。
