### ISSUE TITLE
块级作用域与函数声明有个地方不理解

### ISSUE THREAD

**Issue by hickey666** [ruanyf/es6tutorial#660]
在let 和 const 命令章节的块级作用域有段代码是这样的
```js
function f() { console.log('I am outside!'); }

(function () {
  if (false) {
    // 重复声明一次函数f
    function f() { console.log('I am inside!'); }
  }

  f();
}());
```
这段代码运行应该是报错的，但您在文章里说输出‘I am inside’.我能理解您为什么这么说，但是能请您解释下为什么报错吗，是因为函数跟变量的区别吗

**Comment by hickey666** [comment]
额..我是在chrome上运行的，默认是es6
我现在就一个问题，怎么让chrome切换成es5

**Comment by XGHeaven** [comment]
你可以选择安装低版本的 chrome 或者使用 ie6 2333

**Comment by hickey666** [comment]
。。。我之前就在想会不会叫我装低版本的:smile:不过还是谢谢大佬了，3Q

**Comment by ruanyf** [comment]
用 nvm 切换到 Node 0.12 即可实验 ES5。
