### ISSUE TITLE
Set和Map数据结构 - WeakMap 的语法 第一段有个小错误

### ISSUE THREAD

**Issue by baxtergu** [ruanyf/es6tutorial#662]
- 原文  
WeakMap 与 Map 在 API 上的区别主要是两个，一是没有遍历操作（即没有key()、values()和entries()方法）

- 应为
WeakMap 与 Map 在 API 上的区别主要是两个，一是没有遍历操作（即没有key`s`()、values()和entries()方法）

keys()方法应名为复数形式keys。

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
