### ISSUE TITLE
safari兼容效果可以优化

### ISSUE THREAD

**Issue by wwy2018** [ruanyf/es6tutorial#663]
您好，safari打开本文档页面上下查看页面的时候存在跳动的问题，原因大概在于顶部进度条这里：
```
<div class="progress-indicator-2" style="width: 77.858%;"></div>
```
在chrome中没有产生跳动问题

**Comment by ruanyf** [comment]
我在 Safari 10 里面没有复现。后面我多用 Safari 浏览，如果复现了，看看怎么解决，或者去掉这个进度条。
