### ISSUE TITLE
Proxy get中的receiver问题

### ISSUE THREAD

**Issue by youen123** [ruanyf/es6tutorial#669]
http://es6.ruanyifeng.com/#docs/proxy 文章中写到
“上面代码中，get方法的第三个参数receiver，总是为当前的 Proxy 实例。get方法的第三个参数receiver，总是为当前的 Proxy 实例。“

感觉这里会误导，我认为get里的receiver和set里的receiver是一样的，都是原始读操作所在对象，下面是具体的例子
```
const proxy = new Proxy({}, {
  get: function(target, property, receiver) {
    return receiver;
  }
});
var d = Object.create(proxy)
d.a  === d // true
```

**Comment by ruanyf** [comment]
谢谢指出，这里确实写错了，已经改掉了。https://github.com/ruanyf/es6tutorial/commit/7d5a56292aefec91b000a691143de6fdd2dfbe27
