### ISSUE TITLE
变量声明语句中使用解构赋值且用了扩展运算符问题。

### ISSUE THREAD

**Issue by fzhw88** [ruanyf/es6tutorial#670]
丢九章有如下内容：
ES6 规定，变量声明语句之中，如果使用解构赋值，扩展运算符后面必须是一个变量名，而不能是一个解构赋值表达式，

这个规定是否只是正对对象？我用Chrome,Edge和Firefox测试了一下数组扩展运算没有报错，如下：
let [a,...[b,c]]=[1,2,3];
a; // 1
b; // 2
c; // 3

**Comment by ruanyf** [comment]
应该是的。当初就很奇怪，这个规则只有对象才存在。

**Comment by wc5858** [comment]
babel转换后的结果没有这条限制：[链接](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=DYUwLgBA3gdHUA8A0BPAvmiBeaCBcAjKngExpA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=true&lineWrap=true&presets=es2015%2Ces2016%2Ces2017%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3%2Ces2015-loose&prettier=true&targets=&version=6.26.0&envVersion=)

翻了些资料没找到明确的说明，但是有一些讨论：
https://github.com/tc39/proposal-object-rest-spread/issues/43
https://github.com/tc39/ecma262/issues/915

似乎是这样的语法很冗余，不易于理解，就ban掉了
