### ISSUE TITLE
proxy的construct()方法问题

### ISSUE THREAD

**Issue by fzhw88** [ruanyf/es6tutorial#673]
http://es6.ruanyifeng.com/#docs/proxy#construct

文中写道：
construct方法可以接受两个参数。

target: 目标对象
args：构建函数的参数对象

规范中construct方法可以接受三个参数，第三个参数指向调用new Proxy生成的实例。

**Comment by fzhw88** [comment]
参考：https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/construct
这里也没讲这第三个参数怎么用。

**Comment by ruanyf** [comment]
谢谢指出，我已经补上了。
