### ISSUE TITLE
Proxy中defineProperty()实例代码问题

### ISSUE THREAD

**Issue by fzhw88** [ruanyf/es6tutorial#674]
http://es6.ruanyifeng.com/#docs/proxy#defineProperty

原文代码：
var handler = {
  defineProperty (target, key, descriptor) {
    return false;
  }
};
var target = {};
var proxy = new Proxy(target, handler);
proxy.foo = 'bar'
// TypeError: proxy defineProperty handler returned false for property '"foo"'

实际上并不会报错，只是赋值静默失败。

**Comment by fzhw88** [comment]
用Object.defineProperty(proxy, 'foo',{value:'bar'})
 这样才会报错。

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
