### ISSUE TITLE
extends 的继承目标 中的文字解说有误？

### ISSUE THREAD

**Issue by fzhw88** [ruanyf/es6tutorial#679]
http://es6.ruanyifeng.com/#docs/class-extends#extends-%E7%9A%84%E7%BB%A7%E6%89%BF%E7%9B%AE%E6%A0%87

第三种特殊情况，子类继承null。

class A extends null {
}

A.__proto__ === Function.prototype // true
A.prototype.__proto__ === undefined // true

这种情况与第二种情况非常像。A也是一个普通函数，所以直接继承Function.prototype。但是，A调用后返回的对象不继承任何方法，所以它的__proto__指向Function.prototype，即实质上执行了下面的代码。

class C extends null {
  constructor() { return Object.create(null); }
}

其中：
但是，A调用后返回的对象不继承任何方法，所以它的__proto__指向Function.prototype
从行文的逻辑来看，应该是：
但是，A调用后返回的对象不继承任何方法，所以它的prototype的__proto__指向null。（因为null上不会有任何属性，所以A.prototype上访问任何属性都是undefined，包括__proto__）

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
