### ISSUE TITLE
关于函数参数的解构赋值

### ISSUE THREAD

**Issue by daishoulun** [ruanyf/es6tutorial#683]
function move({x, y} = { x: 0, y: 0 }) {
  return [x, y];
}
move({x: 3}); // [3, undefined]这个点我试过之后，不知道哪里出问题了得到的是[3, 0]

**Comment by ruanyf** [comment]
换个浏览器试试看。

**Comment by daishoulun** [comment]
问题已解决，谢谢阮一峰老师
