### ISSUE TITLE
Promise 可能早于本轮循环的同步任务。

### ISSUE THREAD

**Issue by xianshenglu** [ruanyf/es6tutorial#691]
[Promise 对象-基本用法](http://es6.ruanyifeng.com/#docs/promise#%E5%9F%BA%E6%9C%AC%E7%94%A8%E6%B3%95) 结尾处

> 这是因为立即 resolved 的 Promise 是在本轮事件循环的末尾执行，总是晚于本轮循环的同步任务。

用来解释相应的例子没错，但是这个表达不够严谨。

> 立即 resolved 的 Promise 是在本轮事件循环的末尾执行，总是晚于本轮循环的同步任务。

实际上，`Promise `作为微任务，

* 除了可能在本轮事件循环的末尾执行，也可能在任务当中运行，只要执行栈上没有正在执行的代码。
* 这就导致了，`Promise ` 可能早于本轮循环的同步任务

案例:

```html
<div class="outer">
  outer
  <div class="inner">inner</div>
</div>
```
```javascript
// Let's get hold of those elements
var outer = document.querySelector('.outer');
var inner = document.querySelector('.inner');

// Here's a click listener…
function onClick() {
  console.log('click');

  setTimeout(function() {
    console.log('timeout');
  }, 0); 

  Promise.resolve().then(function() {
    console.log('promise');
  });
}

// …which we'll attach to both elements
inner.addEventListener('click', onClick);
outer.addEventListener('click', onClick); 
```
在上面例子中，点击`inner`，`click` 事件的触发和冒泡都是同步的，但是`promise`会在冒泡的同步代码执行之前先执行，因为执行栈空了。

建议把下面的参考文档，放进文档里做备注，供人参考，对于理解事件循环和微任务大有裨益。
参考文档：[tasks-microtasks-queues-and-schedules](https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/)

**Comment by ruanyf** [comment]
谢谢补充，我把链接加入参考文档。

Task 这个概念还是暂时不放进书里，一方面为了简化模型，另一方面那篇文章也提到，不同的浏览器运行上面的代码，结果不一样。
