### ISSUE TITLE
第4章拓展符的应用，复制数组一节有待补充，concat()方法对对象引用（非对象直接量）会复制对象引用放到组合的新数组里，此处是浅复制

### ISSUE THREAD

**Issue by volcanG** [ruanyf/es6tutorial#694]
引用地址：[https://www.jianshu.com/p/ec79c4e47370](url)
array.concat(value1, value2.....)
将传入的数组或非数组值与原数组合并，组成一个新的数组并返回
**注意**：concat方法在拷贝原数组的过程中，

- 对象引用（非对象直接量）：concat方法会复制对象引用放到组合的新数组里，原数组和新数组中的对象引用都指向同一个实际的对象，所以，当实际的对象被修改时，两个数组也同时被修改

- 字符串和数字（是原始值，而不是包装原始值的string和number对象）：concat方法会复制字符串和数字的值放到新数组里

书中实例只使用了数字数组做示例，并不完全，望能补全。

**Comment by ruanyf** [comment]
谢谢指出，已经补充了。
