### ISSUE TITLE
"23.Module 的加载实现” 中 “CommonJS 模块加载 ES6 模块” 案例运行报错

### ISSUE THREAD

**Issue by sunq0001** [ruanyf/es6tutorial#696]
在webpack4环境下运行这条语句会报错：
`const es_namespace = await import('./es.mjs');`

ERROR in ./src/index.js
Module parse failed: Can not use keyword 'await' outside an async function (1:11)
You may need an appropriate loader to handle this file type.

说明await不能独立于async function使用

**Comment by ruanyf** [comment]
这是提案，尚未实现。
