### ISSUE TITLE
关于es6中函数扩展章节的实例错误问题

### ISSUE THREAD

**Issue by 17717840944** [ruanyf/es6tutorial#699]
在es6 这本书中的“函数的扩展”这一章，第一个部分“函数参数的默认值”中讲到“作用域”时用的第5和第7的例子结果错了

**Comment by ruanyf** [comment]
错在哪里？

**Comment by 17717840944** [comment]
http://es6.ruanyifeng.com/#docs/function#%E4%BD%9C%E7%94%A8%E5%9F%9F

我不清楚是您那错了，还是这个网站有bug，反正我将代码copy过去，结果不一样


------------------------------------------------------------------
发件人：Ruan YiFeng <notifications@github.com>
发送时间：2018年6月19日(星期二) 16:30
收件人：ruanyf/es6tutorial <es6tutorial@noreply.github.com>
抄　送：17717840944 <czr2399728400@dingtalk.com>; Author <author@noreply.github.com>
主　题：Re: [ruanyf/es6tutorial] 关于es6中函数扩展章节的实例错误问题 (#699)

错在哪里？

**Comment by ruanyf** [comment]
你可以把代码拷贝过来，哪一段代码，报了什么错。
