### ISSUE TITLE
尾递归依然出现“栈溢出”的问题

### ISSUE THREAD

**Issue by JiangL1011** [ruanyf/es6tutorial#703]
阮老师您好，您的《ECMAScript6 入门》写的非常好，我很喜欢这本书，真的帮助我提升了不少，非常感谢您。不过我在学习尾递归这一章节的时候有一点不是很明白，希望您能帮我解答一下。您在这一章的时候说过对于尾递归来说，由于只存在一个调用帧，所以永远不会发生“栈溢出”错误。但是我引用了您书里的代码还是出现了“栈溢出”。
`function Fibonacci2 (n , ac1 = 1 , ac2 = 1) {
  if( n <= 1 ) {return ac2;}
  return Fibonacci2 (n - 1, ac2, ac1 + ac2);
}

Fibonacci2(100)    //573147844013817200000
Fibonacci2(1000)    //7.0330367711422765e+208
Fibonacci2(9000)    //Infinity
Fibonacci2(10000)    //Infinity
Fibonacci2(1000000)
VM2133:1 Uncaught RangeError: Maximum call stack size exceeded`

**Comment by STLighter** [comment]
似乎v8默认关闭的尾递归优化
参考资料:
http://imweb.io/topic/5a244260a192c3b460fce275
https://www.zhihu.com/question/20501180

**Comment by flyyang** [comment]
可以看看这篇文章[javascript 中的尾递归优化](https://flyyang.github.io/2017/07/24/JavaScript-%E4%B8%AD%E7%9A%84%E5%B0%BE%E8%B0%83%E7%94%A8%E4%BC%98%E5%8C%96%EF%BC%88tail-call-optimization%EF%BC%89/)

**Comment by ruanyf** [comment]
浏览器的尾递归优化功能被去掉了，实际上没支持……

**Comment by hax** [comment]
@ruanyf 从现在情况看，除了Safari之外，其他浏览器厂商不会实现尾调用，所以建议把尾调用这部分从函数扩展中拿掉，放到附录或其他部分去，并注明一下现实情况。

**Comment by JiangL1011** [comment]
非常感谢大家的解答

**Comment by LongTengDao** [comment]
> @ruanyf 从现在情况看，除了Safari之外，其他浏览器厂商不会实现尾调用，所以建议把尾调用这部分从函数扩展中拿掉，放到附录或其他部分去，并注明一下现实情况。

他们有什么理由吗？

**Comment by hax** [comment]
看这个：https://www.bilibili.com/video/av10389292/?p=3

**Comment by LongTengDao** [comment]
@hax 谢谢！声音很清澈。

我理解的大概情况是，规范规定了（默认）尾递归（PTC），但是除了 Safari 之外的都没实现，而且他们还提议为尾递归规定新的语法（STC）。双方都不同意对方，就搁置下来了。但是这么合理的需求，百利无一害，还是不明白为什么他们为什么认为应该靠新语法解决。如果是技术难度，那新语法下不还是要去实现它吗？那些理由听上去非常像扯淡……

另外，这种活动是开放的吗？如果是，哪里可以及时获取通知并报名参加？（这个系列活动的信息我看到官方网站和渠道了，我是指哪里可以关注您将莅临的活动？）

**Comment by XGHeaven** [comment]
@LongTengDao 视频以及上面的例子里面讲了，依靠尾递归优化之后，调用栈会丢失。这在开发的情况下不是很方便的，可以说比较致命的一个问题。而且大部分情况下，尾递归可以通过循环的方式进行简化。引用新语法并不是说为了换一种实现方式，我是觉得减轻编译器推断是否要启动尾递归的复杂度。就像是为啥要引入 async/await 语法，直接 v8 自己推断是不是异步操作然后等待就可以了，一个样子的道理。

实在不行，你就理解新语言就是递归循环展开的语法糖呗~~ // 我没看过他们具体讨论的语法的样子，猜测的，有误见谅。

尾递归，是一个好东西。就算是放在一些强类型语言(C++)里面，也是要开启 -O2 之后才会优化尾递归，更何况 js 这种动态语言呢。

还有活动什么的，多多关注社区动态就可以了，实在不行天天逛活动行都可以。

**Comment by LongTengDao** [comment]
@XGHeaven 谢谢！

同一个函数的自我尾递归的调用栈应该没什么用了吧，这个应该是主要应用场景吧。你认为呢？

至于目前，你说的尾递归通过循环简化我想理论上是可行的。我的应用场景是类似于不限层数的 JSON.parse，这种树状递归（而非单线递归）是不是有比较成熟的解决方案？

**Comment by XGHeaven** [comment]
@LongTengDao 确实，对于树状的尾递归确实写起来方便很多。

反正我理解并支持引入新的语法。。。我觉得显式的比隐式的更加清楚，不容易掉坑里。说白了，我觉得尾递归优化作为一个语法糖是不是更合适一点 😂

**Comment by hax** [comment]
@LongTengDao 视频里讲了一些问题。PTC的缺陷一个是调用栈问题，一个是无法明确程序员意图导致在后续维护时可能被错误重构并产生很难发现的bug。
