### ISSUE TITLE
在讲解扩展运算符分解数组的时候，替代apply的误导说明

### ISSUE THREAD

**Issue by ThenMorning** [ruanyf/es6tutorial#704]
在我看到  数组的扩展     “替代函数的 apply 方法 ”这里时，
因为例子只给了 f.apply(null,[1,2,3]) 与 f(...[1,2,3]) 
我会猜想
f.apply(obj,[1,2,3]) 与 f(obj,...[1,2,3])是否是同样的效果
建议给与说明

**Comment by snow212-cn** [comment]
不同，f(obj,...[1,2,3])相当于f.apply(null,[obj,1,2,3])

**Comment by ThenMorning** [comment]
@snow212-cn 
嗯 我试过的，我的意思是，扩展运算符 只是 代替了apply 数组解构的功能，并不能完全替代函数apply
这点如果提出来，会更好

**Comment by ruanyf** [comment]
@zhaowanhua 你的意见是正确的，就是表达起来会句子很长。这里意思是，在扩展参数数组方法，可以替代 apply 方法，我想想怎么表达比较好。
