### ISSUE TITLE
14章 promise问题

### ISSUE THREAD

**Issue by banli17** [ruanyf/es6tutorial#705]
第14章 Promise，第四节 Promise.prototype.catch()最后一点.

```
const someAsyncThing = function() {
  return new Promise(function(resolve, reject) {
    // 下面一行会报错，因为x没有声明
    resolve(x + 2);
  });
};

someAsyncThing().then(function() {
  return someOtherAsyncThing();
}).catch(function(error) {
  console.log('oh no', error);
  // 下面一行会报错，因为 y 没有声明
  y + 2;
}).then(function() {
  console.log('carry on');
});
// oh no [ReferenceError: x is not defined]
```

> 上面代码中，catch方法抛出一个错误，因为后面没有别的catch方法了，导致这个错误不会被捕获，也不会传递到外层。

这里 y+2 错误会传递到外层。最新chrome测试版本 67.0.3396.87（正式版本）

![wx20180625-160254](https://user-images.githubusercontent.com/12556069/41837856-4c098450-7891-11e8-9473-c0dd6a8cd9b5.png)

**Comment by banli17** [comment]
另外，我有个几个疑问，为什么下面两种写法不一样，第一种写法的 rejection 没有拦截掉,后面的catch还是执行了。
![wx20180625-160254](https://user-images.githubusercontent.com/12556069/41838049-d3f45eee-7891-11e8-9d3b-cff001810a0e.png)

**Comment by STLighter** [comment]
问题1: 我认为可能是有一些歧义. 这里的`不会传递到外层`是指`不会终止脚本执行`.

>上面代码中，someAsyncThing函数产生的 Promise 对象，内部有语法错误。浏览器运行到这一行，会打印出错误提示ReferenceError: x is not defined，但是不会退出进程、终止脚本执行，2 秒之后还是会输出123。这就是说，Promise 内部的错误不会影响到 Promise 外部的代码，通俗的说法就是“Promise 会吃掉错误”。

问题2: 前者`.then`和`.catch`都是在`p`上, `.catch`捕获的是`p`上产生的错误. 后者`.catch`是在`.then`返回的Promise上, `.catch`捕获的是`() => { console.log('y') }`上产生的错误.
可以将`() => { console.log('y') }`换成以下函数, 根据执行顺序进行理解.
```js
() => {
  return new Promise((res, rej) => {
    setTimeout(() => {
        console.log('y')
        rej();
    }, 1000)
  })
}
```

**Comment by banli17** [comment]
@STLighter  谢谢，第二个理解了，第一个我试试看看

**Comment by ruanyf** [comment]
@STLighter 的解释没有问题。

第一个问题是这样的，脚本只是打印出错误，实际上没有报错。

```bash
$ node demo.js
oh no ReferenceError: x is not defined

$ echo $?
0
```

上面代码中，虽然打印出了错误，但是实际上脚本是正常结束的，退出状态为 0。
