### ISSUE TITLE
19章中的问题: 类不能定义属性

### ISSUE THREAD

**Issue by frostrain** [ruanyf/es6tutorial#706]
19章中写道 类 可以定义 **实例属性** 和 **静态属性**
`class MyClass {
  myProp = 42;

  constructor() {
    console.log(this.myProp); // 42
  }
}`

但是实际上并不能定义属性, [参考这里](http://exploringjs.com/es6/ch_classes.html#_inside-the-body-of-a-class-definition)
自己测试一下也可发现会报错

ps: typescript 里倒是可以这么写

**Comment by songchengen** [comment]
还在提案阶段，即使通过了，浏览器也没那么快支持吧

**Comment by ruanyf** [comment]
应该会进入 ES2019 标准。

**Comment by hax** [comment]
不好说。这个提案比较有争议，ES2019也不一定会加。比方说我就反对这提案 😜 ，我支持的是 classes 1.1 提案。

**Comment by LongTengDao** [comment]
```js

let a = 1;
let b= 1;

class MyClass extend Object {
    myPropA = a;
    myPropB = b;
    constructor (a) {
        b = 2;
        super();
        b = 3;
    }
}

new MyClass(2);

```

感觉这事没那么容易定。。作用域、运行时顺序是个大问题
算在 constructor 里的话看起来太混乱了，算在外层的话就很废了。
在super后才添加很容易很乱，在constructor开始时缓存值并在super()之后添加的话也非常狗。。如果父类上还有setter，真不知道合适触发比较合理。
@ruanyf 阮大大倾向于哪种？
