### ISSUE TITLE
第15章 Iterator 和 for...of 循环 遍历器对象中的return方法调用时机的问题

### ISSUE THREAD

**Issue by lvshijie321** [ruanyf/es6tutorial#708]
原文：
上面代码中，函数readLinesSync接受一个文件对象作为参数，返回一个遍历器对象，其中除了next方法，还部署了return方法。下面的三种情况，都会触发执行return方法。

...
// 情况二
for (let line of readLinesSync(fileName)) {
  console.log(line);
  continue;
}
...

测试反馈：
使用 continue 命令并不会执行 return 方法，而是循环执行next函数

**Comment by ruanyf** [comment]
谢谢指出，我测了一下，果然不会触发。已经改过来了。
