### ISSUE TITLE
20.1 简介 表述错误（续）

### ISSUE THREAD

**Issue by jasonfreak** [ruanyf/es6tutorial#711]
关联问题：[657](https://github.com/ruanyf/es6tutorial/issues/657)
表述：

> ES5 的继承，实质是先创造子类的实例对象this，然后再将父类的方法添加到this上面（Parent.apply(this)）。ES6 的继承机制完全不同，**实质是先创造父类的实例对象this（所以必须先调用super方法），然后再用子类的构造函数修改this**。

以及

> 另一个需要注意的地方是，在子类的构造函数中，只有调用super之后，才可以使用this关键字，否则会报错。这是因为子类实例的构建，是基于对父类实例加工，**只有super方法才能返回父类实例**。

黑体部分仍将super()方法视为创造父类实例，描述不一致。

**Comment by ruanyf** [comment]
谢谢指出，应该更正。
