### ISSUE TITLE
关于顶层对象的疑问

### ISSUE THREAD

**Issue by qianfeii** [ruanyf/es6tutorial#715]
阮老师您好，在看到顶层函数一小节时的一些代码在浏览器环境中没有问题。但在vue-cli 3 初始化的项目中运行起来结果不是预期结果。代码是加在入口的 main.js 中的。这个大概是什么造成的？是因为webpack打包过么？

console.log(window) // Window
console.log(global) // Window
console.log(this) // undefined
// eslint-disable-next-line
var a = 1
console.log(window.a) // undefined
// eslint-disable-next-line
let b = 1
console.log(window.b) // undefined
// eslint-disable-next-line
c = 1
console.log(window.c) // Uncaught ReferenceError: c is not defined

let app = document.getElementById('app')
console.log(app)  // #app dom

打包以后浏览器控制台查看对应js文件（去\n）：
var a = 1;
console.log(window.a); // undefined
// eslint-disable-next-line
var b = 1;
console.log(window.b); // undefined
// eslint-disable-next-line
c = 1;
console.log(window.c);

**Comment by ruanyf** [comment]
Webpack 打包过程中，顶层对象会临时替换，所以顶层的 this 指向不正确。

**Comment by qianfeii** [comment]
那之后的var 声明 a 的 ，输出window.a 是undefined  也是因为在打包过程中的临时替换顶层对象  没有把a添加进顶层的window中么？
