### ISSUE TITLE
const 本质的解释，貌似不太对

### ISSUE THREAD

**Issue by jianghuzai** [ruanyf/es6tutorial#720]
## 原文
> `const`实际上保证的，并不是变量的值不得改动，而是变量指向的那个内存地址不得改动。对于简单类型的数据（数值、字符串、布尔值），值就保存在变量指向的那个内存地址，因此等同于常量。但对于复合类型的数据（主要是对象和数组），变量指向的内存地址，保存的只是一个指针，`const`只能保证这个指针是固定的，至于它指向的数据结构是不是可变的，就完全不能控制了。因此，将一个对象声明为常量必须非常小心。

## 咬文嚼字
* 第一句：`const`  保证变量指向的那个内存地址不得改动。
* 第二句：对于复合类型数据，变量指向的内存地址，保存的只是一个指针，`const `只能保证指针是固定的。

矛盾之处：一句说变量所指向的内存地址不得改动，一句说，内存地址里面的指针是固定的。

## 以java的内存模型来解释
相信不管是c，还是java，还是javaScript,都是类似的。

在java内存模型中：
* 每个方法的调用和结束，对应着一个栈帧在 `栈`中出栈和入栈。
* 每个栈帧都会有一个局部变量表。
* 每定义一个变量时，系统（jvm）会在`当前栈帧`的局部变量表内添加一行记录。
* 如果是基本数据类型，值会被保存在局部变量表中；如果是复合类型，会在`堆`中分配一块内存，内存地址会被保存在局部变量表中。
* 如果加了`const`关键字，局部变量表中的值就不能改变（基本类型，值不能改；复合类型，指针不能修改指向）。

## 类比结论
* 不管是基本类型，还是复合类型，加了`const`只是保证，局部变量表中的值不能改变。
* 变量所指向的内存地址并不能通过程序类控制，声明一个变量时，该变量所指向的内存已经确定。
* 变量所指向的内存中，保存的是什么？基本类型：值；复合类型：对象在堆中的内存地址。

**Comment by ruanyf** [comment]
谢谢指出，我表达得不好。现在改了一下，看看是不是好一点。

**Comment by jianghuzai** [comment]
@ruanyf 看了一下你的改动，其实我觉得第二句是没毛病的，有问题的应该是第一句。按照你的思路，我觉得这样改会比较好：

`const`实际上保证的，**是变量指向的那个内存地址所保存的数据不得改动**。对于简单类型的数据（数值、字符串、布尔值），值就保存在变量指向的那个内存地址，因此等同于常量。但对于复合类型的数据（主要是对象和数组），变量指向的内存地址，保存的只是一个指向实际数据的指针，const只能保证这个指针是固定的（即总是指向另一个固定的地址），至于它指向的数据结构是不是可变的，就完全不能控制了。因此，将一个对象声明为常量必须非常小心。

**Comment by ruanyf** [comment]
确实你的表达更好，已经采用你的表达了。

**Comment by LongTengDao** [comment]
我认为在高级脚本语言教程中谈及“内存地址”层面的概念并不合适……它是不透明也没有必要谈及的概念。

>   `const`实际上保证的，并不是变量的值不得改动，而是变量指向的那个内存地址所保存的数据不得改动。对于简单类型的数据（数值、字符串、布尔值），值就保存在变量指向的那个内存地址，因此等同于常量。但对于复合类型的数据（主要是对象和数组），变量指向的内存地址，保存的只是一个指向实际数据的指针，`const`只能保证这个指针是固定的（即总是指向另一个固定的地址），至于它指向的数据结构是不是可变的，就完全不能控制了。因此，将一个对象声明为常量必须非常小心。

无论 `let` 还是 `const`，它们只是**变量**层面的区别，`const` 实际上保护的，只是变量本身，而不是值。
比如，当你 `const arr = [ 0, 1 ];` 时，唯一发生的事情只是 `arr` 这个变量以后不能再通过 `arr = ...` 来等于别的东西了，至于它所指向的这个数组 `[ 0, 1 ]` 是否还能被修改内容（比如往里面 `push` 新数据），它是完全不管的。

…………

如果你希望让一个值内部不能再被修改，那么你可能需要的是 `Object.freeze` 函数，它能够使一个对象不能够再修改、新增或删除属性。不过需要注意的是，

1.  如果该对象某个属性的值是另一个对象，那么那个对象的属性是否能够被修改，只取决于那个对象有没有被 `Object.freeze`。换言之，`Object.freeze` 只管一层，不会自动层层深入下去，如果你有需要，那么你要自己写一个函数来逐层冻结。

2.  你只能对一个理论上有可能被修改属性的数据类型进行冻结操作，比如对象、函数。至于像字符串、数字之类的数据类型，本来就不存在“修改属性”一说（比如 `"abc".x = 1` 本来就是不行的）。

**Comment by jianghuzai** [comment]
@LongTengDao 
首先，Object.freeze的说明没有毛病，不过我不清楚它的底层是如何做到保证对象不被修改滴~
所以，在Object.freeze和const之间我想不到他们之间的联系是什么~~

其次，下面这句话我不太认同：
> 我认为在高级脚本语言教程中谈及“内存地址”层面的概念并不合适……它是不透明也没有必要谈及的概念。

我觉得，学一门语言，如果能把内存模型弄清楚，那些神奇诡异的结果，都能自己解释清楚了~~

**Comment by LongTengDao** [comment]
@jianghuzai 

## 关于 `Object.freeze`

我想阮老师的书在讲到 `const` 这里，他会去提一下 `Object.freeze`，主要用意是避免 `const` 被误用。

虽然 `Object.freeze` 不属于 ES6，不过这样对学习的人可能更友好。

当然，提示也不可能无穷无尽，所以最终还是看阮老师基于整体篇幅的考虑，详略如何取舍。

## 关于底层概念

我觉得这有点像迟到时被老师问道“怎么又迟到了？”，有人认为“没听见闹钟”是答案的方向，而有人认为“对不起，下次注意”是答案的方向，这个就见仁见智了。
