### ISSUE TITLE
阮老师，2.2.3里块级作用域的例子

### ISSUE THREAD

**Issue by tqq123** [ruanyf/es6tutorial#721]
function f() {
    console.log('I am outside')
  }
  
  (function(){
  
    if (false) {
      function f(){'I am inside'}
    }
    f()
  }())
这个例子在chrome和IE  edge下会报错tqq not a function，在ie10以下版本却正常输出。是JS引擎的问题吗？

**Comment by jianghuzai** [comment]
@tqq123 里面不是已经说明了吗？
*  ES5 中运行，会得到“I am inside!”，因为在if内声明的函数f会被提升到函数头部。
* ES6 就完全不一样了，理论上会得到“I am outside!”但是，如果你真的在 ES6 浏览器中运行一下上面的代码，是会报错的

chrome 和 IE edge是es6，，ie10以下是es5………………

**Comment by nuanyang233** [comment]
如果是在Node环境下也会报错，不会输出理论结果，这是为什么呢？
