### ISSUE TITLE
扩展运算符应用中，数组的浅拷贝，貌似不对

### ISSUE THREAD

**Issue by jianghuzai** [ruanyf/es6tutorial#723]
### （1）复制数组
扩展运算符提供了复制数组的简便写法。
```
const a1 = [1, 2];
// 写法一
const a2 = [...a1];
// 写法二
const [...a2] = a1;
```
上面的两种写法，a2都是a1的克隆。

### （2）合并数组
扩展运算符提供了数组合并的新写法。
```
const arr1 = ['a', 'b'];
const arr2 = ['c'];
const arr3 = ['d', 'e'];
// ES5 的合并数组
arr1.concat(arr2, arr3);
// [ 'a', 'b', 'c', 'd', 'e' ]
// ES6 的合并数组
[...arr1, ...arr2, ...arr3]
// [ 'a', 'b', 'c', 'd', 'e' ]
```
不过，这两种方法都是浅拷贝，使用的时候需要注意。
```
const a1 = [{ foo: 1 }];
const a2 = [{ bar: 2 }];
const a3 = a1.concat(a2);
const a4 = [...a1, ...a2];
a3[0] === a1[0] // true
a4[0] === a1[0] // true
```
上面代码中，a3和a4是用两种不同方法合并而成的新数组，但是它们的成员都是对原数组成员的引用，这就是浅拷贝。如果修改了原数组的成员，会同步反映到新数组。

## 问题所在
* 同样的操作，复制数组的时候就是克隆，合并数组的时候就变成了浅拷贝
* 所谓浅拷贝与深复制，前提是对象，所以，对于基本数据类型来说，没有浅拷贝一说。
* 在第二个例子中，`const arr4 = [...arr1, ...arr2, ...arr3];`,这时候改变arr1、arr2、arr3的元素，arr4的元素并不受影响。所以，合并数组不是浅拷贝。
* 第三个例子，貌似把对象的复制混进来了。

### （2）合并数组
扩展运算符提供了数组合并的新写法。
```
// ES5 的合并数组(es5并没有const这个关键字)
var arr1 = ['a', 'b'];
var arr2 = ['c'];
var arr3 = ['d', 'e'];
var arr4 = arr1.concat(arr2, arr3);//['a', 'b','c','d', 'e']
arr1[0] = 'g';
console.log(arr4[0]);//a  (并不受arr1的修改的影响)


// ES6 的合并数组
const arr1 = ['a', 'b'];
const arr2 = ['c'];
const arr3 = ['d', 'e'];
const arr4 = [...arr1, ...arr2, ...arr3]; // [ 'a', 'b', 'c', 'd', 'e' ]
arr1[0] = 'g';
console.log(arr4[0]);//a  (并不受arr1的修改的影响)
```
这两种方法是等效的。

## 对于第三个例子的看法
* 数组是对象，数组的浅拷贝判断：对某个元素重新赋值，看拷贝出来的数组同位置的元素是否也被重新赋值了。

### 对元素重新赋值
```
const obj1 = { foo: 1 };
const obj2 = { foo: 2 };
const obj3 = { foo: 2 };
const arr1 = [obj1];
const arr2 = [obj2];
const arr3 = arr1.concat(arr2);
const arr4 = [...arr1, ...arr2];

arr1[0] = obj3; //修改原数组

console.log(arr3[0].foo);//1，并不受arr1对第一个元素重新赋值的影响
console.log(arr4[0].foo);//1，并不受arr1对第一个元素重新赋值的影响
```
### 判断元素是否 ===
```
const a1 = [{ foo: 1 }];
const a2 = [{ bar: 2 }];
const a3 = a1.concat(a2);
const a4 = [...a1, ...a2];
a3[0] === a1[0] // true
a4[0] === a1[0] // true
```
这只能说明 a3[0]、 a4[0] 、a1[0]都是同时引用了同一个对象。

## 最后给阮老师的建议
阮老师写的很多文章，都很受大家欢迎、喜爱，因为通俗易懂。我也只是一个刚毕业一年的年轻人，不敢说批评阮老师，不过从前天好今天我提的issue来看，我个人是觉得，阮老师对内存模型这一块不是很清晰的。所以，如果阮老师有空，可以去读一读c语言中的“指针的指针、数组指针、指针数组”以及《深入理解java虚拟机》的第二章；虽然是不同的语言，但是堆、栈这些概念是想通的。

学了c再学java的时候，老师告诉我们，java没有指针了。但是，真正理解了的人都知道，java中都是很巧妙的各种指针。故，建议阮老师读“指针的指针、数组指针、指针数组”以及《深入理解java虚拟机》。

再次感谢阮老师文章，给我很大的帮助。

**Comment by ruanyf** [comment]
例子本身没有问题吧，就是用语不太精确，我以后注意一下。

**Comment by jianghuzai** [comment]
@ruanyf 嗯，例子本身没问题，但是例子与结论，就有点出入。我坚持认为：你写的最后一个例子不能作为，数组的合并是浅拷贝的证明。因为那个例子已经把数组的拷贝与对象的拷贝，混起来了。给人的感觉是浅拷贝，但是那是对象的浅拷贝，不是数组的浅拷贝。希望阮老师再次思考：数组的浅拷贝与及对象的浅拷贝之间的  区别。

**Comment by jianghuzai** [comment]
@ruanyf 你是夜猫还是早起啊，，，，6点来看issue，，，害得我忍不住爬起来开电脑

**Comment by ruanyf** [comment]
第三个例子没有拷贝对象。你那个浅拷贝的定义是不对的，它判断的是数组成员的成员是否拷贝。

**Comment by jianghuzai** [comment]
@ruanyf 嗯，我查了一下浅拷贝与深拷贝的区别，确实是我弄错了:[js的浅拷贝与深拷贝](http://yuanhehe.cn/2016/11/03/%E7%90%86%E8%A7%A3JS%E7%9A%84%E6%B5%85%E6%8B%B7%E8%B4%9D%E4%B8%8E%E6%B7%B1%E6%8B%B7%E8%B4%9D/)

那么问题又来了，第一个例子复制数组的时候，也是浅拷贝了吧？

**Comment by xiaomizhou66** [comment]
留个脚印，让自己辨识一下这个问题~~~~~~~
