### ISSUE TITLE
对类 （class） 部署Symbol.iterator接口，下面的写法为什么会出现预料之外的错误

### ISSUE THREAD

**Issue by antiai1** [ruanyf/es6tutorial#724]
class RangeIterator {
    constructor(start, stop) {
        this.value = start;
        this.stop = stop;
    }

    [Symbol.iterator]() {
        return {
            next() {
                var value1 = this.value;
                if (value1 < this.stop) {
                    this.value1++;
                    return {
                        done: false,
                        value: value1
                    }
                }
                return {
                    done: true,
                    value: undefined
                }
            }
        };
    } 
}

var range = new RangeIterator(0,3);
var range_iterator = range[Symbol.iterator]();
console.log(range_iterator.next());
// {done: true, value: undefined}

+++++++++++++++++++++++++++++++++
结果为什么直接返回遍历完成的结果呢？

**Comment by ruanyf** [comment]
这样写。

```javascript
[Symbol.iterator]() {
   const that = this;
    return {
        next() {
            var value1 = that.value;
            if (value1 < that.stop) {
                that.value1++;
                return {
                    done: false,
                    value: value1
                }
            }
            return {
                done: true,
                value: undefined
            }
        }
    };
} 
```

**Comment by antiai1** [comment]
谢谢阮大大，这里是不是next（）方法改变了this的指向，能不能用箭头函数对next()函数进行改造。

**Comment by antiai1** [comment]
而且这个next()函数中that.value1++  和  value1++  执行的结果会会有差异呢？
