### ISSUE TITLE
ES6教材网站无法打开了

### ISSUE THREAD

**Issue by suchanglin** [ruanyf/es6tutorial#727]
老师你好，贵网站http://es6.ruanyifeng.com/  目前无法打开了，遇到了故障？

**Comment by ruanyf** [comment]
被广告拦截器误杀了。

请把 es6.ruanyifeng.com 加入白名单。

**Comment by suchanglin** [comment]
感谢阮老师的答疑解惑，确实是这个原因。Adblock添加了白名单就可以了。

**Comment by ruanyf** [comment]
重新打开这个 issue，其他人也有这个问题，就可以看到了。

**Comment by ruanyf** [comment]
改了一下代码，现在可以打开了。

**Comment by AllySu** [comment]
OKOK，毕竟不是每个人都上来GitHub，就算上来了也很难从issues中找到解决方案。阮老师解决问题的耐心细致和彻底性值得学习。

**Comment by derek2035** [comment]
![image](https://user-images.githubusercontent.com/2821160/54588070-e0c58b00-4a5c-11e9-896c-fa010135c6d1.png)
现在打开成一个英文网站了

**Comment by LeezQ** [comment]
> ![image](https://user-images.githubusercontent.com/2821160/54588070-e0c58b00-4a5c-11e9-896c-fa010135c6d1.png)
> 现在打开成一个英文网站了

你这个是一个 ip 访问过多，被当成是机器了。验证下应该就好了
