### ISSUE TITLE
关于Generator与状态机一节的疑惑

### ISSUE THREAD

**Issue by ZhangWren** [ruanyf/es6tutorial#732]
http://es6.ruanyifeng.com/#docs/generator#Generator-%E4%B8%8E%E7%8A%B6%E6%80%81%E6%9C%BA

如下图红框
![u zrr27 o31gz v v93pm](https://user-images.githubusercontent.com/25240164/43875672-eea86028-9bc3-11e8-9a70-545fc3101aab.png)

下图是运行结果
![a1 _dzma xg cmh s 663](https://user-images.githubusercontent.com/25240164/43875736-389ccc46-9bc4-11e8-85ac-338e18a5e5a1.png)

如图可以清楚的看到，并没有发生每次运行都发生状态的修改，是否是我的运行有问题？请阮老师指点

**Comment by ruanyf** [comment]
不要每次都新建一个迭代器。

**Comment by ZhangWren** [comment]
@ruanyf 应该怎样运行呢？请阮老师指点下

**Comment by ruanyf** [comment]
clock（）每次返回的都是新的迭代器。

**Comment by ZhangWren** [comment]
@ruanyf 不好意思阮老师，如果这样的话，

var clock = function* () {
　while(true) {
　　console.log('Tick!');
　　yield;
　　console.log('Tock!');
　　yield;
　}
}

上面那段代码岂不是不能实现👇👇👇
　　　　　　　　　　　　　　Tick！
　　　　　　　　　　　　　　Tock！
　　　　　　　　　　　　　　Tick！
　　　　　　　　　　　　　　Tock！

亦或者是我的理解有问题？

**Comment by ruanyf** [comment]
好吧，我把代码写出来。这个问题到此为止。

var gen = clock();

gen.next();
gen.next();
