### ISSUE TITLE
关于Proxy的deleteProperty

### ISSUE THREAD

**Issue by YancyLuo** [ruanyf/es6tutorial#733]
问题：return true并不能实际删除想要删除的属性，应该在之前调用delete删除；
   老师您好，很感谢您出的这本书供我们这些新人学习，在测试例子的时候发现了上述问题，可能这并不是您所讲的重点，而且我也不确定我的做法是否合理，所以特在此提交问题。

**Comment by ruanyf** [comment]
谢谢指出，确实是漏掉了。已经改好了。
