### ISSUE TITLE
Generator 函数的流程管理

### ISSUE THREAD

**Issue by hengfei-xiao** [ruanyf/es6tutorial#734]
阮老师您的例子
var fs = require('fs');
var thunkify = require('thunkify');
var readFileThunk = thunkify(fs.readFile);

var gen = function* (){
  var r1 = yield readFileThunk('/etc/fstab');
  console.log(r1.toString());
  var r2 = yield readFileThunk('/etc/shells');
  console.log(r2.toString());
};

var g = gen();

var r1 = g.next();
r1.value(function (err, data) {
  if (err) throw err;
  var r2 = g.next(data);
  r2.value(function (err, data) {
    if (err) throw err;
    g.next(data);
  });
});

我模仿着写的
var readFileThunk = ()=>{
	return new Promise((relsove)=>{
		setTimeout(()=>{
			relsove('123')
		})
	})
}
var readFileThunk1 = ()=>{
	return new Promise((relsove)=>{
		setTimeout(()=>{
			relsove('qwe')
		})
	})
}

var gen = function* (){
  var r1 = yield readFileThunk();
  console.log(r1);
  var r2 = yield readFileThunk1();
  console.log(r2);
};

var g = gen();

var r1 = g.next();
r1.value(function (err, data) {
  if (err) throw err;
  var r2 = g.next(data);
  r2.value(function (err, data) {
    if (err) throw err;
    g.next(data);
  });
});
这个地方的r1返回的不是一个Promise对象吗？我按照这么写的话报错r1.value is not a function。
如果用r1.value.then()的话就不报这个错了，但是后面又不对了。请阮老师帮看一下，我是写错了么。

**Comment by ruanyf** [comment]
readFileThunk 返回的应该是一个函数，不是 Promise 对象。你这样写，把两个概念混在一起了。

感觉你没有搞懂 Thunk 是什么，再好好看一下吧。
