### ISSUE TITLE
import() 动态加载模块（路径是未知的，是个变量） 提示module not found。 

### ISSUE THREAD

**Issue by zhouqunhua** [ruanyf/es6tutorial#735]
（3）动态的模块路径

import()允许模块路径动态生成。

import(f())
.then(...);

确定模块路径动态生成可用吗？

**Comment by ruanyf** [comment]
你试试看, Chrome 浏览器已经支持了。

**Comment by zhouqunhua** [comment]
试了不支持...路径还是得常量...

**Comment by ruanyf** [comment]
支持的。

我试了一个 demo http://jsbin.com/zeyebafifu/edit?js,console,output

**Comment by zhouqunhua** [comment]
是不是本地不行，部署到服务器上才行，我先部署到服务器上看看

**Comment by flyyang** [comment]
检查以下是不是一个网络地址。没记错的化，不支持相对路径。

**Comment by zhouqunhua** [comment]
尝试了相对的绝对的依旧不行，webpack版本是3.7     
  fn(){
       return  'https://ip:port/xxxWebsite/app.js'
    }
    componentDidMount(){
        import(this.fn()).then(module =>{console.log(module)}).catch(error=>(console.log(error.message)));
    }


运行期报错： Uncaught Error: Cannot find module "."

**Comment by zhouqunhua** [comment]
我的理解是webpack编译期  函数没有执行自然是找不到对应的模块。但是阮老师那个例子为什么跑起来没问题也没弄明白
