### ISSUE TITLE
关于字符扩展章节的at()方法的疑惑

### ISSUE THREAD

**Issue by bingxl** [ruanyf/es6tutorial#736]
查看了es2018,里面没有 String.prototype.at() 方法, 查看了es的现有提案里面也没有at()方法. 再chrome 68 里面运行 `'吉'.charAt(0)`可以正确获得 '吉', 请问下阮老师, 是不是at() 方法被合并到 charAt() 里了还是怎么说

**Comment by ruanyf** [comment]
这个方法被取消了，我忘了删掉。现在已经删了这个部分。

另外，文章里面的那个字，不是“上士下口”，而是“上土下口”。
