### ISSUE TITLE
中文排版建议

### ISSUE THREAD

**Issue by u2** [ruanyf/es6tutorial#74]
https://github.com/sparanoid/chinese-copywriting-guidelines

建议遵循中文排版一些规则，暂时发现的问题：
- 中文英文的空格问题。

> ## 工具
> 
> | 倉庫 | 語言 |
> | --- | --- |
> | [vinta/paranoid-auto-spacing](https://github.com/vinta/paranoid-auto-spacing) | JavaScript |
> | [huei90/pangu.node](https://github.com/huei90/pangu.node) | Node.js |
> | [huacnlee/auto-correct](https://github.com/huacnlee/auto-correct) | Ruby |
> | [sparanoid/space-lover](https://github.com/sparanoid/space-lover) | PHP (WordPress) |
> | [hotoo/pangu.vim](https://github.com/hotoo/pangu.vim) | Vim |

**Comment by appleboy** [comment]
:+1:

**Comment by ruanyf** [comment]
我思考过这个问题。现在的决定是，写作过程中不用空格（为了提高速度），后期排版输出可以考虑增加空格。
