### ISSUE TITLE
module中this的指向

### ISSUE THREAD

**Issue by wbc0301** [ruanyf/es6tutorial#744]
阮老师好：最近在拜读你的书ES6，收益匪浅，纸质书也已经购买过。不过发现有个地方不太明白：
let const 一章节的Global那一段，讲到：

> Node 模块和 ES6 模块中，this返回的是当前模块。

但是在22章讲到module的时候，讲到：

> ES6 模块之中，顶层的this指向undefined，即不应该在顶层代码使用this。

我在浏览器中简单的实验了一下，发现指向的是：undefined。看到这里我不禁有些小激动，能发现您写的书中有错误，真让人兴奋。可是回想一下是不是我理解的不够透彻或者不全面，还请阮老师有空的时候能给指正一下。谢谢！

**Comment by ruanyf** [comment]
模块内部（class 代码区块内部）的`this`指向当前模块。

模块文件的顶层`this`，指向 undefined。

```javascript
this // undefined

class foo {
  constructor() {
     this // 当前模块
  }
}
```
