### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by tulinfneg** [ruanyf/es6tutorial#746]
class A {
  constructor() {
    console.log(new.target.name);
  }
}
class B extends A {
  constructor() {
    super();
  }
}
new A() // A  ok
new B() // B  Cannot read property 'name' of undefined

**Comment by Maecenas** [comment]
> Class 内部调用new.target，返回当前 Class。
> 需要注意的是，子类继承父类时，new.target会返回子类。

http://es6.ruanyifeng.com/#docs/class#new-target-属性

Chrome v69、Node v10.9.0 成功，请附上相应的环境以供复现。

不知道阮老师能不能设置一下 [Issue Template](https://github.com/ruanyf/es6tutorial/community) 呢？也可以开一个 Issue 请求 PR。@ruanyf

**Comment by ruanyf** [comment]
@tulinfneg 你的环境是什么？我得不到这个结果。

@Maecenas 这是教程，不是软件，好像很难有固定的模板。

**Comment by tulinfneg** [comment]
@ruanyf   经过 babel  编译后的结果 

var A = function A() {
     _classCallCheck(this, A);

     console.log(new.target.name);
};

var B = function (_A) {
     _inherits(B, _A);

     function B() {
          _classCallCheck(this, B);

          return _possibleConstructorReturn(this, (B.__proto__ || Object.getPrototypeOf(B)).call(this));
     }

     return B;
}(A);

new A(); // A ok
new B(); // B Cannot read property 'name' of undefined

**Comment by ruanyf** [comment]
Babel 很难百分之百符合规格，这本教程不考虑 Babel。

如果原生支持某种语言，就不要在用 Babel 转了。

**Comment by tulinfneg** [comment]
@ruanyf  好的  谢谢

**Comment by hax** [comment]
@tulinfneg babel 7.0+ 才支持 new.target。

**Comment by tulinfneg** [comment]
@hax 多谢
