### ISSUE TITLE
网站上 第4章第一节文字错误

### ISSUE THREAD

**Issue by leyeee** [ruanyf/es6tutorial#747]
![image](https://user-images.githubusercontent.com/42109822/45463695-df2ea980-b73f-11e8-8d2b-d88f5b476dd1.png)

上面文字说有6种方法，下面代码中只有5种

**Comment by XGHeaven** [comment]
还有一种直接表示呀...😑

leyeee <notifications@github.com> 于 2018年9月13日周四 10:35写道：

**Comment by ruanyf** [comment]
第6种在等号右边。
