### ISSUE TITLE
let例子解析错误(勘误)

### ISSUE THREAD

**Issue by meilihao** [ruanyf/es6tutorial#75]
http://es6.ruanyifeng.com/#docs/let,不存在变量提升:

``` js
let foo = 'outer';

function bar(func = x => foo) {
  let foo = 'inner';
  console.log(func()); // outer
}

bar();
```

上面的例子中, console.log()应该输出"inner"而不是"outer".

**Comment by hax** [comment]
traceur输出的是`inner`，babel输出的是`outer`。

**Comment by meilihao** [comment]
FF 40输出的是`inner`.

**Comment by hax** [comment]
看了一下，基本确认是 FF 的 bug。所以原文是正确的。

https://bugzilla.mozilla.org/show_bug.cgi?id=1022967
https://github.com/babel/babel/issues/710
