### ISSUE TITLE
诈骗提醒

### ISSUE THREAD

**Issue by willin** [ruanyf/es6tutorial#750]
@ipusi 爱普斯科技 <jenkins@pusi.site>

![2018-09-25 09 33 20](https://user-images.githubusercontent.com/1890238/45987807-1b4dfc80-c0a6-11e8-9fce-f4262b5f85d8.png)

这种无下限的行为严重恶心到我了。请 @ruanyf 注意保护自身合法权益。

**Comment by XGHeaven** [comment]
我也收到了，太恶心了。但是似乎没有什么好的办法阻止

Willin Wang <notifications@github.com> 于 2018年9月25日周二 09:34写道：

**Comment by ruanyf** [comment]
他是怎么拿到大家的邮件地址的？先拿到 contributors，然后根据每个 ID 从 GitHub API 获取公开的邮箱地址？

如果真是这样，确实好像无法阻止。

**Comment by hax** [comment]
似乎确实是支付宝的红包。他只是可以获得某种活动返现？
