### ISSUE TITLE
async章节中的await命令好像有一处

### ISSUE THREAD

**Issue by chang-shuai** [ruanyf/es6tutorial#752]
[await命令](http://es6.ruanyifeng.com/#docs/async#await-%E5%91%BD%E4%BB%A4)
原文内容
> 正常情况下，await命令后面是一个 Promise 对象。如果不是，会被转成一个立即resolve的 Promise 对象。
```javascript
async function f() {
  return await 123;
}

f().then(v => console.log(v))
// 123
```
> 上面代码中，await命令的参数是数值123，它被转成 Promise 对象，并立即resolve。

但是在我在Chrome控制台实验以后, 发现并不是这样
```javascript
const a = await 123

a
// 123
```
变量a并不是Promise对象, 原文中出现Promise对象, 应该是因为async关键字的. 因为前文说到, async function返回内置函数的时候, 会利用Promise.resolve()包装一下.

**Comment by ruanyf** [comment]
谢谢指出。原文确实有误，已经改正。
