### ISSUE TITLE
Promise章节中的基本用法

### ISSUE THREAD

**Issue by chang-shuai** [ruanyf/es6tutorial#753]
[Promise基本用法](http://es6.ruanyifeng.com/#docs/promise#%E5%9F%BA%E6%9C%AC%E7%94%A8%E6%B3%95)
原文中的示例代码:
```javascript
const promise = new Promise(function(resolve, reject) {
  // ... some code

  if (/* 异步操作成功 */){
    resolve(value);
  } else {
    reject(error);
  }
});
```
代码中`if`的判断条件是`异步操作成功` . 其实`... some code`中的代码可以是普通的同步代码, 也可以谁类似于Ajax的异步代码, `if` 的判断条件直接写`异步操作成功`容易产生误解. 以为`... some code`出的代码是异步执行的.

**Comment by ruanyf** [comment]
你说的有道理，但是这里写“some sync code”好像有点怪。

原文的写法问题也不是太大，所以我就不改了。
