### ISSUE TITLE
关于定义多行对象要不要加逗号的问题

### ISSUE THREAD

**Issue by iambinlin** [ruanyf/es6tutorial#755]
尊敬的阮大大，您好，就在多行定义的对象，在要不要加逗号这个地方有些个人的看法。JS既然是忽略空格地去编译执行，那么实际上在编译和执行阶段，多行与单行是没有区别的。反而在一些低版本浏览器（ie7/8）会不同程度出现bug，而我在正在阅读的《JavaScript专家编程》一书中，作者Mark Daggett不建议多行加逗号，否则会破坏一些运行环境。我在IE7环境下做了测试，
【 var obj = {
            name:'BillWang',
            age:18,
        }
        console.log(obj);】
按照上述写法会报错   --SCRIPT1028: 缺少标识符、字符串或数字--
如果有描述不当的地方，还请阮大大见谅。

**Comment by hax** [comment]
ES5就定义的行为有什么好讨论的？

如果你要支持老浏览器，用工具转换就可以了。

**Comment by bigbigDreamer** [comment]
> 尊敬的阮大大，您好，就在多行定义的对象，在要不要加逗号这个地方有些个人的看法。JS既然是忽略空格地去编译执行，那么实际上在编译和执行阶段，多行与单行是没有区别的。反而在一些低版本浏览器（ie7/8）会不同程度出现bug，而我在正在阅读的《JavaScript专家编程》一书中，作者Mark Daggett不建议多行加逗号，否则会破坏一些运行环境。我在IE7环境下做了测试，
> 【 var obj = {
> name:'BillWang',
> age:18,
> }
> console.log(obj);】
> 按照上述写法会报错 --SCRIPT1028: 缺少标识符、字符串或数字--
> 如果有描述不当的地方，还请阮大大见谅。
