### ISSUE TITLE
Promise then方法返回

### ISSUE THREAD

**Issue by LeeDou** [ruanyf/es6tutorial#756]
原文：then方法返回的是一个新的Promise实例（注意，不是原来那个Promise实例）。

若then方法的处理resolve或reject的函数，返回值不是一个新定义的promise实例，只是返回一个基本数据类型，这里的话then还是将其封装为一个新promise对象，并以返回值作为resolve的参数来处理吗？

**Comment by hax** [comment]
不清楚你问的是什么。建议上代码。

**Comment by LeeDou** [comment]
原文中then方法返回的是一个新的Promise实例
例如：
const p = new Promise((resolve, reject) => {...})
p.then(f1(){
  // 返回一个Promise实例 
  return new Promise(...);  // 
  // 返回一个常量
  return 1; 
  // 无返回值
}).then(...) // 链式继续调用then
对于f1的三种返回值，then 方法内部是不是通过Promise.resolve()函数对f1进行处理从而达到返回一个新的Promise实例的目的，或者说用的什么其他方法才能使then返回的是一个Promise实例。

**Comment by hax** [comment]
p.then() 直接马上就返回一个新的 pending 的 promise，跟 f1() 返回什么没有直接的关系，因为当时 f1 还没有被调用。

**Comment by LeeDou** [comment]
嗯嗯 我想问的是新的pending的Promise是怎么实现的

**Comment by hax** [comment]
@LeeDou 你找一个promise库自己看源码就知道了，比如 https://github.com/hax/my-promise/blob/master/src/Promise.js#L343-L387 。当然引擎的具体实现和库的实现是不一样的，但机制上是一致的。

**Comment by LeeDou** [comment]
嗯 好的，谢谢！
