### ISSUE TITLE
Set 和 Map 数据结构 对NAN的描述有问题

### ISSUE THREAD

**Issue by duoduoObama** [ruanyf/es6tutorial#757]
![image](https://user-images.githubusercontent.com/30836806/46855157-7f5a1a00-ce35-11e8-9a01-56a5b8088372.png)

![image](https://user-images.githubusercontent.com/30836806/46855214-a284c980-ce35-11e8-8fb9-0268a2ea09a7.png)

希望阮大哥能更正下

**Comment by hax** [comment]
最后一句可以改为：

因为 `x === NaN` 总是返回 false，即使 x 的值是 NaN。

**Comment by ruanyf** [comment]
@duoduoObama 看下面这一段。

> NaN is considered the same as NaN (even though NaN !== NaN).

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set#Value_equality
