### ISSUE TITLE
字符串的扩展（勘误） 

### ISSUE THREAD

**Issue by howiefh** [ruanyf/es6tutorial#76]
http://git.io/vsQ4i

> 如果大括号中的值不是字符串，将按照一般的规则转为字符串。不如，大括号中是一个对象，将默认调用对象的toString方法。

文中“不如”应该是“比如”吧。

> tag函数所有参数的实际值如下。
>     第一个参数：['Hello ', ' world ']
>     第二个参数: 15
>     第三个参数：50

第一个参数是否应该是 `['Hello ', ' world ', '']

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
