### ISSUE TITLE
建议增加对“export default”值修改的说明。

### ISSUE THREAD

**Issue by LongTengDao** [ruanyf/es6tutorial#763]
在《ECMAScript 6 入门 - 23.Module 的加载实现 - 2. ES6 模块与 CommonJS 模块的差异》中，顺带提到了 `import` 导入的变量值，会随着导出模块中的修改而变动的特性：

>   ```js
>   // lib.js
>   export let counter = 3;
>   export function incCounter() {
>     counter++;
>   }
>   
>   // main.js
>   import { counter, incCounter } from './lib';
>   console.log(counter); // 3
>   incCounter();
>   console.log(counter); // 4
>   ```

那么对于 `export defaut` 导出的值，情况会如何呢？

```js
// lib.js
let v = 0;
export default v;
v = 1;

// main.js
import v from './lib';
console.log(v); // ?
```

这种情况下会输出 `0` 还是 `1`？又或者 `default` 是不允许修改的，会报错（编译期？运行时？）？
谢谢！

**Comment by ruanyf** [comment]
default 也是一样的，不必专门讨论吧。

**Comment by LongTengDao** [comment]
我本来以为是这样的：

```js
export var v = 'original'; // import v==='changed'

export { v as default }; // import v==='changed'
export default v; // import v==='changed'
export default (v); // import v==='original'
export default +v; // import v==='original'

v = 'changed';
```

没想到搭了一下服务器（Chrome 不允许本地测试 ES6 Module，所以比较麻烦一直没实测），经过在 Chrome 中实际测试，结果却是这样的：

```js
export var v = 'original'; // import v==='changed'

export { v as default }; // import v==='changed'
export default v; // import v==='original' 不同于 export { v as default }，不跟随改变
export default (v); // import v==='original'
export default v+''; // import v==='original'

v = 'changed';
```

---

另外，顺便测试了另一个比较容易误解的：

```js
export default function f () {};
typeof f // 'function'，而不是 'undefined'
```

这种时候，它其实相当于一个函数声明，而不是一定是表达式语法，哪怕是匿名的 `function` 也一样，这一点也是比较特殊的，所以：

```js
export default function (n) {
    return ()=>n;
}(1);
// 实际上是：
export default function (n) {
    return ()=>n;
};
(1);
```

@ruanyf
