### ISSUE TITLE
Proxy - set 返回布尔值，可以添加详细说明

### ISSUE THREAD

**Issue by nswbmw** [ruanyf/es6tutorial#765]
在使用 Proxy 的时候，set handler 没有返回布尔值报错：

```js
TypeError: 'set' on proxy: trap returned falsish for property 'xxx'
```

原因是：在严格模式下如果 set 不返回值会报这个错。
参考链接：

- https://github.com/GoogleChrome/proxy-polyfill/issues/20
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/set

这个可以在文中加个说明，目前并没有。

**Comment by ruanyf** [comment]
谢谢指出，已经加上了。
