### ISSUE TITLE
about super in class extends

### ISSUE THREAD

**Issue by Rangocold** [ruanyf/es6tutorial#766]
class A {
  constructor() {
    this.x = 1;
  }
}

class B extends A {
  constructor() {
    super();
    this.x = 2;
    super.x = 3;
    console.log(super.x); // undefined
    console.log(this.x); // 3
  }
}

let b = new B();
为什么super.x = 3的时候super就是当this来用
console.log(super.x); 的时候，this就变成了A.prototype
从代码上看，只是第一次对super对象进行写操作，第二次是对super对象进行读操作，是什么导致了这两次操作的实际对象不一样呢？能否详细说明写？
感激不尽

**Comment by ruanyf** [comment]
这个地方，我也不是很理解为什么这么设计。

只能说，规格是这么定的，`super`读的时候和写的时候，不是同一个对象。
