### ISSUE TITLE
关于 `docs/promise.md` 的「只有**异步操作**的结果，可以决定当前是哪一种状态」的问题

### ISSUE THREAD

**Issue by rovast** [ruanyf/es6tutorial#773]
文中对 promise 对象特点的描述第一点中有如下描述：

> 只有**异步操作**的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。

其中讲到，只有「异步操作」结果可以决定 promise 当前的状态，在后面的示例中有如下一个例子：

```js
let promise = new Promise(function(resolve, reject) {
  console.log('Promise');
  resolve();
});

promise.then(function() {
  console.log('resolved.');
});

console.log('Hi!');

// Promise
// Hi!
// resolved
```

其中 new 出的 promise 实例中并无异步操作，所以这一块是否需要更正？

_是否是直接调用了 resolve() 或者 reject() 就直接改变了状态，其实和内部的同步、异步关系不大_

**Comment by jimmylab** [comment]
我觉得这样理解更恰当，你觉得呢：
> 只有异步操作的**结果**，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。

整段如下：
> （1）**对象的状态不受外界影响**。Promise对象代表一个异步操作，有三种状态：pending（进行中）、fulfilled（已成功）和rejected（已失败）。只有异步操作的**结果**，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。这也是Promise这个名字的由来，它的英语意思就是“承诺”，表示其他手段无法改变。

**Comment by ruanyf** [comment]
Promise 状态确定是开发者指定的。但是，如果你用它来包装异步操作，那么只有异步操作可以决定它的状态。文中是这个意思。
