### ISSUE TITLE
移动端阅读优化

### ISSUE THREAD

**Issue by z2n** [ruanyf/es6tutorial#775]
在移动端阅读中途若想切换章节需要把屏滚到顶部才可进行, 这样操作很麻烦, 希望能让 `back to top` 在移动可见. 或者提供个按钮让目录从侧边弹出.

**Comment by ruanyf** [comment]
点击任一个小标题，就有 back to top 按钮。

倒是全书目录在页尾，可能不是很方便。后面会考虑侧边弹出。
