### ISSUE TITLE
Math.sign

### ISSUE THREAD

**Issue by enthural** [ruanyf/es6tutorial#782]
Math.sign = Math.sign || function(x) {
  x = +x; // convert to a number
  if (x === 0 || isNaN(x)) {
    return x;
  }
  return x > 0 ? 1 : -1;
};
你好，请问x如果是NaN,isNaN(x)返回ture，函数返回x,而不是Math.sign要求的NaN吧?????

**Comment by ruanyf** [comment]
我运行了一下，返回 NaN

**Comment by enthural** [comment]
好的，谢谢。我看错了。返回的是x
