### ISSUE TITLE
冒昧求解一下const [...a2] = a1;

### ISSUE THREAD

**Issue by bosens-China** [ruanyf/es6tutorial#785]
阮老师你在扩展运算符举了这个例子
const a1 = [1, 2];
// 写法二
const [...a2] = a1;
不过写法二我没有看懂这句话的意思，...不应该是展开么，a2上一句并未声明，使用扩展运算符，为什么不会出现“假死”，这个问题折磨许久了

**Comment by ruanyf** [comment]
这个跟 `let [a1, ...a2] = [1, 2, 3]` 和 `let [, ...a2] = [1, 2, 3]`是一个用法。
