### ISSUE TITLE
async函数的await命令后面，可以是 原始值（但不等同于同步操作）

### ISSUE THREAD

**Issue by xianshenglu** [ruanyf/es6tutorial#787]
![image](https://user-images.githubusercontent.com/23273077/50471689-d44b0c80-09f0-11e9-8cfc-aaab283506b2.png)

如上图，如题，我测试下面代码

```js
const async2 = async function () {
  const f1 = await 1
  const f2 = await 2
  console.log(f1.toString())
  console.log(f2.toString())
}
async2()
console.log(3)
```

结果如下图：

![image](https://user-images.githubusercontent.com/23273077/50471729-f8a6e900-09f0-11e9-8ed8-09c84f886920.png)

要不就是 加粗的地方，我理解有误？或者是有歧义？

> 可以是 Promise 对象和原始类型的值（数值、字符串和布尔值，**但这时等同于同步操作**）。

**Comment by ruanyf** [comment]
我改一下，这里是不太严谨。不过，只要用了 await，都是这个结果。
