### ISSUE TITLE
Symbol 值不能形成 class 私有方法，仍然可以被外部访问

### ISSUE THREAD

**Issue by xianshenglu** [ruanyf/es6tutorial#789]
http://es6.ruanyifeng.com/#docs/class#%E7%A7%81%E6%9C%89%E6%96%B9%E6%B3%95%E5%92%8C%E7%A7%81%E6%9C%89%E5%B1%9E%E6%80%A7

如图：

![image](https://user-images.githubusercontent.com/23273077/50537483-262f9600-0b9b-11e9-8ad2-fbbec9f817f0.png)

你看下面代码：
```js
const bar = Symbol('bar');
const snaf = Symbol('snaf');
class myClass{

  // 公有方法
  foo(baz) {
    this[bar](baz);
  }

  // 私有方法
  [bar](baz) {
    return this[snaf] = baz;
  }

  // ...
};
let ins1=new myClass()
ins1[Reflect.ownKeys(myClass.prototype)[2]] // 访问到了
```
我是在 https://stackoverflow.com/questions/22156326/private-properties-in-javascript-es6-classes 看到的，觉得这个实现确实是有问题的

**Comment by ruanyf** [comment]
谢谢提醒，已经加入教程了。https://github.com/ruanyf/es6tutorial/commit/46981f6b9ae4acbbbb474322b1c3ab04ab916c34
