### ISSUE TITLE
类的属性定义描述上下有歧义

### ISSUE THREAD

**Issue by codepandy** [ruanyf/es6tutorial#792]
在`Class的基本语法`一章中，在`类的实例`有如下描述：
```
与 ES5 一样，实例的属性除非显式定义在其本身（即定义在this对象上），否则都是定义在原型上（即定义在class上）。
```
这说的好像是：“如果不在this上定义属性，那么就是在prototype上的”。
但是在`实例属性的新写法`中又描述：
```
实例属性除了在constructor()方法里面定义，也可以直接写在类的最顶层。
```
如果直接看这段，我会理解成：“在class上定义的属性其实是定义在this上的，方法是在prototype上的”。
但是从上到下看下来，又感觉上下冲突，希望修改下。
我目前认为我的理解是对的：
```
在class上定义的属性其实是定义在this上的（和在contructor中定义在this上是一样的），方法是在prototype上的
```

**Comment by ruanyf** [comment]
《实例属性的新写法》指的是实例自身的属性。我改一下。

**Comment by codepandy** [comment]
@ruanyf 阮老师，不好意思，可能是我没表达清楚，我觉的是下面这句有问题。
```
与 ES5 一样，实例的属性除非显式定义在其本身（即定义在this对象上），否则都是定义在原型上（即定义在class上）。
```
按照《实例属性的新写法》，属性即使没有定义this上，不应该也是属于实例的，而不是在原型上的吗?

**Comment by ruanyf** [comment]
新的写法只是语法糖，实际上还是定义在 this 上面，只是这种写法省略了 this。
