### ISSUE TITLE
函数的扩展（作用域）中的小例子结果有笔误

### ISSUE THREAD

**Issue by html5s** [ruanyf/es6tutorial#798]
var x = 1;
function foo(x, y = function() { x = 2; }) {
  var x = 3;
  y();
  console.log(x);
}

原文中执行结果：
foo()  // 3
实际执行结果：
foo()  // 2

**Comment by html5s** [comment]
是基于webpack打包环境下执行的结果

**Comment by ruanyf** [comment]
请直接在 Chrome 控制台执行，不要经过 babel 转码。
