### ISSUE TITLE
第4章 字符串的扩展 关于 codePointAt方法的参数描述的疑惑

### ISSUE THREAD

**Issue by DazhiFe** [ruanyf/es6tutorial#800]
![image](https://user-images.githubusercontent.com/9132607/51658086-d7322080-1fe1-11e9-9534-01b91eb49d73.png)
作者你好，如图所示，“𠮷”的后两个字节不就是字符“a”了吗，怎么还会有第三个字符“a”的描述？

**Comment by ruanyf** [comment]
如果把`𠮷`看作两个字符，`a`不就是第三个字符吗
