### ISSUE TITLE
22. Decorator 还在stage-2

### ISSUE THREAD

**Issue by aladdin-add** [ruanyf/es6tutorial#805]
目录中前面的章节都是 ES6，会让人误以为 Decorator也是在ES6。可以考虑放入《28.最新提案》
![image](https://user-images.githubusercontent.com/13050025/51890001-e8aa6c80-23d5-11e9-94f2-353c6dea36d5.png)

**Comment by ruanyf** [comment]
这一章近期就会重写。主要是它基于 class，可以加深对 class 的理解。我考虑一下，是否搬迁位置。
