### ISSUE TITLE
关于class-extends的super

### ISSUE THREAD

**Issue by cassiehuang** [ruanyf/es6tutorial#812]
#### super 作为函数在子类构造函数内执行时
* 原文：注意，super虽然代表了父类A的构造函数，但是返回的是子类B的实例，即super内部的this指的是B，因此super()在这里相当于A.prototype.constructor.call(this)。
* 我的理解：A.prototype.constructor.call(this)将构造函数内的this传入，所以super内部的this就是构造函数内的this，即正在被创建的实例对象b，而不是类B
请帮忙指正，帮助我理解这段话，万分感谢

**Comment by ruanyf** [comment]
对，this 指的是 B 的实例。我改一下。

**Comment by cassiehuang** [comment]
* 原文: 上面代码中，new.target指向当前正在执行的函数。可以看到，在super()执行时，它指向的是子类B的构造函数，而不是父类A的构造函数。也就是说，super()内部的this指向的是B。
* 这个地方也是一样，super() 内部的this指向的是B的实例。还有一个不明白的地方是，new.target的指向和this我认为不存在关联，不能通过new.target来判断this，虽然看起来this._proto_constructor.name===new.target.name
