### ISSUE TITLE
关于class章节中this的指向

### ISSUE THREAD

**Issue by cassiehuang** [ruanyf/es6tutorial#813]
![image](https://user-images.githubusercontent.com/19901705/52769972-df273280-306c-11e9-8f62-5498b40621ad.png)

按照下面这段文字的理解，此时运行时的环境应该时Window，而不是undefined,实际执行时，解构赋值后，printName()内部的this是undefined

**Comment by dee-qi** [comment]
对，我也有这个疑问。这个例子来自阮一峰老师在参考文献中提到的[这篇文章](https://ponyfoo.com/articles/binding-methods-to-class-instance-objects)，按文中说法，这个函数被拿出来单独使用时，其执行上下文会莫名其妙的改变，也就是说既不是该实例环境，也不是方法运行所在环境（即全局环境）。具体的执行上下文到底是什么，我查阅了很多文献也没找到，希望有大佬找到能分享一下。

**Comment by ruanyf** [comment]
是这样的，class 内部是严格模式，this 从 window 变成 undefined。

我改一下原文。
