### ISSUE TITLE
提一个小小的笔误

### ISSUE THREAD

**Issue by xdlStrive** [ruanyf/es6tutorial#817]
第二章“let和const命令”中，第三节“const命令的基本用法”中有一段“_const声明的变量不得改变值，这意味着，const一旦声明变量，就必须立即初始化，不能留到以后赋值。_” 的描述， 个人感觉，这里的 “_const声明的' **变量** '_” 改为“**常量** ”更为准确。
ES6初学者，这个问题提的如有不对之处，还望指出！

**Comment by ruanyf** [comment]
这里改成“常量”，确实更符合 const 本意。但是，const 声明的对象，属性是可变的，写常量可能会有误导。而且，“变量”的写法，大家也能理解，就是值的引用，所以也就不改了。
