### ISSUE TITLE
关于class基本语法章节的class表达式的问题

### ISSUE THREAD

**Issue by dee-qi** [ruanyf/es6tutorial#818]
<img width="939" alt="default" src="https://user-images.githubusercontent.com/24741212/52952372-4ae80300-33bf-11e9-8524-1dafce5e6ed1.png">
如图，文中提到通过class表达式定义的类，其名字是MyClass。但用如下代码进行试验，不管是Me还是MyClass，其name的值都为"Me"，也就是说该类的名字应该是Me，该类只是被赋值给了一个名为MyClass的变量。我认为这里正确的表述应该是，“MyClass是一个指向名字为Me的类的引用，而且在类外只能通过MyClass来调用该类”。

```js
const MyClass = class Me {
    constructor() {
        console.log(MyClass.name) //Me
        console.log(Me.name) //Me
    }
}
console.log(MyClass.name) // Me
```

**Comment by ruanyf** [comment]
谢谢指出，我修改了一下原文。
