### ISSUE TITLE
关于《Class的继承》中mixin实现的问题

### ISSUE THREAD

**Issue by dee-qi** [ruanyf/es6tutorial#820]
<img width="741" alt="default" src="https://user-images.githubusercontent.com/24741212/53023926-1779a700-3499-11e9-8656-e181e571124e.png">
如图画红线部分，在定义mixin时，文中代码将传入的mixins的属性拷贝到了Mix类的prototype上，这样会导致该属性对于Mix类不再是实例属性而是静态属性，即所有Mix实例共享同一个该属性。我认为这是不符合预期的。

晚辈拙见，可作如下修改以达到预期效果。

```js
function mix(...mixins) {
    class Mix { 
        constructor() {
            for(let mixin of mixins) {
                copyProperties(this, mixin)
            }
        }
    }

    for (let mixin of mixins) {
        //copyProperties(Mix.prototype, mixin);
        copyProperties(Mix.prototype, Reflect.getPrototypeOf(mixin)); // 拷贝原型属性
    }

    return Mix;
}
```

**Comment by ruanyf** [comment]
静态属性是 Mix.foo，而  Mix.prototype.foo 依然可以在实例上读取。

**Comment by dee-qi** [comment]
> 静态属性是 Mix.foo，而 Mix.prototype.foo 依然可以在实例上读取。

其实我这里主要的疑惑是，在Mix.prototype上设置属性的话，用Mix类初始化的实例都会共享这个属性。一个实例修改这个属性，那么其他实例的这个属性也会跟着变动，我认为这样是不符合预期的

**Comment by ruanyf** [comment]
确实存在这个问题，我改一下。

**Comment by ruanyf** [comment]
我前面糊涂了，原文有问题。

```javascript
class Foo {
  bar () {}
}
```

上面代码中，`bar`是定义在`Foo.prototype`上面的。所以其实`copyProperties(Mix.prototype, mixin);`这一行是多余的，因为所有属性都定义在`Foo.prototype`上面。所以，完全可以把这一行删了，或者改成`copyProperties(Mix, mixin);`，把静态属性拷贝上去。

**Comment by ruanyf** [comment]
改成下面的实现，应该比较正确了。

```javascript
function mix(...mixins) {
  class Mix {
    constructor() {
      for (let mixin of mixins) {
        copyProperties(this, new mixin()); // 拷贝实例属性
      }
    }
  }

  for (let mixin of mixins) {
    copyProperties(Mix, mixin); // 拷贝静态属性
    copyProperties(Mix.prototype, mixin.prototype); // 拷贝原型属性
  }

  return Mix;
}
```
