### ISSUE TITLE
ES5难以继承原生构造函数（内置类）的原因

### ISSUE THREAD

**Issue by dee-qi** [ruanyf/es6tutorial#821]
<img width="992" alt="default" src="https://user-images.githubusercontent.com/24741212/53025758-7d1b6280-349c-11e9-9a8b-94f79939a2e9.png">
如图，文中提到“原生构造函数的this无法绑定，导致拿不到内部属性。”。我认为这里阮老师可能把形如`this.someProp = someValue`的实例属性和内部属性`internal property`两个概念弄混了。

内部属性的定义如下：
> **Internal properties**
    Exist only in the ECMAScript language specification. They are not directly accessible from JavaScript, but there might be indirect ways of accessing them. The specification writes the keys of internal properties in brackets. For example, [[Prototype]] holds the prototype of an object and is readable via Object.getPrototypeOf(). 

在[Speaking Javascript Chapter 28. Subclassing Builtins](http://speakingjs.com/es5/ch28.html)中提到，内置属性获取不到实际上是js解释器决定的。

另外，Subclassing Builtins一章也提到，ES5继承内置类的两大障碍就是
* 内置属性通常无法获取。
* 内置类的构造函数会忽略传入的this，返回的是一个新对象。

我认为阮老师也可以从这两个角度进行这方面的阐释。

**Comment by ruanyf** [comment]
Internal 和 builtin 在中文里面很难区分，我想表达的就是外部获取不到的属性。改了以后，恐怕还要额外解释，现在尽管不精确，但是能够理解。
