### ISSUE TITLE
generator.md 中关于 并行执行 的问题

### ISSUE THREAD

**Issue by Tenleft** [ruanyf/es6tutorial#822]
阮老师你好，在 ` （1）协程与子例程的差异 ` 中提到的 `并行执行` 换成 `并发执行` 是不是更好呢？

**Comment by ruanyf** [comment]
这里不能算“并发”，是同时处在执行态，但只有一个函数正在执行。我也不知道，用哪个词描述比较合适。

**Comment by zyhcool** [comment]
@ruanyf 
您好，这方面我也存在疑问

“并行执行”是指多个线程（函数）同时执行；
“并发执行”是指多个线程（函数）同时处于**待**执行状态，但是只有一个在执行，其余等待；
可以这么理解吗？

从 nodejs 的高并发来理解，为什么不是 nodejs 的**高并行**呢？我想就是因为 nodejs 支持大并发请求，但是这些海量请求只能一个个排队来获得“执行权”，而不是同时执行。

不知道我的理解可有偏差

**Comment by zyhcool** [comment]
所以按我的理解来说，我认为 @StephenZW 的想法有道理，“并发执行”好像更符合协程的理念

**Comment by facetothefate** [comment]
这里显然应该用并发（concurrency）而不是并行（parallelism）。
并行意指是同时执行，是有多个操作在同一时间段内执行。只有一个函数在执行的状态是不能称为并行的。
并发是一种结构，意指程序包含多个可以独立执行的部分。

显然，并发不是并行。并发的设计可以提供并行的基础，比如线程，也不必非要并行，一个时间片只执行一个任务，比如协程。

这方面，go 有个著名的talk concurrency is not parallelism
http://blog.golang.org/concurrency-is-not-parallelism 解释的很清楚了。

Zhifei Fang
