### ISSUE TITLE
关于 for 循环中使用let定义的变量所在作用域的问题

### ISSUE THREAD

**Issue by CodingYiyi** [ruanyf/es6tutorial#824]
原文如下（let和const命令章节）：

> for循环还有一个特别之处，就是设置循环变量的那部分是一个父作用域，而循环体内部是一个单独的子作用域。

```
for (let i = 0; i < 3; i++) {
  let i = 'abc';
  console.log(i);
}
// abc
// abc
// abc
```
换言之，for循环中的let，属于外层父作用域，我们知道，let修饰的变量重复声明是会报错的，按照文章说的i属于外层父作用域，那么我在外层再定义let i是会报错的。实则不然，怎么解释呢？
```
let i = 10;
for (let i = 0; i < 3; i++) { // 此处的 i 如果属于外层父作用域，那么就是let重复声明的问题了，但此处没报错
  let i = 'abc';
  console.log(i);
}
```

**Comment by ruanyf** [comment]
for 循环的循环变量只声明一次。请阅读规格的相关部分。

**Comment by jjmathy** [comment]
块级作用域，出了作用域就销毁了

**Comment by Liuxingwei** [comment]
此处的父作用域，说的并不是 for 循环的外部作用域，而是说 for (....) 的这个括号内是一个作用域，它是循环体的父作用域。
