### ISSUE TITLE
【建议】用户评论太多导致以为文章很长很长的错觉，建议换种方式折叠评论

### ISSUE THREAD

**Issue by vikyd** [ruanyf/es6tutorial#826]
【建议】用户评论太多导致以为文章很长很长的错觉，可能容易丧失读完的兴趣，建议换种方式折叠评论

**Comment by ruanyf** [comment]
现在用的是 Disqus ，好像已经对评论分页了。

**Comment by vikyd** [comment]
分页固然好，但我想的是默认不展开任何评论，因为连第 1 页我都觉得有点长了，例子：
http://es6.ruanyifeng.com/#docs/class-extends
