### ISSUE TITLE
ArrayBuffer 章节翻译错误

### ISSUE THREAD

**Issue by loohoo** [ruanyf/es6tutorial#827]
相对`重要`的字节排在后面的内存地址，相对`不重要`字节排在前面的内存地址，所以就得到了上面的结果。

我没看过英文版，我猜这里的重要不重要应该是翻译自于 significant`。
应该叫高位，低位

**Comment by ruanyf** [comment]
不是翻译错误，是我故意这样翻的。

我一直分不清，什么是高位，什么是低位。另一方面，个位数是相对最不重要的位。
