### ISSUE TITLE
文档描述错误

### ISSUE THREAD

**Issue by LoveNormalDay** [ruanyf/es6tutorial#831]
您好：
2.let 和 const 命令
![image](https://user-images.githubusercontent.com/16485250/54920021-2098e080-4f3d-11e9-9ab3-b78737165df7.png)

根据您之前写的JavaScript教程，这里if(false)虽然没有执行，但是内部函数f函数提升，但是提升的效果和变量提升一样，只是声明了var f，并没有给f赋值成函数，我测试了下运行效果，也是如此，麻烦您看一下
![image](https://user-images.githubusercontent.com/16485250/54919434-c0ee0580-4f3b-11e9-979b-18c85f32be08.png)

这是您写的JavaScript教程
![image](https://user-images.githubusercontent.com/16485250/54919676-66a17480-4f3c-11e9-8d89-19ae13d7e99c.png)

**Comment by 8pig** [comment]
ES5和ES6运行

请做环境区分

**Comment by ruanyf** [comment]
你下面的例子是函数赋值给一个变量，这与直接声明函数是不一样的，后者的整个定义都提升了。
