### ISSUE TITLE
文档描述有歧义

### ISSUE THREAD

**Issue by LoveNormalDay** [ruanyf/es6tutorial#834]
您好：
7.函数的拓展-1.函数参数的默认值-应用
![image](https://user-images.githubusercontent.com/16485250/55137662-87e8a780-516c-11e9-996d-c220a49e1aa5.png)

根据您的2个例子，应该是如果参数的默认值如果是另一个函数的运行结果，是在定义时已经执行；如果默认值是一个函数表达式，才是在运行时执行

**Comment by ruanyf** [comment]
不是啊，都是在运行时执行的。书里的例子应该看不出，你说的那一点啊。
