### ISSUE TITLE
关于`尾调用`和`模块化`的论证demo的疑问

### ISSUE THREAD

**Issue by JaredCen** [ruanyf/es6tutorial#835]
阮老师，您好。

我认为 `尾调用优化` 中您使用斐波拉契数列的例子有点不妥当，一个是该例子在低长度时不会堆栈溢出，而应该是程序超时；另一个是尾递归版本的斐波拉契数列效率提升不是因为尾调用优化而应该是函数调用次数变少。我写了篇文章来说明：https://www.jianshu.com/p/db220b0f4386
您在讲述 `ES6 模块与 CommonJS 模块的差异`中，用于论述 `CommonJS 模块输出的是值的拷贝` 的例子我认为是没有说服力的，我在这里也详述了原因：https://www.jianshu.com/p/1cfc5673e61d

十分喜欢看阮老师的博客，祝工作顺利。

**Comment by XGHeaven** [comment]
第一个例子我觉得用斐波那契来讲解尾递归的调用栈确实不太合适。

第二个我觉得是完全没问题的。

**Comment by ruanyf** [comment]
谢谢指出，我做了修改。
