### ISSUE TITLE
希望在《3.变量的解构赋值》里增加对象解构赋值原型对象的说明

### ISSUE THREAD

**Issue by LoveNormalDay** [ruanyf/es6tutorial#836]
您好：
![image](https://user-images.githubusercontent.com/16485250/55224534-b25d6200-524b-11e9-8a77-5019fa3d5e19.png)
在9.对象的拓展-解构赋值的这个例子里，x 能拿到o的原型对象的 x 属性值，这个在之前的
《3.变量的解构赋值》里没有提到，能不能麻烦您酌情加一下，因为如果不是看到这个例子，都不知道原来 x 可以拿到原型对象的属性值，谢谢。

**Comment by ruanyf** [comment]
谢谢指出，已经补上去了。
