### ISSUE TITLE
希望在《11.Symbol》增加一个区分Symbol('key')和Symbol.for('key')的例子

### ISSUE THREAD

**Issue by LoveNormalDay** [ruanyf/es6tutorial#837]
![image](https://user-images.githubusercontent.com/16485250/55318152-a8826b80-54a4-11e9-8ff6-f9979fd92cbb.png)
您好：
在11.Symbol-5.Symbol.for
您说了Symbol.for会在全局登记变量，Symbol不会，所以比如说s1是Symbol.for生成的，s2是Symbol生成的，两个是不相等。您如果有时间，可以加一下吗

**Comment by ruanyf** [comment]
截图里面的下面代码，不已经给出例子了吗。
