### ISSUE TITLE
Promise.resolve不带参数描述有歧义

### ISSUE THREAD

**Issue by LoveNormalDay** [ruanyf/es6tutorial#839]
您好：
15.Promise对象-8.Promise.resolve()

![image](https://user-images.githubusercontent.com/16485250/55460535-ca0a6100-5624-11e9-8473-e3b2f0988b73.png)

您这里提到了立即resolve的 Promise 对象，是在本轮“事件循环”（event loop）的结束时，而不是在下一轮“事件循环”的开始时。
因为是放到不带参数这一节里说明，我理解的是只有是Promise.resolve()生成的Promise对象的resolve才是在本轮循环结束时执行，但是经过测试，即使是new Promise()生成的对象也是同样的规则，我感觉这个应该单独拿出来讲，放到不带参数这一节里容易造成歧义

![image](https://user-images.githubusercontent.com/16485250/55460712-3e450480-5625-11e9-94d5-4f36795501c3.png)
![image](https://user-images.githubusercontent.com/16485250/55460737-4c932080-5625-11e9-8769-57dae5745814.png)

**Comment by ruanyf** [comment]
这个在前面《基本用法》里面提到过，不是这里第一次出现。但是，确实没有单独拿出来作为一节。
