### ISSUE TITLE
上下文两段话感觉有冲突，加括号是函数调用还是不加呢？

### ISSUE THREAD

**Issue by kangaroo711** [ruanyf/es6tutorial#846]
注意，扩展运算符如果放在括号中，JavaScript 引擎就会认为这是函数调用。如果这时不是函数调用，就会报错。

(...[1, 2])
// Uncaught SyntaxError: Unexpected number

console.log((...[1, 2]))
// Uncaught SyntaxError: Unexpected number

console.log(...[1, 2])
// 1 2
上面前两种情况都会报错，因为扩展运算符所在的括号不是函数调用，而第三种情况console.log(...[1, 2])就不会报错，因为这时是函数调用。

**Comment by ahanser** [comment]
受教了受教了，感谢大佬

**Comment by ruanyf** [comment]
我改了一下，现在表达应该更清楚了。

**Comment by kangaroo711** [comment]
> 我改了一下，现在表达应该更清楚了。

是的，感谢

**Comment by facetothefate** [comment]
(...[1, 2, 3]) 是错误的语法，应该报unexpected token ... 错
你用的浏览器大概有bug。

chrome Version 74.0.3729.108 (Official Build) (64-bit)

(...[1,2,3])
VM78:1 Uncaught SyntaxError: Unexpected token ...

Zhifei Fang
