### ISSUE TITLE
clone 到本地后无法查看

### ISSUE THREAD

**Issue by linyongfu2013** [ruanyf/es6tutorial#85]
clone 到本地后，点击index.html 无法查看，浏览器弹出js提示框：
JavaScript 提醒：Opps! can't find the sidebar file to display!

然后是一个空白页面。

**Comment by ruanyf** [comment]
起一个HTTP服务

**Comment by luffy2333** [comment]
备注下：如在IIS上部署，需要设置MIME类型支持markdown文件格式。
文件扩展名：md
MIME类型：text/x-markdown
