### ISSUE TITLE
md 语法高亮语言可用 js 别名

### ISSUE THREAD

**Issue by waitingsong** [ruanyf/es6tutorial#861]
目前代码块的语法高亮语言使用的是 `javascript` ， 可使用别名 `js` 。这样就少打些字了。

- [github 语法高亮](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)
- [语法高亮语言及其别名](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml)

**Comment by ruanyf** [comment]
不考虑这样做。

原因有两个：

（1）保证所有的 Markdown 解析器都能处理这些文档，所以要使用最通用的语言名称。

（2）项目的用法应该统一，如果一种语言有两种名称，就不可避免会出现混用现象。
