### ISSUE TITLE
在线阅读的宽度不够

### ISSUE THREAD

**Issue by shanlanCoding** [ruanyf/es6tutorial#865]
123

**Comment by zjgpolaris** [comment]
不大发到付

**Comment by Maecenas** [comment]
这是一个 feature 吧。在阅读时尽量要避免过长的行：眼球在换行时速度慢会导致阅读速度变慢，而相邻的文字视觉上也不相邻，这不利于理解。

**Comment by shanlanCoding** [comment]
翻了下里是的问答，作者回复说等以后重构页面。所以我认为这个是一个bug，而不是一个特色呢。




------------------ 原始邮件 ------------------
发件人: "Xiang Li"<notifications@github.com>; 
发送时间: 2019年5月31日(星期五) 晚上7:27
收件人: "ruanyf/es6tutorial"<es6tutorial@noreply.github.com>; 
抄送: "两载"<291637732@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ruanyf/es6tutorial] 在线阅读的宽度不够 (#865)




这是一个 feature 吧。在阅读时尽量要避免过长的行：眼球在换行时速度慢会导致阅读速度变慢，而相邻的文字视觉上也不相邻，这不利于理解。
 
&mdash;

**Comment by ruanyf** [comment]
这边应该不会改动页面了，后面整个教程会考虑搬迁到 https://wangdoc.com/
