### ISSUE TITLE
关于Proxy一章，Proxy实例方法get讲解中的例子

### ISSUE THREAD

**Issue by ghost** [ruanyf/es6tutorial#866]
阮老师好，在阅读Proxy一章时，有个利用get操作拦截实现生成各种DOM节点的通用函数的例子。关于这个例子有点疑问向您请教。
我尝试自己实际操作一遍后发现，如果将最后一句`document.body.appendChild(el);`换成`console.log(el);`，其他代码不变（新建dom代理器和初始化el节点的代码都相同）。想要在控制台去查看el节点，就会发生崩溃。如下图
![image](https://user-images.githubusercontent.com/26135245/58695966-34434600-83c9-11e9-8c25-d400e2c233ee.png)
这是什么原因呢？我一直没想明白？引发浏览器崩溃的原因会是什么造成？

**Comment by ruanyf** [comment]
我可以正常打印，你换个机器试试。

**Comment by ghost** [comment]
阮老师打扰您了，打印是可以正常打印的，但在控制台点开查看dom结构时，当点开`ul`节点就会发生崩溃。我用windows和mac的chrome都尝试了，都会发生崩溃。

**Comment by ruanyf** [comment]
我点击展开是正常了，就不截图了。你换一台机器试试。
