### ISSUE TITLE
数组的扩展-扩展运算符

### ISSUE THREAD

**Issue by cby0310** [ruanyf/es6tutorial#870]
http://es6.ruanyifeng.com/#docs/array#%E6%89%A9%E5%B1%95%E8%BF%90%E7%AE%97%E7%AC%A6
数组的扩展-扩展运算符-第二段代码：
function push(array, ...items) {
  array.push(...items);
}
第一行的“...items”是不是多了“...”?
现在的情况是转换了两次数组

**Comment by Linchaojin** [comment]
// 有...
push(arr, 1, 2, 3) => [ 1, 2, 3 ]
// 无...
push(arr, 1, 2, 3) => [ [ 1, 2, 3 ] ]
items在function里面为数组类似，没有操作符的话，会直接作为一个元素被push进去，加了...的话就会单独将item的元素push进去。
