### ISSUE TITLE
await 继发/并发

### ISSUE THREAD

**Issue by thbgh** [ruanyf/es6tutorial#873]
![0](https://user-images.githubusercontent.com/9399517/60011573-a51a0d00-96ac-11e9-9ded-d42f6a38a906.png)
小白的问题:
两处写法 为何会不同 ?

**Comment by ruanyf** [comment]
await 有暂停效果，第一种写法相当于A完成后，才触发B。

**Comment by niexia** [comment]
第二种写法是开始就同时触发请求了，await 的是返回不是请求

**Comment by thbgh** [comment]
明白了,谢谢!
