### ISSUE TITLE
关于书中Generator函数章节例子替换

### ISSUE THREAD

**Issue by Yxiuchao** [ruanyf/es6tutorial#878]
我现是一个大学生，在学习老师您的ES6这本书中，在第三版书中16.6yield*表达式小节中有一个例子是使用yield*语句遍历完全二叉树，我认为此例子应当换成yield*语句遍历二叉树，因为完全二叉树只是二叉树的一种特殊，不具有普遍性，而且改为二叉树只是在生成二叉树的函数内多增加一。层判断，在make(array)函数中增加代码：（if(array.length==2）return new Tree(make(array[0],array[1],null))，可能这个建议并不影响来时您让我们理解的关于这个yield*表达式，但是我认为这个还是有必要的（因为如果一开始每台看清是完全二叉树的话，很容易进行报错，觉得应该改进一下，已适用于普遍），感谢老师能采纳。谢谢

**Comment by ruanyf** [comment]
这里是为了演示 Generator 语法，不是为了演示算法。

例子越简单越好，就不考虑完整的二叉树情况了。读者自动修改，难度也不大。
