### ISSUE TITLE
Module 的加载实现一章中关于export输出建议给一个例子

### ISSUE THREAD

**Issue by bosens-China** [ruanyf/es6tutorial#883]
> 模块之中，可以使用import命令加载其他模块（.js后缀不可省略，需要提供绝对 URL 或相对 URL），也可以使用export命令输出对外接口。

上面引用你的话，不过如果`script`标签使用了`module`属性，不就形成了模块作用域么，如果在这个作用域使用`export`输出一个值，在其他`script`中又该如何获取呢？
``` html
<script type="module">
export default 5;
</script>
```
比如上面这段

**Comment by ruanyf** [comment]
嵌入页面的模块，通常不用 export。只有引用外部模块时才使用，比如下面这样。

```
<script type="module" src="../foo.js">
```
