### ISSUE TITLE
关于Map的疑问

### ISSUE THREAD

**Issue by elainema** [ruanyf/es6tutorial#887]
http://es6.ruanyifeng.com/#docs/set-map
注意，只有对同一个对象的引用，Map 结构才将其视为同一个键。这一点要非常小心。
const map = new Map();

map.set(['a'], 555);
map.get(['a']) // undefined
这个demo没太理解，阮老师有空方便解释一下吗？感谢

**Comment by snsart** [comment]
map.set(['a'], 555);
map.get(['a']);
这两个['a']不是同一个对象，执行['a']会创建一个新的数组对象。改成下面这样就行了:
let a=['a'];
map.set(a,555);
map.get(a);

**Comment by hax** [comment]
有一些新的提案正在tc39讨论中以解决这类问题：https://github.com/tc39/proposal-collection-normalization

**Comment by ruanyf** [comment]
@elainema  两个字面量`['a']`，是不同的实例。
