### ISSUE TITLE
案例错误问题（函数的扩展 ）

### ISSUE THREAD

**Issue by Laule** [ruanyf/es6tutorial#888]
【错误案例一】
var x = 1;

function foo(x = x) {
  // ...
}

foo() // ReferenceError: x is not defined

// 实际运行中，并不会报错

var x = 1;

function foo(x = x) {
    console.log(x)
}

foo() // undefined

【错误案例二】
let foo = 'outer';

function bar(func = () => foo) {
  let foo = 'inner';
  console.log(func());
}

bar(); // outer

【输出 inner】

【错误案例三】
function bar(func = () => foo) {
  let foo = 'inner';
  console.log(func());
}

bar() // ReferenceError: foo is not defined

【输出 inner】

【错误案例四】
var x = 1;
function foo(x, y = function() { x = 2; }) {
  var x = 3;
  y();
  console.log(x);
}

foo() // 3
x // 1

【输出 2 ， 空】

**Comment by ruanyf** [comment]
请到其他浏览器试试看。
