### ISSUE TITLE
为书籍开个打赏功能吧

### ISSUE THREAD

**Issue by iwmaker** [ruanyf/es6tutorial#889]
非常感谢您的《ECMAScript 6 入门》，简洁全面，循序渐进。只是本人，也许存在相当一部分人，对于 IT 书籍更习惯电子版而不是纸质。所以一个打赏功能会使我们更为心安的随时查阅使用

**Comment by sunnynudt** [comment]
我已经买个本纸质版的表示支持。

**Comment by ruanyf** [comment]
主要是觉得，打赏的人寥寥无几，放个二维码影响页面整洁。
