### ISSUE TITLE
关于es6块级作用域问题

### ISSUE THREAD

**Issue by kuang-lingxi** [ruanyf/es6tutorial#890]
老师我有一个问题, 在书中写到块级作用域之中, 函数声明的行为类似于let, 在块级作用域之外不可引用, 但是我在node环境下也可以在外面访问块级作用域里面声明的函数, 比如下面这段代码
```js
if(true) {
  function f() {
    console.log('hello')
  }
}

f();//hello
```
请问是node环境对于es6的实现不够标准还是我对这句话的意思理解有误还是我的代码哪里有问题呢。。如果是node环境对于es6的实现不够标准, 那么如何去实现一个完全遵循es6实现的环境呢？希望得到老师的解答。

**Comment by ruanyf** [comment]
不算错，Node 实现了标准对浏览器的要求。https://stackoverflow.com/questions/31419897/what-are-the-precise-semantics-of-block-level-functions-in-es6
