### ISSUE TITLE
Iterator的章节中说明Iterator不可重用

### ISSUE THREAD

**Issue by bigbird231** [ruanyf/es6tutorial#894]
let map=new Map([[1,1],[2,2]]);
    let keys=map.keys();
    for(let i of keys){
        console.log(i);
    }
    console.log("-------");
    //当iterator消耗完之后再遍历就无效了
    for(let i of keys){
        console.log(i);
    }

**Comment by ruanyf** [comment]
for...of 循环不存在这个问题。
