### ISSUE TITLE
关于String上的raw方法，源码实现有误

### ISSUE THREAD

**Issue by liuzw1024** [ruanyf/es6tutorial#895]
// 关于String上的raw方法，源码实现有误
String.raw = function (strings, ...values) {
  let output = '';
  let index;
  // 最终长度应取决于raw，而并非values
  const len =  strings.raw.length - 1;
  for (index = 0; index < len; index++) {
    output += strings.raw[index] + values[index];
  }

  output += strings.raw[index]
  return output;
}

**Comment by ruanyf** [comment]
原来的实现没有错，这里不需要加一个 `len` 变量。

**Comment by liuzw1024** [comment]
是有问题的，加len只是一个小性能的提升写法，可以尝试下当values值的量多余row的量的时候的情况，与预期结果不符，如



------------------ 原始邮件 ------------------
发件人: "Ruan YiFeng"<notifications@github.com>; 
发送时间: 2019年8月13日(星期二) 下午5:14
收件人: "ruanyf/es6tutorial"<es6tutorial@noreply.github.com>; 
抄送: "刘志伟"<335035371@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ruanyf/es6tutorial] 关于String上的raw方法，源码实现有误 (#895)




原来的实现没有错，这里不需要加一个 len 变量。

**Comment by liuzw1024** [comment]
------------------ 原始邮件 ------------------
发件人: "Ruan YiFeng"<notifications@github.com>;
发送时间: 2019年8月13日(星期二) 下午5:15
收件人: "ruanyf/es6tutorial"<es6tutorial@noreply.github.com>;
抄送: "刘志伟"<335035371@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ruanyf/es6tutorial] 关于String上的raw方法，源码实现有误 (#895)




Closed #895.
