### ISSUE TITLE
似乎有错别字

### ISSUE THREAD

**Issue by LiuCaptain** [ruanyf/es6tutorial#906]
链接：http://es6.ruanyifeng.com/#docs/class#%E7%B1%BB%E7%9A%84%E7%94%B1%E6%9D%A5
第4点静态属性
“”目前，只有这种写法可行，因为 ES6 明确规定，Class 内部只有静态方法，没有静态属性。现在有一个提案提供了类的静态属性，写法是在实例属性法的前面，加上static关键字。“”这段话中的“实例属性法”

**Comment by LongTengDao** [comment]
应该是多了个“法”字
