### ISSUE TITLE
《Generator函数语法》章节第5小节

### ISSUE THREAD

**Issue by Kavelaa** [ruanyf/es6tutorial#910]
> 如果 Generator 函数内部有try...finally代码块，且正在执行try代码块，那么return方法会推迟到finally代码块执行完再执行。
>```
>function* numbers () {
>  yield 1;
>  try {
>    yield 2;
>    yield 3;
>  } finally {
>   yield 4;
>    yield 5;
>  }
>  yield 6;
>}
>var g = numbers();
>g.next() // { value: 1, done: false }
>g.next() // { value: 2, done: false }
>g.return(7) // { value: 4, done: false }
>g.next() // { value: 5, done: false }
>g.next() // { value: 7, done: true }
>```
> 上面代码中，调用return方法后，就开始执行finally代码块，然后等到finally代码块执行完，再执行return方法。

上面是原文，因为我同时也在看阮老师的网道《错误处理机制》那一块，所以es6这边的
> 调用return方法后，就开始执行finally代码块，然后等到finally代码块执行完，再执行return方法。

应该是表述不准的，return方法是执行了的，但是结果会在finally代码块执行完之后再返回。
这是我的测试代码：
```
let count = 1;
function* numbers () {
  try {
    yield count;
  } finally {
    yield count+1;
  }
}
var g = numbers();
console.log(g.next());
console.log(g.return(count));
console.log(g.next());
```
实际上和网道中《错误处理机制》的描述是一致的。

**Comment by ruanyf** [comment]
谢谢指出，已经更正了。
