### ISSUE TITLE
阮大佬，10月份最新今个提案出来了，貌似都很不错，是不是要更新一波教程了？

### ISSUE THREAD

**Issue by 1316346949** [ruanyf/es6tutorial#916]

**Comment by ruanyf** [comment]
stage 4 的提案都写进教程了，stage 3 也写了大部分，比如`Promise.any()`。https://github.com/ruanyf/es6tutorial/blob/gh-pages/docs/promise.md#promiseany

**Comment by 1316346949** [comment]
前几天新进的几个stage1的感觉很不错的，大佬有兴趣可以看看

**Comment by 1316346949** [comment]
https://github.com/tc39-transfer/proposal-readonly-collections

**Comment by ruanyf** [comment]
stage 0～2 的提案都是不稳定的， 语法随时可能变，也可能撤案，所以不考虑写进教程。
