### ISSUE TITLE
ES5没有块级作用域，为什么还说ES5规定不能在块级作用域声明函数呢？

### ISSUE THREAD

**Issue by heweixiao** [ruanyf/es6tutorial#918]
阮大佬，有个问题请教一下。在《let和const命令》章节的“块级作用域”中，首先提到“ES5 只有全局作用域和函数作用域，没有块级作用域”，然后后面有提到“ES5 规定，函数只能在顶层作用域和函数作用域之中声明，不能在块级作用域声明”。感觉这两句话矛盾了呢，ES5既然没有块级作用域，那么为什么还会有ES5不能在块级作用域声明函数这一说呢？

**Comment by ruanyf** [comment]
后一个块级作用域，指的是大括号的代码块。我想想怎么表达更清晰一点。

**Comment by heweixiao** [comment]
好的，这样子我就理解了，谢谢阮大佬。
