### ISSUE TITLE
asyn函数返回的Promise对象then方法回调函数的执行时机

### ISSUE THREAD

**Issue by fengertao** [ruanyf/es6tutorial#919]
阮老师好:

"async 函数"章节中“async函数返回的 Promise 对象，必须等到内部所有await命令后面的 Promise 对象执行完，才会发生状态改变，除非遇到return语句或者抛出错误。也就是说，只有async函数内部的异步操作执行完，才会执行then方法指定的回调函数”。这段话和实测效果好像不一样。

在chrome v77的console执行以下程序：

```javascript
let myVar = ""

let asyncAccessURL = async function () {
  myVar = "landmark1"
  const f1 = await fetch('https://www.baidu.com');
  myVar = "landmark2"
  const f2 = await fetch('https://www.baidu.com');
  myVar = "landmark3"
  console.log(f1);
  console.log(f2);
};

asyncAccessURL().then(console.log(myVar))
```

按照本文的理解，console.log(myVar)应该输出"landmark3"。
而实测结果，console.log(myVar)输出为"landmark1"。
所以asyncAccessURL().then()应该是在async函数体内第一个await执行后就被callback了，而不是所有的await被执行后才被callback。

如果我希望asyncAccessURL().then()内的函数在asyncAccessURL()所有代码都执行完毕以后才执行(也就是console.log(f2)执行完毕后才执行)，应该怎样写？

**Comment by ruanyf** [comment]
`then()`的参数是函数。
