### ISSUE TITLE
示例代码的一个疑问

### ISSUE THREAD

**Issue by MinWest** [ruanyf/es6tutorial#922]
http://es6.ruanyifeng.com/#docs/class#%E5%AE%9E%E4%BE%8B%E5%B1%9E%E6%80%A7%E7%9A%84%E6%96%B0%E5%86%99%E6%B3%95
这里有如下代码片段，get value(){}, get是一个修饰符吗，或者这是一处编辑错误
get value() {
    console.log('Getting the current value!');
    return this._count;
}

**Comment by ruanyf** [comment]
https://wangdoc.com/javascript/stdlib/attributes.html#%E5%AD%98%E5%8F%96%E5%99%A8
