### ISSUE TITLE
关于模块导入导出的问题

### ISSUE THREAD

**Issue by lxfriday** [ruanyf/es6tutorial#925]
阮老师您好

ref [ES6-模块加载-CommonJS-模块](http://es6.ruanyifeng.com/#docs/module-loader#ES6-%E6%A8%A1%E5%9D%97%E5%8A%A0%E8%BD%BD-CommonJS-%E6%A8%A1%E5%9D%97)

使用 webpack 打包出来的结果和书中不一致。

**环境**
```
"webpack": "^4.41.2",
"webpack-cli": "^3.3.9"
```

**问题**
模块使用 `module.exports = xx` 导出，在另一个模块导入的时候，下面两种导入的结果是一致的

```js
// mod.js
module.exports = 'xx'

// app.js
import mod1 from './mod'
import * as mod2 from './mod'

console.log(mod1)
console.log(mod2)

// xx
// xx
```

阮老师您的代码中是这么写的

```js
// c.js
module.exports = function two() {
  return 2;
};

// es.js
import foo from './c';
foo(); // 2

import * as bar from './c';
bar.default(); // 2
bar(); // throws, bar is not a function
```

---

而下面的结果和书中类似

```js
// mod.js
export default 'xx'

// app.js
import mod1 from './mod'
import * as mod2 from './mod'

console.log(mod1)
console.log(mod2)

// xx
// Module {default: "xx", __esModule: true, Symbol(Symbol.toStringTag): "Module"}
```

上面的结果说明，webpack 处理的时候，

-  `module.exports` 导出的，`import x from 'mod'` 和 `import * as x from 'mod'` 相同
-  `export default` 导出的，`import x from 'mod'` 和 `import * as x from 'mod'`  不同，后者是整个模块的内容

**Comment by ruanyf** [comment]
这部分过时了，Node.js 已经明确了，commonjs 和 es6 模块不得混用。也就是说，不能用 import 命令去加载 commonjs 模块。

我后面修订的时候，会把这部分删除。

**Comment by hax** [comment]
不是不能混用。

目前node.js 13里的experimental module特性是：
- esmodule可以用`import`加载commonjs模块
- commonjs模块不能用`require()`来加载esmodule，但可以用`import()`（动态import）加载esmodule。

不过我们不清楚node.js以后还会不会再改。

**Comment by lxfriday** [comment]
了解了
