### ISSUE TITLE
示例引用有误

### ISSUE THREAD

**Issue by JimFirst** [ruanyf/es6tutorial#926]
![image](https://user-images.githubusercontent.com/19401131/68445976-5eb9ea80-0216-11ea-8abf-8a480a06db59.png)
const x = 1;

console.log(x === window.x); //false
这个示例引用有误，const x = 1不管是不是在模块中，都不会挂载到window下，而且在scope中

**Comment by ruanyf** [comment]
这里是想从反面提醒大家，不要在`window`上面去获取`x`，这是不会成功的。
