### ISSUE TITLE
“暂时性死区”第一例中似乎存在误导描述

### ISSUE THREAD

**Issue by jacty** [ruanyf/es6tutorial#932]
1.【let 和 const 命令】章节里头【暂时性死区】部分的第一个例子中，是否在外部声明 var tmp = 123 似乎对执行结果没有影响吧？而 ‘上面代码中，存在全局变量tmp，但是块级作用域内let又声明了一个局部变量tmp，导致后者绑定这个块级作用域’ 这句话中的‘导致’似乎容易被理解成 var 声明的存在协作出了暂时性死区的现象。所以，是不是这个例子中可以去掉 var 声明部分？似乎它是多余的论据。 
2.另外该部分最后一段说‘只要一进入当前作用域，所要使用的变量就已经存在了，但是不可获取’。没太理解‘已经存在’是什么意思？是说我打算声明变量 a， 然后 a 在声明前是已经存在的，但是不可获取么？这似乎有点‘未卜先知’了吧，没太理解这里，麻烦指点一二。 多谢阮老师。

**Comment by ruanyf** [comment]
https://wangdoc.com/javascript/basic/grammar.html#%E5%8F%98%E9%87%8F%E6%8F%90%E5%8D%87
