### ISSUE TITLE
关于浅拷贝部分发现一个新数组未同步更新的例子，请阮老师指教

### ISSUE THREAD

**Issue by jacty** [ruanyf/es6tutorial#934]
【数组的扩展】-【扩展运算符】-【扩展运算符的运用】-【合并数组】中最末尾的描述：
“如果修改了原数组的成员，会同步反映到新数组。“。 这段描述或许不是很严谨。请老师看下如下的截图。
<img width="259" alt="a" src="https://user-images.githubusercontent.com/4190959/70969732-820a6c00-20d7-11ea-946c-67424b426e32.png">

修改原数组中成员对象元素的属性值，新数组会发生更新。但是将原数组的成员直接修改成其他数据类型，则新数组不发生更新。所以，原文描述中最后一句是有纰漏的，个人理解。

<img width="292" alt="b" src="https://user-images.githubusercontent.com/4190959/70969743-85055c80-20d7-11ea-8b21-d49a2a321f29.png">

另外，尝试了一下将原数组的成员直接修改成其他数据类型，再修改会对象类型，新数组也是不发生更新的。所以，我在想是不是因为修改成员类型后，新老数组之间的引用就已经断开了，无法修复了？

**Comment by ruanyf** [comment]
对于浅拷贝来说，这是很自然的事：可以修改引用指向的值，但不能把引用改掉。

我来改一下，改得更明白一些。
