### ISSUE TITLE
class语法实力属性定义的更改

### ISSUE THREAD

**Issue by 1316346949** [ruanyf/es6tutorial#935]
![image](https://user-images.githubusercontent.com/24400797/71061401-dcbcca00-21a2-11ea-86c3-ea8cc0596e1f.png)

**Comment by 1316346949** [comment]
class A{

a=1

constructor(){  this.b = 2  }

}
阮老师 class A的a和b写法是不一样的 a赋值方法事 [[Define]] b写法事[[Set]] 这个事最新stage3的坑爹提案更改的

**Comment by 1316346949** [comment]
第一种写法完全覆盖父类的a属性比如父类属性有个set a(){ .... }，b的赋值方法则会掉用父类的
set b(){  ...  }

**Comment by ruanyf** [comment]
谢谢提醒，我看一下。这个属于底层的赋值实现原理了。
