### ISSUE TITLE
第九章第一节扩展运算符

### ISSUE THREAD

**Issue by mercurywang** [ruanyf/es6tutorial#941]
数组的扩展 -- 扩展运算符的应用 -- （2）合并数组
第一个例子描述道：「这两种方法都是浅拷贝，使用的时候需要注意。」

我个人理解使用`concat`方法进行深拷贝时，适用的情况是「对不包含引用对象的一维数组的深拷贝」，所以第一个例子应该是实现了深拷贝。

而第二个例子中的数组是由「引用类型」组成的，所以没有实现深拷贝。

请老师不吝赐教！

谢谢！

**Comment by ruanyf** [comment]
JavaScript 默认都是浅拷贝，复合类型的值全部为引用。深拷贝都是自己实现的。
