### ISSUE TITLE
字符串扩展>标签模板  示例错误

### ISSUE THREAD

**Issue by tans** [ruanyf/es6tutorial#942]
**[字符串扩展>标签模板](http://es6.ruanyifeng.com/#docs/string#%E6%A0%87%E7%AD%BE%E6%A8%A1%E6%9D%BF)**  中一开始的示例

```javascript
alert`123`
// 等同于
alert(123)
```

没有理解错，应该是这样才对吧

```javascript
alert`123`
// 等同于
alert(['123'])
```

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
