### ISSUE TITLE
async函数返回的 Promise 对象，不必等到内部所有await命令后面的 Promise 对象执行完，才会发生状态改变

### ISSUE THREAD

**Issue by joyful2** [ruanyf/es6tutorial#944]
阮老师好

原文： ‘async函数返回的 Promise 对象，必须等到内部所有await命令后面的 Promise 对象执行完，才会发生状态改变，除非遇到return语句或者抛出错误。也就是说，只有async函数内部的异步操作执行完，才会执行then方法指定的回调函数。’

这句话我的理解是async函数返回的 Promise 对象，不必等到内部所有await命令后面的 Promise 对象执行完，才会发生状态改变。 如下代码：先执行的是then回调，后面才执行setTimeout的
function timeout(ms) {
  setTimeout(() => {
    console.log(ms);
  }, ms);
 }

async function getTitle(ms) {
   await timeout(ms);
 
}
getTitle(1000).then((res)=> console.log('res',res))

谢谢！

**Comment by nineSean** [comment]
timeout函数返回一个Promise对象就符合预期了
