### ISSUE TITLE
`命令`，是否应该改为 `关键字`

### ISSUE THREAD

**Issue by qinhanlei** [ruanyf/es6tutorial#946]
建议使用**关键字**这个更合适的术语，如 TypeScript 官网文档所示：

[Variable Declarations](http://www.typescriptlang.org/docs/handbook/release-notes/typescript-1-4.html#let-declarations)

> Declaring a variable in JavaScript has always traditionally been done with the `var` **keyword**.

> By now you’ve figured out that var has some problems, which is precisely why let statements were introduced. Apart from the **keyword** used, let statements are written the same way var statements are.

**Comment by ruanyf** [comment]
关键字分成不同用途，有的是命令（delete），有的是语言结构（比如`if`），我想区分这两者。
