### ISSUE TITLE
weakMap用途的例子貌似有问题

### ISSUE THREAD

**Issue by notomorow** [ruanyf/es6tutorial#947]
阮老师，weakMap用途的例子貌似有问题
![企业微信截图_ba250152-e000-4e90-a10c-95745646aff3 (1)](https://user-images.githubusercontent.com/12589944/73156228-2391ce00-4118-11ea-83f6-2a035bb84794.jpg)

**Comment by hax** [comment]
你可以想象这段代码在一个 IIFE 里，当这段代码执行之后， myElement 这个绑定就不存在了。

**Comment by notomorow** [comment]
嗯，那如果是在IIFE环境中执行的，感觉这里用不用WeakMap都是一样的效果，即使不用WeakMap，如果节点删除了，那么相关的所有变量也会被回收。反正就是觉得这个例子有点怪，不是很恰当的那种。

**Comment by hax** [comment]
嗯，可能例子是需要再改进改进。

**Comment by ruanyf** [comment]
@notomorow 谢谢指出，确实有这个问题。

我改了一下，把引用删掉了，直接使用节点对象。
