### ISSUE TITLE
class继承里面的一个小demo答案是错误的

### ISSUE THREAD

**Issue by cfjin** [ruanyf/es6tutorial#950]
![image](https://user-images.githubusercontent.com/23311355/74135440-41d2f000-4c27-11ea-8f71-e8d1f2b63a68.png)

结果是
![image](https://user-images.githubusercontent.com/23311355/74135544-6dee7100-4c27-11ea-8b20-77e561b4cb10.png)

**Comment by ruanyf** [comment]
直接在 Node.js 运行。
