### ISSUE TITLE
对 find() (以及findIndex()和filter())的第三个参数的疑问

### ISSUE THREAD

**Issue by ykl124** [ruanyf/es6tutorial#951]
点击：[原文出处](https://github.com/ruanyf/es6tutorial/blob/5a465dda710bb1d16d97fe0783b6fcf0e7439d46/docs/array.md)

`find()`方法中说第3个参数arr 是指原数组，我试了一下，arr只返回了原数组的第一个成员。 
![image](https://user-images.githubusercontent.com/10691264/75010480-38b01180-54b8-11ea-9e3b-4a9a07725e31.png)

同理，和`find()`类似的`findIndex()``filter()`也是类似的

**Comment by ruanyf** [comment]
你理解错了。
