### ISSUE TITLE
本书的在线版本连接错误，希望尽快恢复

### ISSUE THREAD

**Issue by ChanMenglin** [ruanyf/es6tutorial#953]
本书的在线版本连接错误，连接到了其它网站，希望尽快恢复
http://es6.ruanyifeng.com/

**Comment by ruanyf** [comment]
我这里一切正常。

能否告知所在地区，网络服务商，以及是DNS劫持还是注入恶意脚本？

最后，使用加密版本访问 https://es6.ruanyifeng.com 是否正常？

**Comment by ChanMenglin** [comment]
加密版本(https://es6.ruanyifeng.com) 访问正常
非加密版本(http://es6.ruanyifeng.com/) 会跳转到其他网页（一个游戏网站）
应该是被劫持了，建议停用非加密版本
武汉电信网络

**Comment by ruanyf** [comment]
如果是 DNS 劫持，我无能为力。不过，HTTPS 访问正常，估计是你的网络服务商注入的脚本跳转。

我已经强制 HTTP 跳转 HTTPS 了，你再试试看。

**Comment by ChanMenglin** [comment]
OK，访问正常

**Comment by lizehua-cn** [comment]
北京联通 / 手机切4g 都无法访问
提示我 `您的连接不是私密连接`
dns 设置的是 `114.114.114.114/8.8.8.8`
是证书过期了吗?

**Comment by ruanyf** [comment]
网站用了cloudflare的CDN，看来被屏蔽了。

现在CDN关了，你再试试。
