### ISSUE TITLE
await命令的返回值说法有疑问

### ISSUE THREAD

**Issue by snow212-cn** [ruanyf/es6tutorial#957]
这句话想了两天也没明白
> 正常情况下，await命令后面是一个 Promise 对象，返回该对象的结果。  

[原文位置](https://es6.ruanyifeng.com/#docs/async#await-命令)
返回该对象的结果，是哪个结果，表述的含糊不清。写出这段测试，返回的不是Promise对象本身，是resolve参数吧
```javascript
(async ()=>{console.log(await new Promise(resolve=>resolve('test')))})()
//test
```

**Comment by ruanyf** [comment]
返回 Promise 实例的结果。
