### ISSUE TITLE
class的继承。子类不调用super()也能实例化成功？

### ISSUE THREAD

**Issue by 24min** [ruanyf/es6tutorial#959]
我是在谷歌开发者工具的控制台中运行下面的代码。
谷歌浏览器版本：版本 80.0.3987.132（正式版本） （64 位）。
不太明白为什么。谢谢~
`class father {
    constructor() {
        this.a = 1
    }
}

class son extends father {
    method() {
        console.log('sss',this.a)
    }
}

let new_son = new son()
new_son.method();`
![calss_super](https://user-images.githubusercontent.com/32154293/76530753-27529780-64af-11ea-8f84-ef90be9fc44c.png)

**Comment by ruanyf** [comment]
接着往下读。

**Comment by 24min** [comment]
> 接着往下读。

谢谢~ 自己确实没看仔细
