### ISSUE TITLE
”数值的扩展-指数运算符“一节有关 V8 的信息过时

### ISSUE THREAD

**Issue by kidonng** [ruanyf/es6tutorial#965]
https://github.com/ruanyf/es6tutorial/blob/74acd642fa4c2d88cbf5e860ca5792216e74a7fc/docs/number.md#%E6%8C%87%E6%95%B0%E8%BF%90%E7%AE%97%E7%AC%A6

> 注意，V8 引擎的指数运算符与Math.pow的实现不相同，对于特别大的运算结果，两者会有细微的差异。

在 Chrome 82.0.4085.12 (V8 8.2.297.1) 上测试，`Math.pow(99, 99)` 和 `99 ** 99` 的结果都是 `3.697296376497268e+197` (即原先 `99 ** 99` 的结果)。

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
