### ISSUE TITLE
Proxy 实现一个生成各种 DOM 节点的通用函数dom示例代码注释错误

### ISSUE THREAD

**Issue by moozeeli** [ruanyf/es6tutorial#966]
实现一个生成各种 DOM 节点的通用函数dom，示例代码中双斜杠被识别为注释
对应的代码位置在下面代码的第三行， 把代码割开了。
<img width="369" alt="屏幕快照 2020-03-23 上午10 41 31" src="https://user-images.githubusercontent.com/11691439/77275368-14339900-6cf3-11ea-9e0e-d544f8b8b996.png">

**Comment by ruanyf** [comment]
这个是页面代码高亮的问题，实际可以在浏览器执行。
