### ISSUE TITLE
for of不支持return跳出循环

### ISSUE THREAD

**Issue by SageSanyue** [ruanyf/es6tutorial#976]
17章“iterator和for of循环”的最后一节“与其他遍历语法的比较”，文字的倒数第5行“不同于forEach方法，它可以与break、continue和return配合使用。”里面说for of可以配合return使用，但私以为for of可以配合break和continue但不能配合return:
![image](https://user-images.githubusercontent.com/34312844/79750467-97bcc600-8343-11ea-8e0a-a24dec71486b.png)

for of支持break跳出循环：
```
var iterable = [10, 20, 30]
for (var value of iterable) {
  if (value === 20) { break }
  value += 1
  console.log(value)
}
// 打印11
```
for of支持continue跳出循环：
```
var iterable = [10, 20, 30]
for (var value of iterable) {
  if (value === 20) { continue }
  value += 1
  console.log(value)
}
// 打印11 31
```
但for of不支持return跳出循环：
```
var iterable = [10, 20, 30]
for (var value of iterable) {
  if (value === 20) { return }
  value += 1
  console.log(value)
}
// 报错VM355:3 Uncaught SyntaxError: Illegal return statement
```
![image](https://user-images.githubusercontent.com/34312844/79749828-74dde200-8342-11ea-9eda-b083f7fdbf02.png)

**Comment by Dcatfly** [comment]
emmm `return`要放在函数里面

**Comment by ruanyf** [comment]
要放在函数里面

**Comment by SageSanyue** [comment]
> emmm `return`要放在函数里面

哦哦，好的，多谢啦。

**Comment by SageSanyue** [comment]
> 要放在函数里面

嗯嗯，明白了，谢谢阮老师！

**Comment by ghostcode** [comment]
Node 环境下可以直接执行，浏览器下确实需要放在函数里。
