### ISSUE TITLE
es6 module 导入同路径同实例的前提是什么？

### ISSUE THREAD

**Issue by LongTengDao** [ruanyf/es6tutorial#978]
1. 应该是要求同一个页面内的请求才共享实例吧？如果是跨页面（不论是否跨源），应该是不同的实例吧？
2. 对缓存有效性的要求是怎样的？如果缓存失效了再导入，应该就是另一份实例了吧？如果重新请求时返回 304，是否依旧算是同一份？如果没有返回 304，但 ETag 相同呢？如果 ETag 是 W/"" 模式呢？

**Comment by ruanyf** [comment]
请提供对应的原文章节。

**Comment by LongTengDao** [comment]
@ruanyf 谢谢！

https://github.com/ruanyf/es6tutorial/blame/gh-pages/docs/module-loader.md#L232-L272

（经过我在 Chrome 上的测试，似乎浏览器会完全无视任何禁止缓存的策略，一律使用同一份缓存，绝不重新加载该路径，不知道这是实现问题，还是规范中就是如此规定的？我在规范中搜索没有发现相关内容）

**Comment by ruanyf** [comment]
不考虑实现的问题了。

这里是指正常情况下，两个地方引用同一个模块，得到的是同一个实例。
