### ISSUE TITLE
Promise 的疑问

### ISSUE THREAD

**Issue by Murongyge** [ruanyf/es6tutorial#98]
阮老师,在书中(Page 122-123)的Promise.resolve方法中,其中讲到回调立即执行,我有些疑问:
我将代码做了如下改动(只是增加了些内容)
var p = Promise.resolve('Hello');
var d = '';

p.then(function (s){
    console.log(s);
    console.log(d);
})
d =  'oked'
console.log(p);
//
结果:
Promise { 'Hello' }
Hello
oked
看此,p仍然是异步等待的
初学node,希望老师解惑

**Comment by ruanyf** [comment]
Promise是当前一轮同步任务结束后，再执行任务。

参考这里 http://javascript.ruanyifeng.com/bom/timer.html#toc7
