### ISSUE TITLE
【ECMAScript 6 入门】书中有一个错别字，请阮老师知晓并评判。叨扰了！

### ISSUE THREAD

**Issue by fourseas1998** [ruanyf/es6tutorial#981]
#### 位置：第8章函数的扩展，第3节严格模式，第二段文字：
**"ES2016 做了一点修改，规定只要函数参数使用了默认值、解构赋值、或者扩展运算符，那么函数内部就不能显式设定为严格模式，否则会报错。"**
其中 **“显式”** 的 **式** 是不是错别字？我觉得应该是 **“显示”** 才对。

因此，特来询问，还请阮老师做评判。
我是刚毕业的大学生，目前在自学ES6。如果是我理解错了，那还请老师为我解惑，为什么是用这个字。

望回复，谢谢。叨扰了！

**Comment by Kafuu-Chinocya** [comment]
个人感觉“式”像是强调一种方式，显式的反义词就是隐式。
比如说js的 == 运算符就是在隐式的转换了你的数据类型然后再进行判断的（比如1 == '1' 为true），显式就相当于不使用 === 运算符，但是你要判断类型和数据都相等你可能会这样写1 == Number('1')，此时是显式的将'1'转换成Number类型。

**Comment by fourseas1998** [comment]
学到了！原来还有这层含义在里面。
十分感谢你为我解惑！谢谢了
