### ISSUE TITLE
函数的length属性介绍有误

### ISSUE THREAD

**Issue by ghost** [ruanyf/es6tutorial#986]
https://es6.ruanyifeng.com/#docs/function

8.函数的扩展   函数的length属性部分描述似乎有误
文中代码示例为：
(function (a) {}).length // 1
(function (a = 5) {}).length // 0
(function (a, b, c = 5) {}).length // 2

文中结论描述为：
上面代码中，length属性的返回值，等于函数的参数个数减去指定了默认值的参数个数。比如，上面最后一个函数，定义了 3 个参数，其中有一个参数c指定了默认值，因此length属性等于3减去1，最后得到2。

事实上如果最后一个表达式是:
(function (a=5, b, c) {}).length，它的length会是0

如果是：
(function (a, b=5, c) {}).length，它的length会是1

**Comment by ruanyf** [comment]
https://wangdoc.com/es6/function.html#%E5%8F%82%E6%95%B0%E9%BB%98%E8%AE%A4%E5%80%BC%E7%9A%84%E4%BD%8D%E7%BD%AE

**Comment by ghost** [comment]
哇，谢谢阮老师




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ruan YiFeng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月12日(星期二) 中午11:55
收件人:&nbsp;"ruanyf/es6tutorial"<es6tutorial@noreply.github.com&gt;;
抄送： &nbsp;“柳柒” <2245874113@qq.com&gt;;“作者” <author@noreply.github.com&gt;;
主题:&nbsp;Re: [ruanyf/es6tutorial] 函数的length属性介绍有误 (#986)





 
https://wangdoc.com/es6/function.html#%E5%8F%82%E6%95%B0%E9%BB%98%E8%AE%A4%E5%80%BC%E7%9A%84%E4%BD%8D%E7%BD%AE
  
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。
