### ISSUE TITLE
There may be an error in the description of the weakSet

### ISSUE THREAD

**Issue by lq9958** [ruanyf/es6tutorial#989]
As mentioned in the section of weakSet, as long as an object with an Iterable interface can be put into a weakSet, but when I put a normal object, just like: `{name:'Tom'}` , it can also be added into a weakSet. I remember that the normal object does not implement the Iterable interface.

**Comment by ruanyf** [comment]
```javascript
const ws = new WeakSet({foo: 'bar'});
// Uncaught TypeError: object is not iterable
```
