### ISSUE TITLE
es官方教程

### ISSUE THREAD

**Issue by huamanlou112233** [ruanyf/es6tutorial#990]
<img width="623" alt="屏幕快照 2020-05-27 下午5 47 52" src="https://user-images.githubusercontent.com/66008319/83004560-64581000-a042-11ea-9902-55ef526fed06.png">
把第二行的IF语句改为 if ( n <= 2 ) {return 1}; 是不是更合理一点，在斐波那契数列中n的值对应数列值才正确。

**Comment by ruanyf** [comment]
这个例子的斐波那契数列，`n`从`0`开始算。
