### ISSUE TITLE
matchAll 全局修饰符

### ISSUE THREAD

**Issue by mgsers** [ruanyf/es6tutorial#992]
https://es6.ruanyifeng.com/#docs/regex#String-prototype-matchAll
```
const string = 'test1test2test3';

// g 修饰符加不加都可以
const regex = /t(e)(st(\d?))/g;

for (const match of string.matchAll(regex)) {
  console.log(match);
}
// ["test1", "e", "st1", "1", index: 0, input: "test1test2test3"]
// ["test2", "e", "st2", "2", index: 5, input: "test1test2test3"]
// ["test3", "e", "st3", "3", index: 10, input: "test1test2test3"]
```
老师，正则表达式那里如果去掉全局修饰符的话chrome浏览是会报
```
String.prototype.matchAll called with a non-global RegExp argument
```
错误的，所以不应该是 g 修饰符加不加都可以
chrome版本83

**Comment by Mookiepiece** [comment]
ES规范：https://tc39.es/ecma262/#sec-string.prototype.matchall

> If ToString(flags) does not contain "g", throw a TypeError exception.


MDN也改了，这是该页的历史记录，可以看到备注指向了那个pr：
https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll$history


依据是这个，2019年10月被合并：

> tc39/proposal-string-replaceall的pull的24

所以chrome78正常，但是83及未来会报错

**Comment by bosens-China** [comment]
赞同，我也看到了这个问题，报错信息提示`TypeError: String.prototype.matchAll called with a non-global RegExp argument`，在创建变量依然出现问题，所以这个`g`修饰符是必须要添加的
``` js
var reg = /\[\d+\]/
var test =  'ab[0][1]'.matchAll(reg)
```

**Comment by ruanyf** [comment]
谢谢提醒，我已经把那句话删了。
