### ISSUE TITLE
win + ← 改变浏览器大小后的显示问题

### ISSUE THREAD

**Issue by kvii** [ruanyf/es6tutorial#998]
# 缩小浏览器后使用笔记本触摸板将页面往左滑会出现 bug，见图

![image](https://user-images.githubusercontent.com/56432636/88471126-aebd1680-cf37-11ea-9cbe-30e8981f57c3.png)

> 浏览器为新 Edge，在 Chrome 中没有此问题。
系统为 win10 专业版的预览版本，电脑是笔记本电脑
![image](https://user-images.githubusercontent.com/56432636/88471160-44f13c80-cf38-11ea-88c7-fdcaab38a3e3.png)

**Comment by kvii** [comment]
更正：chrome 同样有此问题，触发问题的条件是使用鼠标滚轮放大网页。
使用触摸板手势放大的网页没有这个问题。

**Comment by ruanyf** [comment]
我手边没有 Windows 笔记本，没法复现。

你用网道的镜像代替吧。https://wangdoc.com/es6/
